table aux_fact_less_polissa_fraude
	lineageTag: 3f5379f2-9c18-48ed-8b77-026e67cad5ad

	column sector_id
		dataType: int64
		formatString: 0
		lineageTag: 10953bc4-297c-4610-85d3-04ba336bda54
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column sector
		dataType: string
		lineageTag: 0095b469-0272-48c1-b53b-3d3871591b8a
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	partition aux_fact_less_polissa_fraude = m
		mode: import
		source =
				let
				    Origen = fact_less_polissa_fraude,
				    #"Otras columnas quitadas" = Table.SelectColumns(Origen,{"sector", "sector_id"}),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Otras columnas quitadas",{"sector_id", "sector"}),
				    #"Duplicados quitados" = Table.Distinct(#"Columnas reordenadas", {"sector_id"})
				in
				    #"Duplicados quitados"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

