table aux_fact_cabals_mínims
	lineageTag: 2d6d96f9-ea0b-476f-bf7f-39f8994b73ab

	column sector_id
		dataType: double
		lineageTag: 8330c621-01e7-4212-9720-b91474bf5099
		summarizeBy: sum
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sector
		dataType: string
		lineageTag: 8d587597-2ca6-4bb3-8455-69347556cf69
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	partition aux_fact_cabals_mínims = m
		mode: import
		source =
				let
				    Origen = fact_cabals_mínims,
				    #"Columnas reordenadas" = Table.ReorderColumns(Origen,{"sector_id", "sectors", "arteria", "fecha", "q_min", "gerencia_id"}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Columnas reordenadas",{"sector_id", "sectors"}),
				    #"Duplicados quitados" = Table.Distinct(#"Otras columnas quitadas", {"sector_id"}),
				    #"Duplicados quitados1" = Table.Distinct(#"Duplicados quitados", {"sectors"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Duplicados quitados1",{{"sectors", "sector"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

