table aux_fact_volum_lliurat
	lineageTag: b95e398e-eb64-43bd-8d03-d184fb33ff12

	column sector_id
		dataType: double
		lineageTag: cd08df67-38ed-4b3f-b199-673f2d8afa03
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sector
		dataType: string
		lineageTag: 5882a5eb-f4b4-46f7-82af-362a4d7a1907
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	partition aux_fact_volum_lliurat = m
		mode: import
		source =
				let
				    Origen = fact_volum_lliurat,
				    #"Columnas reordenadas" = Table.ReorderColumns(Origen,{"sector_id", "Sectors", "pis_pressio", "fecha", "volum_lliurat", "gerencia_id"}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Columnas reordenadas",{"sector_id", "Sectors"}),
				    #"Duplicados quitados" = Table.Distinct(#"Otras columnas quitadas", {"sector_id"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Duplicados quitados",{{"Sectors", "sector"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

