table aux_fact_bossa
	lineageTag: 1d8c29f0-bdfa-4a99-9405-634464c9bd35

	column sector
		dataType: string
		lineageTag: d7e239b1-e7b0-4604-9795-462c109cf209
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column sector_id
		dataType: int64
		formatString: 0
		lineageTag: 9224b55c-6de4-4524-afbf-68d3bbe3847f
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	partition aux_fact_bossa = m
		mode: import
		source =
				let
				    Origen = fact_bossa,
				    #"Otras columnas quitadas" = Table.SelectColumns(Origen,{"sector"}),
				    #"Duplicados quitados" = Table.Distinct(#"Otras columnas quitadas"),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Duplicados quitados",{{"sector", Text.Proper, type text}}),
				    #"Texto limpio" = Table.TransformColumns(#"Poner En Mayúsculas Cada Palabra",{{"sector", Text.Clean, type text}}),
				    #"Texto recortado" = Table.TransformColumns(#"Texto limpio",{{"sector", Text.Trim, type text}}),
				    #"Consultas combinadas" = Table.FuzzyNestedJoin(#"Texto recortado", {"sector"}, dim_dades_sectors, {"sector"}, "dim_dades_sectors", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),
				    #"Se expandió dim_dades_sectors" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_dades_sectors", {"sector_id"}, {"dim_dades_sectors.sector_id"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió dim_dades_sectors",{{"dim_dades_sectors.sector_id", "sector_id"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

