table aux_dim_ortomat_sectores
	lineageTag: e117b49c-b73b-4206-a59d-5446004b0741

	column sector_id
		dataType: int64
		formatString: 0
		lineageTag: fb66219e-2e74-4fc7-88cd-f4f2b21b6db9
		summarizeBy: sum
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column num_points
		dataType: int64
		formatString: 0
		lineageTag: d697f75e-3ad5-4118-9098-cb494915deef
		summarizeBy: sum
		sourceColumn: num_points

		annotation SummarizationSetBy = Automatic

	partition aux_dim_ortomat_sectores = m
		mode: import
		queryGroup: Auxiliares
		source =
				let
				
				    Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1dca9OE3HQzH16kwQty0mn2sH6krPn0RFOmR9uFBWXJI/edit?gid=709331709#gid=709331709"),
				    data = Origen{[name = "Sectores_sembrados_numero", ItemKind = "Table"]}[Data],
				    #"Otras columnas quitadas" = Table.SelectColumns(data,{"Column2", "Column6"}),
				    #"Filas filtradas" = Table.SelectRows(#"Otras columnas quitadas", each ([Column2] <> "")),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Filas filtradas", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(        #"Encabezados promovidos",        {{"SAP_ID_2", "sector_id"}, {"NUMPOINTS", "num_points"}}    ),
				    #"Duplicados eliminados" = Table.Distinct(        #"Columnas con nombre cambiado",        {"sector_id"}    ),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Duplicados eliminados",{{"sector_id", Int64.Type}, {"num_points", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

