table Bossa_de_Limitadors_BCNN
	lineageTag: e7a0cca2-a283-46d0-b0be-5d6139d41385

	column dop
		dataType: string
		lineageTag: 544fdba7-ee2a-4142-b41c-42e4a0673540
		summarizeBy: none
		sourceColumn: dop

		annotation SummarizationSetBy = Automatic

	column sector
		dataType: string
		lineageTag: cd0355eb-4fc1-4271-a95f-274f3e81efc5
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column rendiment_sector_(maig_2026)
		dataType: double
		lineageTag: a5360a89-c7b9-46f7-a4ef-a569c8e22217
		summarizeBy: sum
		sourceColumn: rendiment_sector_(maig_2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column polissa_subm
		dataType: string
		lineageTag: d602d106-0914-46f1-8e08-bfc728a5e46e
		summarizeBy: none
		sourceColumn: polissa_subm

		annotation SummarizationSetBy = Automatic

	column tipus_subm
		dataType: string
		lineageTag: abb433dd-666b-49bd-923d-406aac3e20e0
		summarizeBy: none
		sourceColumn: tipus_subm

		annotation SummarizationSetBy = Automatic

	column data_instalacion
		dataType: dateTime
		formatString: Long Date
		lineageTag: c9fa9fb6-d210-4d72-9a9e-58eae1e7d51e
		summarizeBy: none
		sourceColumn: data_instalacion

		variation Variación
			isDefault
			relationship: d85bfa09-537e-48b6-923d-aaf146e8ce80
			defaultHierarchy: LocalDateTable_8be2f08e-359c-41a5-8804-3baa529269d8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column edat_comp
		dataType: int64
		formatString: 0
		lineageTag: f1de348c-f4e7-4049-9ef2-0848bd8ac408
		summarizeBy: sum
		sourceColumn: edat_comp

		annotation SummarizationSetBy = Automatic

	column diam_comp
		dataType: int64
		formatString: 0
		lineageTag: 4f2a986e-1e13-4c00-aa80-2295ea2f2e23
		summarizeBy: sum
		sourceColumn: diam_comp

		annotation SummarizationSetBy = Automatic

	column dn_limitador
		dataType: string
		lineageTag: a1a8639c-4c6c-41f1-a31e-a0d88527aa9c
		summarizeBy: none
		sourceColumn: dn_limitador

		annotation SummarizationSetBy = Automatic

	column data_alta_subm
		dataType: dateTime
		formatString: Long Date
		lineageTag: 11ffc8da-2e96-4c28-b5f3-7571e69117b2
		summarizeBy: none
		sourceColumn: data_alta_subm

		variation Variación
			isDefault
			relationship: 903b1105-ffd7-4a73-913f-6150570ea37d
			defaultHierarchy: LocalDateTable_148e1706-1d8d-4ce9-a995-a9943583738a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column consum_mig_dia
		dataType: double
		lineageTag: 87afc140-3619-4fde-b4b4-cf668263b9fb
		summarizeBy: sum
		sourceColumn: consum_mig_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consum_anual_estimat
		dataType: double
		lineageTag: 0ad89c26-0c86-4fb6-a8cb-1ea3aa059a8c
		summarizeBy: sum
		sourceColumn: consum_anual_estimat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estrategic
		dataType: string
		lineageTag: ed1546af-159b-439e-8c85-8a483c88dc2e
		summarizeBy: none
		sourceColumn: estrategic

		annotation SummarizationSetBy = Automatic

	column prioritat
		dataType: string
		lineageTag: 7fc70b2e-9c0d-4ede-a83a-5cbab47c171d
		summarizeBy: none
		sourceColumn: prioritat

		annotation SummarizationSetBy = Automatic

	column necessitat
		dataType: string
		lineageTag: 5b27adcd-b8bf-4b14-87a0-5eb7809459f5
		summarizeBy: none
		sourceColumn: necessitat

		annotation SummarizationSetBy = Automatic

	column v12_en_m3
		dataType: double
		lineageTag: 3847680e-ac10-40fd-be55-d5764a6b85d3
		summarizeBy: sum
		sourceColumn: v12_en_m3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column períodes_amb_estimades
		dataType: int64
		formatString: 0
		lineageTag: 0d4aa34a-7775-49fc-ab24-28e981f5d937
		summarizeBy: sum
		sourceColumn: períodes_amb_estimades

		annotation SummarizationSetBy = Automatic

	partition Bossa_de_Limitadors_BCNN = m
		mode: import
		source = ```
				//
				
				// ESTA FACT SE GENERA A PARTIR DEL ARCHIVO DE GOOGLE DRIVE 
				
				//            Bossa de Limitadors_Canvis per DOP 
				
				// PESTAÑA:
				
				//              BCNN
				
				let
				  Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1G9GggBeQbtbK0kD-I7o1ypbgcIGSwQGkRXSvvtn8MaE/edit?gid=1742937846#gid=1742937846"),
				  BCNN_Table = Origen{[name = "BCNN", ItemKind = "Table"]}[Data],
				  Encabezados =
				        Table.PromoteHeaders(BCNN_Table, [PromoteAllScalars=true]),
				
				    Columnas =
				        Table.TransformColumnNames(
				            Encabezados,
				            each Text.Replace(Text.Lower(_), " ", "_")
				        ),
				
				    Renombradas =
				        Table.RenameColumns(
				            Columnas,
				            {
				                {"data_instal·lació", "data_instalacion"},
				                {"estratègic", "estrategic"}
				            }
				        ),
				
				    Texto =
				        Table.TransformColumns(
				            Renombradas,
				            {
				                {"sector", Text.Proper, type text},
				                {"prioritat", Text.Proper, type text}
				            }
				        ),
				
				    Seleccionadas =
				        Table.SelectColumns(
				            Texto,
				            {
				                "dop",
				                "sector",
				                "rendiment_sector_(maig_2026)",
				                "polissa_subm",
				                "tipus_subm",
				                "data_instalacion",
				                "edat_comp",
				                "diam_comp",
				                "dn_limitador",
				                "data_alta_subm",
				                "consum_mig_dia",
				                "consum_anual_estimat",
				                "estrategic",
				                "prioritat",
				                "necessitat",
				                "v12_en_m3",
				                "períodes_amb_estimades"
				            }
				        ),
				
				    SinErrores =
				        Table.ReplaceErrorValues(
				            Seleccionadas,
				            List.Transform(Table.ColumnNames(Seleccionadas), each {_, null})
				        ),
				
				    Tipos =
				        Table.TransformColumnTypes(
				            SinErrores,
				            {
				                {"rendiment_sector_(maig_2026)", type number},
				                {"polissa_subm", type text},
				                {"data_instalacion", type date},
				                {"edat_comp", Int64.Type},
				                {"diam_comp", Int64.Type},
				                {"data_alta_subm", type date},
				                {"consum_mig_dia", type number},
				                {"consum_anual_estimat", type number},
				                {"estrategic", type text},
				                {"necessitat", type text},
				                {"v12_en_m3", type number},
				                {"períodes_amb_estimades", Int64.Type}
				            }
				        ),
				
				    Limpieza =
				        Table.TransformColumns(
				            Tipos,
				            {
				                {
				                    "sector",
				                    each if _ = "" then null else _,
				                    type nullable text
				                },
				                {
				                    "rendiment_sector_(maig_2026)",
				                    each if _ = "" then null else _,
				                    type nullable number
				                },
				                {
				                    "dn_limitador",
				                    each if _ = "" or _ = "-" then null else _,
				                    type nullable text
				                }
				            }
				        ),
				
				    SinDuplicados =
				        Table.Distinct(Limpieza),
				
				    Resultado =
				        Table.SelectRows(
				            SinDuplicados,
				            each List.NonNullCount(Record.FieldValues(_)) > 0
				        )
				
				in
				    Resultado
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

