table Bossa_de_Limitadors_BES
	lineageTag: 03775801-4c54-4520-a26d-99fa18484204

	column dop
		dataType: string
		lineageTag: d74275c3-0de8-43dd-b2f1-69bd7adbd099
		summarizeBy: none
		sourceColumn: dop

		annotation SummarizationSetBy = Automatic

	column sector
		dataType: string
		lineageTag: 2613a3d9-9983-4aa9-b46e-d80bf5dadade
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column rendiment_sector_(maig_2026)
		dataType: double
		lineageTag: 1b75fb31-005a-4bc4-bc73-801b80acc56a
		summarizeBy: sum
		sourceColumn: rendiment_sector_(maig_2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column polissa_subm
		dataType: string
		lineageTag: a45b48a6-3f9b-473f-b2a4-e9fcfd0fd814
		summarizeBy: none
		sourceColumn: polissa_subm

		annotation SummarizationSetBy = Automatic

	column tipus_subm
		dataType: string
		lineageTag: a2bd9e05-d75e-4f65-834d-7b7fd88be22e
		summarizeBy: none
		sourceColumn: tipus_subm

		annotation SummarizationSetBy = Automatic

	column data_instalacion
		dataType: dateTime
		formatString: Long Date
		lineageTag: cdae158c-47c0-4f65-af44-d613992a0f53
		summarizeBy: none
		sourceColumn: data_instalacion

		variation Variación
			isDefault
			relationship: cf1f3c16-31b8-41a7-bc68-94b4fb9b747b
			defaultHierarchy: LocalDateTable_9767ccab-887e-4f0a-9440-14dbef8098c6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column edat_comp
		dataType: int64
		formatString: 0
		lineageTag: 0f4b4906-7a09-4f9f-bdc2-8005fb1b714e
		summarizeBy: sum
		sourceColumn: edat_comp

		annotation SummarizationSetBy = Automatic

	column diam_comp
		dataType: int64
		formatString: 0
		lineageTag: bd51c1d3-c3bd-4dde-ae6f-45aa6ec7fd71
		summarizeBy: sum
		sourceColumn: diam_comp

		annotation SummarizationSetBy = Automatic

	column dn_limitador
		dataType: string
		lineageTag: e69d208c-e972-454a-922e-e3189814560d
		summarizeBy: none
		sourceColumn: dn_limitador

		annotation SummarizationSetBy = Automatic

	column data_alta_subm
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6a581cbc-0383-4ba7-b0c0-7da95e886f1d
		summarizeBy: none
		sourceColumn: data_alta_subm

		variation Variación
			isDefault
			relationship: f37c0c2c-3f68-4617-ae70-302c00f023b9
			defaultHierarchy: LocalDateTable_83e2c710-b96d-46d8-910a-aa4aa6dccab8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column consum_mig_dia
		dataType: double
		lineageTag: d8d071cb-e16c-4fdf-9359-1fd2afa0ea11
		summarizeBy: sum
		sourceColumn: consum_mig_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consum_anual_estimat
		dataType: double
		lineageTag: ac06e4fc-7acd-4879-8536-51d782fa6d0f
		summarizeBy: sum
		sourceColumn: consum_anual_estimat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estrategic
		dataType: string
		lineageTag: 453676d8-62d7-43a5-b171-efe066cd3c92
		summarizeBy: none
		sourceColumn: estrategic

		annotation SummarizationSetBy = Automatic

	column prioritat
		dataType: string
		lineageTag: b42b5ed9-5178-4e40-80a8-41b18326f9f7
		summarizeBy: none
		sourceColumn: prioritat

		annotation SummarizationSetBy = Automatic

	column necessitat
		dataType: string
		lineageTag: 688815a1-8edb-43f4-8afd-201f55871c5b
		summarizeBy: none
		sourceColumn: necessitat

		annotation SummarizationSetBy = Automatic

	column v12_en_m3
		dataType: double
		lineageTag: 7018169f-a2ce-4565-a445-61e68ff542a3
		summarizeBy: sum
		sourceColumn: v12_en_m3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column periodos_consecutivos_con_ea
		dataType: int64
		formatString: 0
		lineageTag: 92179bcc-f22e-477c-bfe9-962684e7b32c
		summarizeBy: sum
		sourceColumn: periodos_consecutivos_con_ea

		annotation SummarizationSetBy = Automatic

	partition Bossa_de_Limitadors_BES = m
		mode: import
		source = ```
				//
				
				// ESTA FACT SE GENERA A PARTIR DEL ARCHIVO DE GOOGLE DRIVE 
				
				//            Bossa de Limitadors_Canvis per DOP 
				
				// PESTAÑA:
				
				//              BES
				
				let
				  Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1G9GggBeQbtbK0kD-I7o1ypbgcIGSwQGkRXSvvtn8MaE/edit?gid=999620324#gid=999620324"),
				    BES_Table = Origen{[name = "BES", ItemKind = "Table"]}[Data],
				    Encabezados =
				        Table.PromoteHeaders(BES_Table, [PromoteAllScalars=true]),
				
				    Columnas =
				        Table.TransformColumnNames(
				            Encabezados,
				            each Text.Replace(Text.Lower(_), " ", "_")
				        ),
				
				    Renombradas =
				        Table.RenameColumns(
				            Columnas,
				            {
				                {"data_instal·lació", "data_instalacion"},
				                {"estratègic", "estrategic"}
				            }
				        ),
				
				    Texto =
				        Table.TransformColumns(
				            Renombradas,
				            {
				                {"sector", Text.Proper, type text},
				                {"prioritat", Text.Proper, type text}
				            }
				        ),
				
				    Seleccionadas =
				        Table.SelectColumns(
				            Texto,
				            {
				                "dop",
				                "sector",
				                "rendiment_sector_(maig_2026)",
				                "polissa_subm",
				                "tipus_subm",
				                "data_instalacion",
				                "edat_comp",
				                "diam_comp",
				                "dn_limitador",
				                "data_alta_subm",
				                "consum_mig_dia",
				                "consum_anual_estimat",
				                "estrategic",
				                "prioritat",
				                "necessitat",
				                "v12_en_m3",
				                "periodos_consecutivos_con_ea"
				            }
				        ),
				
				    SinErrores =
				        Table.ReplaceErrorValues(
				            Seleccionadas,
				            List.Transform(Table.ColumnNames(Seleccionadas), each {_, null})
				        ),
				
				    Tipos =
				        Table.TransformColumnTypes(
				            SinErrores,
				            {
				                {"rendiment_sector_(maig_2026)", type number},
				                {"polissa_subm", type text},
				                {"data_instalacion", type date},
				                {"edat_comp", Int64.Type},
				                {"diam_comp", Int64.Type},
				                {"data_alta_subm", type date},
				                {"consum_mig_dia", type number},
				                {"consum_anual_estimat", type number},
				                {"estrategic", type text},
				                {"necessitat", type text},
				                {"v12_en_m3", type number},
				                {"periodos_consecutivos_con_ea", Int64.Type}
				            }
				        ),
				
				    Limpieza =
				        Table.TransformColumns(
				            Tipos,
				            {
				                {
				                    "sector",
				                    each
				                        let v = if _ = "" then null else _
				                        in if v = "0" then null else v,
				                    type nullable text
				                },
				                {
				                    "rendiment_sector_(maig_2026)",
				                    each if _ = "" then null else _,
				                    type nullable number
				                },
				                {
				                    "dn_limitador",
				                    each
				                        if _ = "" or _ = "-" then null else _,
				                    type nullable text
				                }
				            }
				        ),
				
				    SinDuplicados =
				        Table.Distinct(Limpieza),
				
				    Resultado =
				        Table.SelectRows(
				            SinDuplicados,
				            each List.NonNullCount(Record.FieldValues(_)) > 0
				        )
				
				in
				    Resultado
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

