table Bossa_de_Limitadors_LLOBN
	lineageTag: 992a8842-8956-40fd-8f41-5b616d58f12c

	column dop
		dataType: string
		lineageTag: a8c5be53-cd7a-437c-a2e4-7a78aec22bec
		summarizeBy: none
		sourceColumn: dop

		annotation SummarizationSetBy = Automatic

	column sector
		dataType: string
		lineageTag: 7e9bba49-9d90-43f2-b859-366a61d59d7a
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column rendiment_sector_(maig_2026)
		dataType: double
		lineageTag: 993ac3d0-15b8-4699-94a2-02d021a0f477
		summarizeBy: sum
		sourceColumn: rendiment_sector_(maig_2026)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column polissa_subm
		dataType: string
		lineageTag: 3cce6539-f5a2-4ea3-8ca7-cea6232897e0
		summarizeBy: none
		sourceColumn: polissa_subm

		annotation SummarizationSetBy = Automatic

	column tipus_subm
		dataType: string
		lineageTag: 628cc0d8-f239-465e-9337-3ca25f7e182c
		summarizeBy: none
		sourceColumn: tipus_subm

		annotation SummarizationSetBy = Automatic

	column data_instalacion
		dataType: dateTime
		formatString: Long Date
		lineageTag: dab99bf5-b80a-4b6d-8875-28bcf8e0654a
		summarizeBy: none
		sourceColumn: data_instalacion

		variation Variación
			isDefault
			relationship: 51c83fd9-a583-4be4-960d-caa485001d0f
			defaultHierarchy: LocalDateTable_1e5bc8dd-8a0d-4fde-b9de-c8dea6a960c7.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column edat_comp
		dataType: int64
		formatString: 0
		lineageTag: f5e26e64-0abc-4e35-94cd-9c613096fa71
		summarizeBy: sum
		sourceColumn: edat_comp

		annotation SummarizationSetBy = Automatic

	column diam_comp
		dataType: int64
		formatString: 0
		lineageTag: 1b5198cd-7bcd-426b-b807-24886faeb8b9
		summarizeBy: sum
		sourceColumn: diam_comp

		annotation SummarizationSetBy = Automatic

	column dn_limitador
		dataType: string
		lineageTag: 0bc8d882-1716-467f-87f0-d44cd9a635a8
		summarizeBy: none
		sourceColumn: dn_limitador

		annotation SummarizationSetBy = Automatic

	column data_alta_subm
		dataType: dateTime
		formatString: Long Date
		lineageTag: fcbcb370-404d-4e90-b613-49166d46fa25
		summarizeBy: none
		sourceColumn: data_alta_subm

		variation Variación
			isDefault
			relationship: 4fd91add-e666-4566-aefd-8a68ed1decfe
			defaultHierarchy: LocalDateTable_50ffd127-7d76-4eac-b9f1-a34291d6b8b8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column consum_mig_dia
		dataType: double
		lineageTag: 7bd3187f-6cb7-4e12-9817-092f99d72fab
		summarizeBy: sum
		sourceColumn: consum_mig_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consum_anual_estimat
		dataType: double
		lineageTag: 22b4e02c-f79c-401e-b7f6-518388a48897
		summarizeBy: sum
		sourceColumn: consum_anual_estimat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estrategic
		dataType: string
		lineageTag: 15d36b0e-460c-4bd1-81b6-f9560c770913
		summarizeBy: none
		sourceColumn: estrategic

		annotation SummarizationSetBy = Automatic

	column prioritat
		dataType: string
		lineageTag: 18bcbd0c-36c3-4291-b1a3-5d78d3a6ed21
		summarizeBy: none
		sourceColumn: prioritat

		annotation SummarizationSetBy = Automatic

	column necessitat
		dataType: string
		lineageTag: a8df4d12-976c-461f-b412-11f8d2e8e534
		summarizeBy: none
		sourceColumn: necessitat

		annotation SummarizationSetBy = Automatic

	column v12_en_m3
		dataType: double
		lineageTag: c30b5f88-5486-4c5e-81f7-db73954ed863
		summarizeBy: sum
		sourceColumn: v12_en_m3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column periodos_consecutivos_con_ea
		dataType: int64
		formatString: 0
		lineageTag: 7928b22d-2ea2-4cf4-9f25-fc9e887c03a1
		summarizeBy: sum
		sourceColumn: periodos_consecutivos_con_ea

		annotation SummarizationSetBy = Automatic

	partition Bossa_de_Limitadors_LLOBN = m
		mode: import
		source = ```
				//
				
				// ESTA FACT SE GENERA A PARTIR DEL ARCHIVO DE GOOGLE DRIVE 
				
				//            Bossa de Limitadors_Canvis per DOP 
				
				// PESTAÑA:
				
				//              LLOBN
				
				let
				  Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1G9GggBeQbtbK0kD-I7o1ypbgcIGSwQGkRXSvvtn8MaE/edit?gid=3033074#gid=3033074"),
				   LLOBN_Table = Origen{[name = "LLOBN", ItemKind = "Table"]}[Data],
				   Encabezados =
				        Table.PromoteHeaders(LLOBN_Table, [PromoteAllScalars=true]),
				
				    Columnas =
				        Table.TransformColumnNames(
				            Encabezados,
				            each Text.Replace(Text.Lower(_), " ", "_")
				        ),
				
				    Renombradas =
				        Table.RenameColumns(
				            Columnas,
				            {
				                {"data_instal·lació", "data_instalacion"},
				                {"estratègic", "estrategic"}
				            }
				        ),
				
				    Texto =
				        Table.TransformColumns(
				            Renombradas,
				            {
				                {"sector", Text.Proper, type text},
				                {"prioritat", Text.Proper, type text}
				            }
				        ),
				
				    Seleccionadas =
				        Table.SelectColumns(
				            Texto,
				            {
				                "dop",
				                "sector",
				                "rendiment_sector_(maig_2026)",
				                "polissa_subm",
				                "tipus_subm",
				                "data_instalacion",
				                "edat_comp",
				                "diam_comp",
				                "dn_limitador",
				                "data_alta_subm",
				                "consum_mig_dia",
				                "consum_anual_estimat",
				                "estrategic",
				                "prioritat",
				                "necessitat",
				                "v12_en_m3",
				                "periodos_consecutivos_con_ea"
				            }
				        ),
				
				    SinErrores =
				        Table.ReplaceErrorValues(
				            Seleccionadas,
				            List.Transform(Table.ColumnNames(Seleccionadas), each {_, null})
				        ),
				
				    Tipos =
				        Table.TransformColumnTypes(SinErrores,{{"rendiment_sector_(maig_2026)", type number}, {"polissa_subm", type text}, {"data_instalacion", type date}, {"edat_comp", Int64.Type}, {"diam_comp", Int64.Type}, {"data_alta_subm", type date}, {"consum_mig_dia", type number}, {"consum_anual_estimat", type number}, {"estrategic", type text}, {"necessitat", type text}, {"v12_en_m3", type number}, {"periodos_consecutivos_con_ea", Int64.Type}, {"dop", type text}}),
				
				    Limpieza =
				        Table.TransformColumns(
				            Tipos,
				            {
				                {
				                    "sector",
				                    each if _ = "" then null else _,
				                    type nullable text
				                },
				                {
				                    "rendiment_sector_(maig_2026)",
				                    each if _ = "" then null else _,
				                    type nullable number
				                },
				                {
				                    "dn_limitador",
				                    each if _ = "" or _ = "-" then null else _,
				                    type nullable text
				                }
				            }
				        ),
				
				    SinDuplicados =
				        Table.Distinct(Limpieza),
				
				    Resultado =
				        Table.SelectRows(
				            SinDuplicados,
				            each List.NonNullCount(Record.FieldValues(_)) > 0
				        )
				
				in
				    Resultado
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

