table dim_sector
	lineageTag: 2081387d-7f27-4ebf-b6af-dea129b732f3

	column sector_id
		dataType: int64
		formatString: 0
		lineageTag: aa19c239-2a2a-48b9-8c9f-ecd71233fbd8
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column sector
		dataType: string
		lineageTag: 627172a6-6fd0-4fb4-83cd-286bfea0ca82
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column gerencia
		dataType: string
		lineageTag: c93f018c-8aa6-46de-a468-20d6a3741f5e
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	partition dim_sector = m
		mode: import
		source =
				let
				  Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vRH4WiST8QUNFuYRZ1ilIw7p1mfJMiAz5bImbBz2ffnYgrxn2MyRB5O192pgqrP_SyFQdf6CJroUA9G/pub?gid=0&single=true&output=csv"), [Delimiter = ",", Columns = 3, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"sector_id", Int64.Type}, {"denomin", type text}, {"gerencia", type text}}, "es"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo de columna cambiado",{{"denomin", "sector"}})
				in
				  #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

