table dim_pozos
	lineageTag: 55100671-d749-4026-8fc4-d2c2fc4570db

	column Object_id
		dataType: string
		lineageTag: 6984b7de-9e3c-4bf3-986f-f1431ee39a30
		summarizeBy: none
		sourceColumn: Object_id

		annotation SummarizationSetBy = Automatic

	column sap_id
		dataType: int64
		formatString: 0
		lineageTag: 605bc99d-7966-43a9-a7f1-8995b1998ce6
		summarizeBy: sum
		sourceColumn: sap_id

		annotation SummarizationSetBy = Automatic

	column material
		dataType: string
		lineageTag: daa8fb83-520d-4bbd-9cd3-83a4d92f7905
		summarizeBy: none
		sourceColumn: material

		annotation SummarizationSetBy = Automatic

	column diametre_n
		dataType: int64
		formatString: 0
		lineageTag: 22ecf861-b472-4e2a-9774-c02478a3d2c2
		summarizeBy: sum
		sourceColumn: diametre_n

		annotation SummarizationSetBy = Automatic

	column gestio
		dataType: string
		lineageTag: 6376be36-a281-4e57-9507-89f81a09295b
		summarizeBy: none
		sourceColumn: gestio

		annotation SummarizationSetBy = Automatic

	column data_insta
		dataType: int64
		formatString: 0
		lineageTag: 909f0838-76f8-4019-9313-4f6cd39ed2b7
		summarizeBy: sum
		sourceColumn: data_insta

		annotation SummarizationSetBy = Automatic

	column mun
		dataType: string
		lineageTag: a24f4a3f-2bdf-452b-93f3-b9e1437e989b
		summarizeBy: none
		sourceColumn: mun

		annotation SummarizationSetBy = Automatic

	column tipus
		dataType: string
		lineageTag: bfcc9ef8-411f-430a-9d19-2d9c5c840cfa
		summarizeBy: none
		sourceColumn: tipus

		annotation SummarizationSetBy = Automatic

	column tram_sap_i
		dataType: string
		lineageTag: e7a6c2d9-3474-4287-bf05-d326357c605d
		summarizeBy: none
		sourceColumn: tram_sap_i

		annotation SummarizationSetBy = Automatic

	column afor_polis
		dataType: string
		lineageTag: 12674120-7af9-4a3d-bd7c-9cf1309d3213
		summarizeBy: none
		sourceColumn: afor_polis

		annotation SummarizationSetBy = Automatic

	column sector_id
		dataType: int64
		formatString: 0
		lineageTag: 561b76ae-8dcf-4b51-b907-eb8ea827acb2
		summarizeBy: sum
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column afor_pol_1
		dataType: string
		lineageTag: 94721997-9850-4caf-aa90-e99d6b1aad8d
		summarizeBy: none
		sourceColumn: afor_pol_1

		annotation SummarizationSetBy = Automatic

	column afor_us_ai
		dataType: int64
		formatString: 0
		lineageTag: 13fc93e9-1170-4148-b4b0-8588fa4ba0d0
		summarizeBy: sum
		sourceColumn: afor_us_ai

		annotation SummarizationSetBy = Automatic

	column afor_us_1
		dataType: string
		lineageTag: 5e02f52b-7dd4-4dcf-814c-3a92714d0e65
		summarizeBy: none
		sourceColumn: afor_us_1

		annotation SummarizationSetBy = Automatic

	column afor_situa
		dataType: string
		lineageTag: e8c20866-56b3-4a76-a5a3-40d4515c9ed8
		summarizeBy: none
		sourceColumn: afor_situa

		annotation SummarizationSetBy = Automatic

	column afor_tip_s
		dataType: string
		lineageTag: 95794954-7eb3-46f4-b2d4-acec8f735de2
		summarizeBy: none
		sourceColumn: afor_tip_s

		annotation SummarizationSetBy = Automatic

	column afor_tipus
		dataType: string
		lineageTag: 5ba5ef20-14a8-4822-ae10-aab036f0f7e3
		summarizeBy: none
		sourceColumn: afor_tipus

		annotation SummarizationSetBy = Automatic

	column afor_dotac
		dataType: int64
		formatString: 0
		lineageTag: 93b47a5f-2871-4096-b2e1-d619dd73e717
		summarizeBy: sum
		sourceColumn: afor_dotac

		annotation SummarizationSetBy = Automatic

	column afor_class
		dataType: string
		lineageTag: 7e9249f4-1958-4dd7-b164-057870527b62
		summarizeBy: none
		sourceColumn: afor_class

		annotation SummarizationSetBy = Automatic

	column afor_num_i
		dataType: int64
		formatString: 0
		lineageTag: ca508e17-fd93-4656-98bd-799da4a6cbf4
		summarizeBy: sum
		sourceColumn: afor_num_i

		annotation SummarizationSetBy = Automatic

	column afor_num_f
		dataType: int64
		formatString: 0
		lineageTag: b7628e22-26d4-416a-9660-22ed89d37486
		summarizeBy: sum
		sourceColumn: afor_num_f

		annotation SummarizationSetBy = Automatic

	column afor_sit_f
		dataType: int64
		formatString: 0
		lineageTag: 55a2a58d-0c94-46b9-9a23-117f82c60e1e
		summarizeBy: sum
		sourceColumn: afor_sit_f

		annotation SummarizationSetBy = Automatic

	column afor_nom_m
		dataType: string
		lineageTag: b69db1e2-343f-44d6-b892-e8075f78b710
		summarizeBy: none
		sourceColumn: afor_nom_m

		annotation SummarizationSetBy = Automatic

	partition dim_pozos = m
		mode: import
		queryGroup: Dimensiones
		source = ```
				let
				    // ORIGEN
				    Origen = GoogleSheets.Contents(Pozos),
				    Datos = Origen{[name = "Pous declarats a l'ACA", ItemKind = "Table"]}[Data],
				
				    Encabezados = Table.PromoteHeaders(
				        Datos,
				        [PromoteAllScalars = true]
				    ),
				
				    // RENOMBRAR COLUMNAS
				    Renombradas = Table.RenameColumns(
				        Encabezados,
				        {
				            {"OBJECTID", "Object_id"},
				            {"SAP_ID", "sap_id"},
				            {"MATERIAL", "material"},
				            {"DIAMETRE_N", "diametre_n"},
				            {"GESTIO", "gestio"},
				            {"DATA_INSTA", "data_insta"},
				            {"MUN", "mun"},
				            {"CARRER", "carrer"},
				            {"TIPUS", "tipus"},
				            {"TRAM_SAP_I", "tram_sap_i"},
				            {"Afor_POLIS", "afor_polis"},
				            {"Afor_SECTO", "sector_id"},
				            {"Afor_POL_1", "afor_pol_1"},
				            {"Afor_US_AI", "afor_us_ai"},
				            {"Afor_US__1", "afor_us_1"},
				            {"Afor_SITUA", "afor_situa"},
				            {"Afor_TIP_S", "afor_tip_s"},
				            {"Afor_TIPUS", "afor_tipus"},
				            {"Afor_DOTAC", "afor_dotac"},
				            {"Afor_CLASS", "afor_class"},
				            {"Afor_NOM_C", "afor_nom_c"},
				            {"Afor_NUM_I", "afor_num_i"},
				            {"Afor_NUM_F", "afor_num_f"},
				            {"Afor_COMP_", "afor_comp_"},
				            {"Afor_COM_1", "afor_com_1"},
				            {"Afor_SIT_F", "afor_sit_f"},
				            {"Afor_ORD_F", "afor_ord_f"},
				            {"Afor_OBS_A", "afor_obs_a"},
				            {"Afor_PIS_P", "afor_pis_p"},
				            {"Afor_NOM_M", "afor_nom_m"},
				            {"Afor_SECCI", "afor_secci"},
				            {"Afor_EPIGR", "afor_epigr"},
				            {"Afor_QL_SU", "afor_ql_su"}
				        },
				        MissingField.Ignore
				    ),
				
				    //  ELIMINAR COLUMNAS NO UTILIZADAS
				    ColumnasNecesarias = Table.RemoveColumns(
				        Renombradas,
				        {
				            "afor_nom_c",
				            "carrer",
				            "afor_obs_a",
				            "afor_secci",
				            "afor_epigr",
				            "afor_ql_su",
				            "afor_ord_f",
				            "afor_pis_p",
				            "afor_comp_",
				            "afor_com_1"
				        },
				        MissingField.Ignore
				    ),
				
				    
				    //  TIPOS
				    Tipos = Table.TransformColumnTypes(
				        ColumnasNecesarias,
				        {
				            {"Object_id", type text},
				            {"sap_id", Int64.Type},
				            {"material", type text},
				            {"diametre_n", Int64.Type},
				            {"gestio", type text},
				            {"data_insta", Int64.Type},
				            {"mun", type text},
				            {"tipus", type text},
				            {"tram_sap_i", type text},
				            {"afor_polis", type text},
				            {"sector_id", Int64.Type},
				            {"afor_pol_1", type text},
				            {"afor_us_ai", Int64.Type},
				            {"afor_us_1", type text},
				            {"afor_situa", type text},
				            {"afor_tip_s", type text},
				            {"afor_tipus", type text},
				            {"afor_dotac", Int64.Type},
				            {"afor_class", type text},
				            {"afor_num_i", Int64.Type},
				            {"afor_num_f", Int64.Type},
				            {"afor_sit_f", Int64.Type},
				            {"afor_nom_m", type text}
				        }
				    ),
				
				    
				    //NORMALIZACIÓN
				    NormalizarTexto = (
				        valor as nullable text,
				        proper as logical,
				        defecto as nullable text
				    ) as nullable text =>
				        let
				            Texto = 
				                if valor = null 
				                then null 
				                else Text.Trim(Text.Clean(valor)),
				
				            Resultado =
				                if Texto = null or Texto = "" then
				                    defecto
				                else if proper then
				                    Text.Proper(Texto)
				                else
				                    Texto
				        in
				            Resultado,
				
				 
				    //  NORMALIZAR TEXTOS
				    Textos = Table.TransformColumns(
				        Tipos,
				        {
				            // Proper + No Disponible
				            {"mun", each NormalizarTexto(_, true, "No Disponible"), type text},
				
				            // Solo limpiar
				            {"tipus", each NormalizarTexto(_, false, null), type text},
				
				            // Solo limpiar + No Disponible
				            {"afor_pol_1", each NormalizarTexto(_, false, "No Disponible"), type text},
				            {"afor_tipus", each NormalizarTexto(_, false, "No Disponible"), type text},
				
				            // Proper
				            {"afor_us_1", each NormalizarTexto(_, true, null), type text},
				            {"afor_situa", each NormalizarTexto(_, true, null), type text},
				            {"afor_nom_m", each NormalizarTexto(_, true, null), type text},
				
				            // Sí -> Si
				            {
				                "gestio",
				                each if _ = "Sí" then "Si" else _,
				                type text
				            }
				        }
				    ),
				
				    //  VALORES POR DEFECTO NUMÉRICOS
				    Valores = Table.TransformColumns(
				        Textos,
				        {
				            {"data_insta", each if _ = null then 2100 else _, Int64.Type},
				            {"afor_num_f", each if _ = null then 0 else _, Int64.Type},
				            {"sector_id", each if _ = null then -1 else _, Int64.Type}
				        }
				    ),
				
				    
				    //  ELIMINAR DUPLICADOS
				    Resultado = Table.Distinct(Valores)
				
				in
				    Resultado
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

