table dim_cabalimetros
	lineageTag: 5ee4f28e-060e-465f-94e7-27c3b294b828

	column id_cabalimetro
		dataType: string
		lineageTag: 9512935e-570d-48d1-9f71-bf752fc56490
		summarizeBy: none
		sourceColumn: id_cabalimetro

		annotation SummarizationSetBy = Automatic

	column tipus_equip
		dataType: string
		lineageTag: 35365366-366e-4b6d-a963-f4e5037a162f
		summarizeBy: none
		sourceColumn: tipus_equip

		annotation SummarizationSetBy = Automatic

	column fabricante
		dataType: string
		lineageTag: f45801fb-489c-419b-b405-d5c68fa28661
		summarizeBy: none
		sourceColumn: fabricante

		annotation SummarizationSetBy = Automatic

	column diametre_mm
		dataType: double
		lineageTag: 2b60ad77-aa5f-4806-9030-07c7e333775c
		summarizeBy: sum
		sourceColumn: diametre_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column data_instal
		dataType: dateTime
		formatString: Long Date
		lineageTag: ca1f3b23-34fd-4a8b-b351-4d0c59be9a65
		summarizeBy: none
		sourceColumn: data_instal

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column any_instal
		dataType: int64
		formatString: 0
		lineageTag: c89dd207-2559-4926-8504-f66d3d13cf27
		summarizeBy: sum
		sourceColumn: any_instal

		annotation SummarizationSetBy = Automatic

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: dec085fa-26b9-45f2-afd4-793e0e94f7bd
		summarizeBy: sum
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

	column cod_gerenciapc
		dataType: string
		lineageTag: 23da1b6c-2ca8-48f0-93b1-bf24926e44df
		summarizeBy: none
		sourceColumn: cod_gerenciapc

		annotation SummarizationSetBy = Automatic

	column tipus_regulac
		dataType: string
		lineageTag: 21130cee-505b-4434-93b9-d324e8d4c2ed
		summarizeBy: none
		sourceColumn: tipus_regulac

		annotation SummarizationSetBy = Automatic

	partition dim_cabalimetros = m
		mode: import
		queryGroup: Dimensiones
		source =
				let
				    Origen = GoogleSheets.Contents(Cabalimetros),
				    Datos = Origen{[name = "Cabalímetres", ItemKind = "Table"]}[Data],
				
				    Encabezados = Table.PromoteHeaders(
				        Datos,
				        [PromoteAllScalars = true]
				    ),
				
				    ColumnasRenombradas = Table.RenameColumns(
				        Encabezados,
				        {
				            {"", "gerencia"},
				            {"ID", "id"},
				            {"Gerència", "cod_gerenciapc"},
				            {"Tipus Equip", "tipus_equip"},
				            {"Fabricant", "fabricante"},
				            {"Diàmetre", "diametre_mm"},
				            {"Data Instal·lació", "data_instal"},
				            {"Any Instal·lació", "any_instal"}
				        }
				    ),
				
				    ColumnasNecesarias = Table.SelectColumns(
				        ColumnasRenombradas,
				        {
				            "gerencia",
				            "id",
				            "cod_gerenciapc",
				            "tipus_equip",
				            "fabricante",
				            "diametre_mm",
				            "data_instal",
				            "any_instal"
				        }
				    ),
				
				    Tipos = Table.TransformColumnTypes(
				        ColumnasNecesarias,
				        {
				            {"gerencia", type text},
				            {"id", type text},
				            {"cod_gerenciapc", type text},
				            {"tipus_equip", type text},
				            {"fabricante", type text},
				            {"diametre_mm", type text},
				            {"data_instal", type date},
				            {"any_instal", Int64.Type}
				        }
				    ),
				
				    TextosLimpios = Table.TransformColumns(
				        Tipos,
				        {
				            {
				                "gerencia",
				                each
				                    if _ = null then
				                        null
				                    else
				                        Text.Proper(
				                            Text.Clean(
				                                Text.Trim(
				                                    Text.From(_)
				                                )
				                            )
				                        ),
				                type text
				            },
				            {
				                "id",
				                each
				                    if _ = null then
				                        null
				                    else
				                        Text.Proper(
				                            Text.Trim(
				                                Text.From(_)
				                            )
				                        ),
				                type text
				            }
				        }
				    ),
				
				    Diametro = Table.TransformColumns(
				        TextosLimpios,
				        {
				            {
				                "diametre_mm",
				                each
				                    try
				                        Number.From(
				                            Text.BeforeDelimiter(
				                                Text.From(_),
				                                "mm"
				                            )
				                        )
				                    otherwise
				                        null,
				                type number
				            }
				        }
				    ),
				
				    FechaInstalacion = Table.ReplaceValue(
				        Diametro,
				        null,
				        #date(1899, 1, 1),
				        Replacer.ReplaceValue,
				        {"data_instal"}
				    ),
				
				    FabricanteNormalizado = Table.TransformColumns(
				        FechaInstalacion,
				        {
				            {
				                "fabricante",
				                each
				                    let
				                        f =
				                            if _ = null then
				                                ""
				                            else
				                                Text.Trim(Text.From(_)),
				                        fl = Text.Lower(f)
				                    in
				                        if f = "" then
				                            "No Disponible"
				                        else if
				                            Text.StartsWith(fl, "siemens")
				                            or fl = "siemmens"
				                            or fl = "sitrans"
				                        then
				                            "Siemens"
				                        else if
				                            fl = "waterflux"
				                            or fl = "krone"
				                            or fl = "krhone"
				                        then
				                            "Krohne"
				                        else if
				                            List.Contains(
				                                {
				                                    "endress & hauser",
				                                    "endress+hausen",
				                                    "endress hauser",
				                                    "endress+hauser"
				                                },
				                                fl
				                            )
				                        then
				                            "Endress + Hauser"
				                        else if
				                            Text.Contains(fl, "isomag")
				                            or Text.Contains(fl, "isoil")
				                        then
				                            "Isoil"
				                        else if fl = "xx" then
				                            "No Disponible"
				                        else
				                            Text.Proper(f),
				                type text
				            }
				        }
				    ),
				
				    GerenciaJoin = Table.NestedJoin(
				        FabricanteNormalizado,
				        {"gerencia"},
				        dim_gerencia,
				        {"gerencia"},
				        "dim_gerencia",
				        JoinKind.LeftOuter
				    ),
				
				    GerenciaExpandida = Table.ExpandTableColumn(
				        GerenciaJoin,
				        "dim_gerencia",
				        {"gerencia_id"},
				        {"gerencia_id"}
				    ),
				
				    GerenciaEliminada = Table.RemoveColumns(
				        GerenciaExpandida,
				        {"gerencia"}
				    ),
				
				    FilasOrdenadas = Table.Sort(
				        GerenciaEliminada,
				        {{"id", Order.Ascending}}
				    ),
				
				    CabalimetroClaval = Table.SelectRows(
				        FilasOrdenadas,
				        each [id] <> "Claval"
				    ),
				
				    RegulacionJoin = Table.NestedJoin(
				        CabalimetroClaval,
				        {"cod_gerenciapc"},
				        dim_aux_tipus_reg_cabali,
				        {"cod_gerenciapc"},
				        "dim_aux_tipus_reg_cabali",
				        JoinKind.LeftOuter
				    ),
				
				    RegulacionExpandida = Table.ExpandTableColumn(
				        RegulacionJoin,
				        "dim_aux_tipus_reg_cabali",
				        {"tipus_regulac"},
				        {"tipus_regulac"}
				    ),
				
				    RegulacionDefault = Table.ReplaceValue(
				        RegulacionExpandida,
				        null,
				        "Medidor",
				        Replacer.ReplaceValue,
				        {"tipus_regulac"}
				    ),
				
				    Resultado = Table.ReorderColumns(
				        RegulacionDefault,
				        {
				            "cod_gerenciapc",
				            "id",
				            "gerencia_id",
				            "tipus_equip",
				            "tipus_regulac",
				            "fabricante",
				            "diametre_mm",
				            "data_instal",
				            "any_instal"
				        }
				    ),
				
				    ResultadoFinal = Table.RenameColumns(
				        Resultado,
				        {
				            {"id", "id_cabalimetro"}
				        }
				    )
				
				in
				    ResultadoFinal

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

