table dim_comptadors
	lineageTag: a58ee88a-d4f9-42bb-97d5-9e175f6a5f67

	column Marca_Comp
		dataType: string
		lineageTag: 93704e7b-0a71-4f68-993e-4068c8956334
		summarizeBy: none
		sourceColumn: Marca_Comp

		annotation SummarizationSetBy = Automatic

	column Codi_Model
		dataType: string
		lineageTag: 257f5c05-9aa2-43dd-98a7-6def62c42755
		summarizeBy: none
		sourceColumn: Codi_Model

		annotation SummarizationSetBy = Automatic

	column Nom_Model
		dataType: string
		lineageTag: 7a325d13-c135-40a2-ba1d-1ef8ac17900c
		summarizeBy: none
		sourceColumn: Nom_Model

		annotation SummarizationSetBy = Automatic

	column Modcon_Ts
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4d22b3a3-306d-441e-a4ff-27968fc10c99
		summarizeBy: none
		sourceColumn: Modcon_Ts

		variation Variación
			isDefault
			relationship: 17fff1c4-214d-4c04-afec-b3881b74383d
			defaultHierarchy: LocalDateTable_2206ba03-04fd-4629-bbfa-8e406fa9fefd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Tipus_Comptador
		dataType: string
		lineageTag: 6d3adc33-4c32-4f4d-a6a9-56787330fad8
		summarizeBy: none
		sourceColumn: Tipus_Comptador

		annotation SummarizationSetBy = Automatic

	column Cabal_Q3
		dataType: double
		lineageTag: 99224aa7-b4e1-41d2-9bad-8c32f90b0cdc
		summarizeBy: sum
		sourceColumn: Cabal_Q3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ratio_Comp
		dataType: int64
		formatString: 0
		lineageTag: 7251393c-0055-45f4-a24b-ac909c01f5f5
		summarizeBy: sum
		sourceColumn: Ratio_Comp

		annotation SummarizationSetBy = Automatic

	column Data_Fi_Vigor
		dataType: dateTime
		formatString: Long Date
		lineageTag: e2a2e4a8-e784-4a42-96e3-2abf26388478
		summarizeBy: none
		sourceColumn: Data_Fi_Vigor

		variation Variación
			isDefault
			relationship: 634d3e43-725f-43ab-9acf-1c38ec2e9103
			defaultHierarchy: LocalDateTable_54d042b8-1683-49ee-a79d-9c2edf38ab53.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Id_marca_modelo
		dataType: string
		lineageTag: f11d8550-a0a4-4077-8b73-2bddec1f7127
		summarizeBy: none
		sourceColumn: Id_marca_modelo

		annotation SummarizationSetBy = Automatic

	partition dim_comptadors = m
		mode: import
		queryGroup: Dimensiones
		source =
				let
				  Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vRj_sXDOyb1nGGY_XqjyRddxHFAjQZIAdDBjiikNuahnlZjUzp4dQpHiBaOeutBdw/pub?gid=1830409052&single=true&output=csv"), [Delimiter = ",", Columns = 26, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				#"Encabezados promovidos" =
				        Table.PromoteHeaders(
				            Origen,
				            [PromoteAllScalars = true]
				        ),
				
				    #"Tipo de columna cambiado" =
				        Table.TransformColumnTypes(
				            #"Encabezados promovidos",
				            {
				                {"MARCA_COMP", type text},
				                {"CODI_MODEL", type text},
				                {"NOM_MODEL", type text},
				                {"QL_SISTEMA_MODEL", type text},
				                {"DES_SISTEMA_MODEL", type text},
				                {"LONGITUD_MODEL", Int64.Type},
				                {"ROSCA_ENT", type text},
				                {"ROSCA_SORT", type text},
				                {"MODCON_TS", type datetime},
				                {"NOMB_DIGI_COMP", Int64.Type},
				                {"NOMB_DIGI_COMP_SEC", Int64.Type},
				                {"TIPUS_COMPTADOR", type text},
				                {"SIT_MODEL_COMP", type text},
				                {"FORMAT_MODEL_C", type text},
				                {"CABAL_Q3", type number},
				                {"RATIO_COMP", Int64.Type},
				                {"SISTEMA_COM", type text},
				                {"CODI_MARCA_SPDE", type text},
				                {"CODI_MOD_SPDE", type text},
				                {"CODI_DIAM_SPDE", type text},
				                {"DATA_FI_VIGOR", type datetime},
				                {"QL_MODEL_DATAMART", type text},
				                {"IND_REAPROFITAR", type text},
				                {"PES_POLS", Int64.Type},
				                {"TECNO_EMISSIO", type text},
				                {"TOTALITZADOR", type text}
				            },
				            "es"
				        ),
				
				    #"Otras columnas quitadas" =
				        Table.SelectColumns(
				            #"Tipo de columna cambiado",
				            {
				                "MARCA_COMP",
				                "CODI_MODEL",
				                "NOM_MODEL",
				                "MODCON_TS",
				                "TIPUS_COMPTADOR",
				                "CABAL_Q3",
				                "RATIO_COMP",
				                "DATA_FI_VIGOR"
				            }
				        ),
				
				    #"Nombres en título" =
				        Table.TransformColumnNames(
				            #"Otras columnas quitadas",
				            each
				                Text.Combine(
				                    List.Transform(
				                        Text.Split(_, "_"),
				                        each Text.Proper(Text.Lower(_))
				                    ),
				                    "_"
				                )
				        ),
				
				    #"Tipo cambiado" =
				        Table.TransformColumnTypes(
				            #"Nombres en título",
				            {
				                {"Data_Fi_Vigor", type date},
				                {"Modcon_Ts", type date}
				            }
				        ),
				    #"Personalizada agregada" = Table.AddColumn(#"Tipo cambiado", "Id_marca_modelo", each [Marca_Comp] & "-" & Text.From([Codi_Model])),
				    #"Duplicados quitados" = Table.Distinct(#"Personalizada agregada", {"Id_marca_modelo"})
				in
				    #"Duplicados quitados"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

