table dim_cabalimetros
	lineageTag: aeac056c-8e6a-4a53-be40-50b699262639

	column cod_gerenciapc
		dataType: string
		lineageTag: c116364c-d03b-403b-8741-7dc431ea5f83
		summarizeBy: none
		sourceColumn: cod_gerenciapc

		annotation SummarizationSetBy = Automatic

	column id_cabalimetro
		dataType: string
		lineageTag: 731d516d-7af7-4f02-800a-27f73fe7d0c5
		summarizeBy: none
		sourceColumn: id_cabalimetro

		annotation SummarizationSetBy = Automatic

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: 68566ccc-2e27-403d-9ccb-a68043505658
		summarizeBy: sum
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

	column tipus_equip
		dataType: string
		lineageTag: 075c504a-29df-46e1-a619-573693b5daf6
		summarizeBy: none
		sourceColumn: tipus_equip

		annotation SummarizationSetBy = Automatic

	column tipus_regulac
		dataType: string
		lineageTag: 97062c19-43ca-41e8-9224-b84d9ce2a398
		summarizeBy: none
		sourceColumn: tipus_regulac

		annotation SummarizationSetBy = Automatic

	column fabricante
		dataType: string
		lineageTag: eb536bc9-35f6-4a1a-b51e-aef815cb65bc
		summarizeBy: none
		sourceColumn: fabricante

		annotation SummarizationSetBy = Automatic

	column diametre_mm
		dataType: double
		lineageTag: 56b66b12-2358-42a1-a529-ef924006b8fc
		summarizeBy: sum
		sourceColumn: diametre_mm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column data_instal
		dataType: dateTime
		formatString: Long Date
		lineageTag: 50dc2b7c-3310-461c-9062-c77fdffa9bd4
		summarizeBy: none
		sourceColumn: data_instal

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column any_instal
		dataType: int64
		formatString: 0
		lineageTag: 87d27b61-b12a-415d-836a-d3b226f4b9b6
		summarizeBy: sum
		sourceColumn: any_instal

		annotation SummarizationSetBy = Automatic

	partition dim_cabalimetros = m
		mode: import
		queryGroup: Dimensiones
		source = ```
				let
				    Origen = GoogleSheets.Contents(#"Inventari Punts de Control"),
				    Datos = Origen{[name = "Cabalímetres", ItemKind = "Table"]}[Data],
				 
				    Encabezados = Table.PromoteHeaders(
				        Datos,
				        [PromoteAllScalars = true]
				    ),
				 
				    ColumnasRenombradas = Table.RenameColumns(
				        Encabezados,
				        {
				            {"", "gerencia"},
				            {"ID", "id"},
				            {"Gerència", "cod_gerenciapc"},
				            {"Tipus Equip", "tipus_equip"},
				            {"Fabricant", "fabricante"},
				            {"Diàmetre", "diametre_mm"},
				            {"Data Instal·lació", "data_instal"},
				            {"Any Instal·lació", "any_instal"}
				        }
				    ),
				 
				    ColumnasNecesarias = Table.SelectColumns(
				        ColumnasRenombradas,
				        {
				            "gerencia",
				            "id",
				            "cod_gerenciapc",
				            "tipus_equip",
				            "fabricante",
				            "diametre_mm",
				            "data_instal",
				            "any_instal"
				        }
				    ),
				 
				    Tipos = Table.TransformColumnTypes(
				        ColumnasNecesarias,
				        {
				            {"gerencia", type text},
				            {"id", type text},
				            {"cod_gerenciapc", type text},
				            {"tipus_equip", type text},
				            {"fabricante", type text},
				            {"diametre_mm", type text},
				            {"data_instal", type date},
				            {"any_instal", Int64.Type}
				        }
				    ),
				 
				    TextosLimpios = Table.TransformColumns(
				        Tipos,
				        {
				            {
				                "gerencia",
				                each
				                    if _ = null then
				                        null
				                    else
				                        Text.Proper(
				                            Text.Clean(
				                                Text.Trim(
				                                    Text.From(_)
				                                )
				                            )
				                        ),
				                type text
				            },
				            {
				                "id",
				                each
				                    if _ = null then
				                        null
				                    else
				                        Text.Proper(
				                            Text.Trim(
				                                Text.From(_)
				                            )
				                        ),
				                type text
				            }
				        }
				    ),
				 
				    Diametro = Table.TransformColumns(
				        TextosLimpios,
				        {
				            {
				                "diametre_mm",
				                each
				                    try
				                        Number.From(
				                            Text.BeforeDelimiter(
				                                Text.From(_),
				                                "mm"
				                            )
				                        )
				                    otherwise
				                        null,
				                type number
				            }
				        }
				    ),
				 
				    FechaInstalacion = Table.ReplaceValue(
				        Diametro,
				        null,
				        #date(1899, 1, 1),
				        Replacer.ReplaceValue,
				        {"data_instal"}
				    ),
				 
				    FabricanteNormalizado = Table.TransformColumns(
				        FechaInstalacion,
				        {
				            {
				                "fabricante",
				                each
				                    let
				                        f =
				                            if _ = null then
				                                ""
				                            else
				                                Text.Trim(Text.From(_)),
				                        fl = Text.Lower(f)
				                    in
				                        if f = "" then
				                            "No Disponible"
				                        else if
				                            Text.StartsWith(fl, "siemens")
				                            or fl = "siemmens"
				                            or fl = "sitrans"
				                        then
				                            "Siemens"
				                        else if
				                            fl = "waterflux"
				                            or fl = "krone"
				                            or fl = "krhone"
				                        then
				                            "Krohne"
				                        else if
				                            List.Contains(
				                                {
				                                    "endress & hauser",
				                                    "endress+hausen",
				                                    "endress hauser",
				                                    "endress+hauser"
				                                },
				                                fl
				                            )
				                        then
				                            "Endress + Hauser"
				                        else if
				                            Text.Contains(fl, "isomag")
				                            or Text.Contains(fl, "isoil")
				                        then
				                            "Isoil"
				                        else if fl = "xx" then
				                            "No Disponible"
				                        else
				                            Text.Proper(f),
				                type text
				            }
				        }
				    ),
				 
				    GerenciaJoin = Table.NestedJoin(
				        FabricanteNormalizado,
				        {"gerencia"},
				        dim_gerencia,
				        {"gerencia"},
				        "dim_gerencia",
				        JoinKind.LeftOuter
				    ),
				 
				    GerenciaExpandida = Table.ExpandTableColumn(
				        GerenciaJoin,
				        "dim_gerencia",
				        {"gerencia_id"},
				        {"gerencia_id"}
				    ),
				 
				    GerenciaEliminada = Table.RemoveColumns(
				        GerenciaExpandida,
				        {"gerencia"}
				    ),
				 
				    FilasOrdenadas = Table.Sort(
				        GerenciaEliminada,
				        {{"id", Order.Ascending}}
				    ),
				 
				    CabalimetroClaval = Table.SelectRows(
				        FilasOrdenadas,
				        each [id] <> "Claval"
				    ),
				 
				    RegulacionJoin = Table.NestedJoin(
				        CabalimetroClaval,
				        {"cod_gerenciapc"},
				        dim_aux_tipus_reg_cabali,
				        {"cod_gerenciapc"},
				        "dim_aux_tipus_reg_cabali",
				        JoinKind.LeftOuter
				    ),
				 
				    RegulacionExpandida = Table.ExpandTableColumn(
				        RegulacionJoin,
				        "dim_aux_tipus_reg_cabali",
				        {"tipus_regulac"},
				        {"tipus_regulac"}
				    ),
				 
				    RegulacionDefault = Table.ReplaceValue(
				        RegulacionExpandida,
				        null,
				        "Medidor",
				        Replacer.ReplaceValue,
				        {"tipus_regulac"}
				    ),
				 
				    Resultado = Table.ReorderColumns(
				        RegulacionDefault,
				        {
				            "cod_gerenciapc",
				            "id",
				            "gerencia_id",
				            "tipus_equip",
				            "tipus_regulac",
				            "fabricante",
				            "diametre_mm",
				            "data_instal",
				            "any_instal"
				        }
				    ),
				 
				    ResultadoFinal = Table.RenameColumns(
				        Resultado,
				        {
				            {"id", "id_cabalimetro"}
				        }
				    )
				 
				in
				    ResultadoFinal
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

