table dim_art_bcn_g_pressio_130BAR
	lineageTag: 4d280462-d6d2-41c8-bea8-e0fb8ef4c4da

	column nº_de_nudo
		dataType: string
		lineageTag: 0849b6a5-2582-40bd-9b32-f0e1551086fb
		summarizeBy: none
		sourceColumn: nº_de_nudo

		annotation SummarizationSetBy = Automatic

	column z(m)
		dataType: double
		lineageTag: 180a80be-6282-4898-831d-9b0f72d61a8b
		summarizeBy: none
		sourceColumn: z(m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column profundidad(m)
		dataType: double
		lineageTag: b7774d31-91ba-4b37-86b7-959d6a4a32e8
		summarizeBy: none
		sourceColumn: profundidad(m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column zona_2
		dataType: double
		lineageTag: f7a86c1d-d5e4-4b1f-bc28-ccf292a1202b
		summarizeBy: none
		sourceColumn: zona_2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nombre
		dataType: string
		lineageTag: 4519b076-70ad-4020-8925-7fa3c95c4d80
		summarizeBy: none
		sourceColumn: nombre

		annotation SummarizationSetBy = Automatic

	column pz_nit
		dataType: double
		lineageTag: d9dedfaa-1dc1-468f-b404-45fa6094f446
		summarizeBy: none
		sourceColumn: pz_nit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pzedifici
		dataType: double
		lineageTag: 87d288d5-e321-43a3-990f-49ddf50b8c8d
		summarizeBy: none
		sourceColumn: pzedifici

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pteorica
		dataType: double
		lineageTag: fbd6dca7-25b5-4274-a708-e33517077953
		summarizeBy: none
		sourceColumn: pteorica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preal
		dataType: double
		lineageTag: d0ef232b-b3e4-4b82-bf27-1d91627c23d0
		summarizeBy: none
		sourceColumn: preal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grup_pressio_nit
		dataType: double
		lineageTag: 9b7cbcf7-2a0d-4215-a3f5-61a184a57d09
		summarizeBy: none
		sourceColumn: grup_pressio_nit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column te_nit
		dataType: string
		lineageTag: e939cd3b-aab9-4e80-8140-8bb52b6410f5
		summarizeBy: none
		sourceColumn: te_nit

		annotation SummarizationSetBy = Automatic

	column pz_dia
		dataType: double
		lineageTag: 7cbb4100-6cc5-40aa-b782-c25ec76b6c57
		summarizeBy: none
		sourceColumn: pz_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preal_3
		dataType: double
		lineageTag: 87bbdf85-4118-4ff8-9893-96b0222bd03e
		summarizeBy: none
		sourceColumn: preal_3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grup_pressio_dia
		dataType: double
		lineageTag: f6b79a81-ccd3-44e7-ae3c-bbcf352e10c8
		summarizeBy: none
		sourceColumn: grup_pressio_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column te_dia
		dataType: string
		lineageTag: 55249687-3aca-472f-9fd9-ea892b5c5867
		summarizeBy: none
		sourceColumn: te_dia

		annotation SummarizationSetBy = Automatic

	partition dim_art_bcn_g_pressio_130BAR = m
		mode: import
		source = ```
				let
				    Origen = GoogleSheets.Contents(#"BCN G Pressio"),
				    #"130BAR_Table" = Origen{[name="070FLL",ItemKind="Table"]}[Data],
				     #"Encabezados promovidos" = Table.PromoteHeaders(#"130BAR_Table", [PromoteAllScalars=true]),
				     // 2. Limpieza de nombres de columna (minúsculas, sin acentos y con _)
				    EncabezadosLimpios = Table.TransformColumnNames(#"Encabezados promovidos", each 
				        let
				            sinSaltos = Text.Replace(Text.Replace(_, "#(lf)", " "), "#(cr)", " "),
				            textoBase = Text.Replace(Text.Lower(Text.Trim(sinSaltos)), " ", "_"),
				            reemplazos = {
				                {"á","a"}, {"é","e"}, {"í","i"}, {"ó","o"}, {"ú","u"}, 
				                {"à","a"}, {"è","e"}, {"ò","o"}, 
				                {"ï","i"}, {"ü","u"}
				            },
				            textoLimpio = List.Accumulate(reemplazos, textoBase, (estado, actual) => Text.Replace(estado, actual{0}, actual{1}))
				        in
				            textoLimpio
				    ),
				    #"Columnas quitadas" = Table.RemoveColumns(EncabezadosLimpios,{"sector", "20-130", "pzedifici_1", "pteorica_2", "20-130_4"}),
				
				
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas quitadas",{{"zeta", type number}, {"profunditats", type number}, {"zona_2", type number}, {"pz_nit", type number}, {"pzedifici", type number}, {"pteorica", type number}, {"preal", type number}, {"grup_pressio", type number}, {"te_?", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"te_?", "te_nit"}, {"te_?_6", "te_dia"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","","No Disponible",Replacer.ReplaceValue,{"te_nit", "te_dia"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado",{{"pz_dia", type number}, {"preal_3", type number}, {"grup_pressio_5", type number}}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Tipo cambiado1",{{"iden", "nº_de_nudo"}, {"zeta", "z(m)"}, {"profunditats", "profundidad(m)"}, {"grup_pressio", "grup_pressio_nit"}, {"grup_pressio_5", "grup_pressio_dia"}})
				in
				    #"Columnas con nombre cambiado1"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

