table dim_art_bcn_g_pressio_100BLL
	lineageTag: 85572fb0-3fad-4259-92f3-68d0fd0b4b7b

	column nº_de_nudo
		dataType: string
		lineageTag: 082e49c3-37cb-450f-a4b2-8e22b429a7dd
		summarizeBy: none
		sourceColumn: nº_de_nudo

		annotation SummarizationSetBy = Automatic

	column z(m)
		dataType: double
		lineageTag: f7ead623-6623-462d-920f-ed6833d23d70
		summarizeBy: sum
		sourceColumn: z(m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column profundidad(m)
		dataType: double
		lineageTag: 53005232-7734-4488-a58d-703457be602d
		summarizeBy: sum
		sourceColumn: profundidad(m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column zona_2
		dataType: double
		lineageTag: 9ffd2e59-baee-4783-81fb-9504f14c642e
		summarizeBy: sum
		sourceColumn: zona_2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nombre
		dataType: string
		lineageTag: 84495c4c-d6e8-43c9-a1d4-aad3bf569caf
		summarizeBy: none
		sourceColumn: nombre

		annotation SummarizationSetBy = Automatic

	column pz_nit
		dataType: double
		lineageTag: 4fa8c8f3-9ff6-4d4a-ba8d-94f8800f730f
		summarizeBy: sum
		sourceColumn: pz_nit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pzedifici
		dataType: double
		lineageTag: 991c80fe-2023-4283-831b-7dc71207742c
		summarizeBy: sum
		sourceColumn: pzedifici

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pteorica
		dataType: double
		lineageTag: b3d54cbc-d8c1-4463-8c28-5c578cb34529
		summarizeBy: sum
		sourceColumn: pteorica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preal
		dataType: double
		lineageTag: dceb3565-bcf2-4ca8-a753-5175f36484ba
		summarizeBy: sum
		sourceColumn: preal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grup_pressio_nit
		dataType: double
		lineageTag: 8da50476-8ccf-4757-b0e8-a832af17b513
		summarizeBy: sum
		sourceColumn: grup_pressio_nit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column te_nit
		dataType: string
		lineageTag: 8a23652f-51c4-4caa-bc1c-571f558ed99d
		summarizeBy: none
		sourceColumn: te_nit

		annotation SummarizationSetBy = Automatic

	column pz_dia
		dataType: double
		lineageTag: 5fafbc19-d6c3-4299-bd09-92c8865b740f
		summarizeBy: sum
		sourceColumn: pz_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preal_3
		dataType: double
		lineageTag: 87f6a28c-2ac5-4002-8485-38ee3e515456
		summarizeBy: sum
		sourceColumn: preal_3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grup_pressio_dia
		dataType: double
		lineageTag: f1a4bc64-4125-4131-a65d-1d1f9ca40625
		summarizeBy: sum
		sourceColumn: grup_pressio_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column te_dia
		dataType: string
		lineageTag: 884db2f7-91f9-4dae-8f3f-920ca4659e57
		summarizeBy: none
		sourceColumn: te_dia

		annotation SummarizationSetBy = Automatic

	partition dim_art_bcn_g_pressio_100BLL = m
		mode: import
		source = ```
				let
				    Origen = GoogleSheets.Contents(#"BCN G Pressio"),
				    #"100BLL_Table" = Origen{[name="100BLL",ItemKind="Table"]}[Data],
				     #"Encabezados promovidos" = Table.PromoteHeaders(#"100BLL_Table", [PromoteAllScalars=true]),
				     // 2. Limpieza de nombres de columna (minúsculas, sin acentos y con _)
				    EncabezadosLimpios = Table.TransformColumnNames(#"Encabezados promovidos", each 
				        let
				            sinSaltos = Text.Replace(Text.Replace(_, "#(lf)", " "), "#(cr)", " "),
				            textoBase = Text.Replace(Text.Lower(Text.Trim(sinSaltos)), " ", "_"),
				            reemplazos = {
				                {"á","a"}, {"é","e"}, {"í","i"}, {"ó","o"}, {"ú","u"}, 
				                {"à","a"}, {"è","e"}, {"ò","o"}, 
				                {"ï","i"}, {"ü","u"}
				            },
				            textoLimpio = List.Accumulate(reemplazos, textoBase, (estado, actual) => Text.Replace(estado, actual{0}, actual{1}))
				        in
				            textoLimpio
				    ),
				    #"Columnas quitadas" = Table.RemoveColumns(EncabezadosLimpios,{"zona", "20-130", "pzedifici_1", "pteorica_2", "20-130_4"}),
				
				
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas quitadas",{{"z(m)", type number}, {"profundidad(m)", type number}, {"zona_2", type number}, {"pz_nit", type number}, {"pzedifici", type number}, {"pteorica", type number}, {"preal", type number}, {"grup_pressio", type number}, {"te_?", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"te_?", "te_nit"}, {"te_?_6", "te_dia"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","","No Disponible",Replacer.ReplaceValue,{"te_nit", "te_dia"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado",{{"pz_dia", type number}, {"preal_3", type number}, {"grup_pressio_5", type number}}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Tipo cambiado1",{{"grup_pressio", "grup_pressio_nit"}, {"grup_pressio_5", "grup_pressio_dia"}})
				in
				    #"Columnas con nombre cambiado1"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Exception

