table dim_art_bcn_g_pressio_070BBE
	lineageTag: 9f0036c6-1e05-44c2-92c2-a5b95451a0ba

	column nº_de_nudo
		dataType: string
		lineageTag: a567b095-6a2d-48cf-b29a-8c5afc2ea54e
		summarizeBy: none
		sourceColumn: nº_de_nudo

		annotation SummarizationSetBy = Automatic

	column z(m)
		dataType: double
		lineageTag: 9aa85b8b-c92f-45f0-8186-1e4ba86cddd6
		summarizeBy: sum
		sourceColumn: z(m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column profundidad(m)
		dataType: double
		lineageTag: f98b7d0c-7aed-4dc9-b7d7-f84ddfb49c44
		summarizeBy: sum
		sourceColumn: profundidad(m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column zona_2
		dataType: double
		lineageTag: 71a4e695-7821-4920-9748-09b937a3d284
		summarizeBy: sum
		sourceColumn: zona_2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nombre
		dataType: string
		lineageTag: a508115b-c65d-4ac8-b6a9-badaf757dc6b
		summarizeBy: none
		sourceColumn: nombre

		annotation SummarizationSetBy = Automatic

	column pz_nit
		dataType: double
		lineageTag: 8c19094a-3090-4eb9-b2ef-dde2a598d9c4
		summarizeBy: sum
		sourceColumn: pz_nit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pzedifici
		dataType: double
		lineageTag: a5011e55-1fb5-4307-8754-4c4f82369673
		summarizeBy: sum
		sourceColumn: pzedifici

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pteorica
		dataType: double
		lineageTag: fddb6678-377e-47b5-a751-8f71fc970c5b
		summarizeBy: sum
		sourceColumn: pteorica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preal
		dataType: double
		lineageTag: c34d5e16-61da-4513-8886-a5abaca20996
		summarizeBy: sum
		sourceColumn: preal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grup_pressio_nit
		dataType: double
		lineageTag: 3eb0d940-926a-49f1-beb4-02ec25defb27
		summarizeBy: sum
		sourceColumn: grup_pressio_nit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column te_nit
		dataType: string
		lineageTag: 6da24f83-0699-4aa3-b2b0-6310188ee1d1
		summarizeBy: none
		sourceColumn: te_nit

		annotation SummarizationSetBy = Automatic

	column pz_dia
		dataType: double
		lineageTag: 28439d96-220f-418c-b204-19c5598d5bc9
		summarizeBy: sum
		sourceColumn: pz_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preal_3
		dataType: double
		lineageTag: 7211471a-61d3-4315-b7bd-f104ba16d98a
		summarizeBy: sum
		sourceColumn: preal_3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grup_pressio_dia
		dataType: double
		lineageTag: b7b789c3-39f9-4451-a530-9ace14d81cb7
		summarizeBy: sum
		sourceColumn: grup_pressio_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column te_dia
		dataType: string
		lineageTag: ccd61a46-6a21-42fb-94ed-807c29f417b2
		summarizeBy: none
		sourceColumn: te_dia

		annotation SummarizationSetBy = Automatic

	partition dim_art_bcn_g_pressio_070BBE = m
		mode: import
		source = ```
				let
				    Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NknnQkvQTlpWVaHLJML1QFtsnHEDRmkFK71aCEnrR5Q/edit?gid=231282145#gid=231282145"),
				    #"070BBE_Table" = Origen{[name="070BBE",ItemKind="Table"]}[Data],
				     #"Encabezados promovidos" = Table.PromoteHeaders(#"070BBE_Table", [PromoteAllScalars=true]),
				     // 2. Limpieza de nombres de columna (minúsculas, sin acentos y con _)
				    EncabezadosLimpios = Table.TransformColumnNames(#"Encabezados promovidos", each 
				        let
				            sinSaltos = Text.Replace(Text.Replace(_, "#(lf)", " "), "#(cr)", " "),
				            textoBase = Text.Replace(Text.Lower(Text.Trim(sinSaltos)), " ", "_"),
				            reemplazos = {
				                {"á","a"}, {"é","e"}, {"í","i"}, {"ó","o"}, {"ú","u"}, 
				                {"à","a"}, {"è","e"}, {"ò","o"}, 
				                {"ï","i"}, {"ü","u"}
				            },
				            textoLimpio = List.Accumulate(reemplazos, textoBase, (estado, actual) => Text.Replace(estado, actual{0}, actual{1}))
				        in
				            textoLimpio
				    ),
				    #"Columnas quitadas" = Table.RemoveColumns(EncabezadosLimpios,{"zona", "20-130", "pzedifici_1", "pteorica_2", "20-130_4"}),
				
				
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas quitadas",{{"z(m)", type number}, {"profundidad(m)", type number}, {"zona_2", type number}, {"pz_nit", type number}, {"pzedifici", type number}, {"pteorica", type number}, {"preal", type number}, {"grup_pressio", type number}, {"te_?", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"te_?", "te_nit"}, {"te_?_6", "te_dia"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","","No Disponible",Replacer.ReplaceValue,{"te_nit", "te_dia"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado",{{"pz_dia", type number}, {"preal_3", type number}, {"grup_pressio_5", type number}}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Tipo cambiado1",{{"grup_pressio", "grup_pressio_nit"}, {"grup_pressio_5", "grup_pressio_dia"}})
				in
				    #"Columnas con nombre cambiado1"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

