table dim_art_bcn_g_pressio_055BAR
	lineageTag: 39457fdc-14a6-4805-9651-f93977303882

	column nº_de_nudo
		dataType: string
		lineageTag: 01134d42-152f-4fca-8403-dafb8fd8ce52
		summarizeBy: none
		sourceColumn: nº_de_nudo

		annotation SummarizationSetBy = Automatic

	column z(m)
		dataType: double
		lineageTag: c96b4af7-5567-4cfa-8ce0-ed60c8ee5287
		summarizeBy: sum
		sourceColumn: z(m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column profundidad(m)
		dataType: double
		lineageTag: 3242977e-5119-481a-8411-3baf1a353d00
		summarizeBy: sum
		sourceColumn: profundidad(m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column zona_2
		dataType: double
		lineageTag: 9c7d4f75-84c0-4d8f-ae29-9e82e15d04bc
		summarizeBy: sum
		sourceColumn: zona_2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nombre
		dataType: string
		lineageTag: a673cf11-9577-4c67-b9e1-842152f795c9
		summarizeBy: none
		sourceColumn: nombre

		annotation SummarizationSetBy = Automatic

	column pz_nit
		dataType: double
		lineageTag: e7366e6a-6ab1-48dd-a093-e7b292e2d85e
		summarizeBy: sum
		sourceColumn: pz_nit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pzedifici
		dataType: double
		lineageTag: 087825f7-49d4-4f3e-8333-c77572d8f6b3
		summarizeBy: sum
		sourceColumn: pzedifici

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pteorica
		dataType: double
		lineageTag: 89ece3b6-8223-4c3f-a25c-3c5f127d558f
		summarizeBy: sum
		sourceColumn: pteorica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preal
		dataType: double
		lineageTag: e8b29f21-c915-443e-8105-16b29fde8674
		summarizeBy: sum
		sourceColumn: preal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grup_pressio_nit
		dataType: double
		lineageTag: d2edb963-5a0e-4eb4-890b-c20bca009355
		summarizeBy: sum
		sourceColumn: grup_pressio_nit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column te_nit
		dataType: string
		lineageTag: ee6eb689-4584-495e-b6b1-c7212e219516
		summarizeBy: none
		sourceColumn: te_nit

		annotation SummarizationSetBy = Automatic

	column pz_dia
		dataType: double
		lineageTag: cadca3ed-62d1-48e2-bd63-a9ef8528016a
		summarizeBy: sum
		sourceColumn: pz_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preal_3
		dataType: double
		lineageTag: 674e93f4-f3e9-4e51-a6fe-2b532858b200
		summarizeBy: sum
		sourceColumn: preal_3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grup_pressio_dia
		dataType: double
		lineageTag: 1d763ccc-f57b-48ab-b791-b395d1cfef70
		summarizeBy: sum
		sourceColumn: grup_pressio_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column te_dia
		dataType: string
		lineageTag: bc568fb2-3501-4ed3-b8b9-4b493d9d1ac2
		summarizeBy: none
		sourceColumn: te_dia

		annotation SummarizationSetBy = Automatic

	partition dim_art_bcn_g_pressio_055BAR = m
		mode: import
		queryGroup: Dimensiones\dim_art_bcn_g_pressio
		source = ```
				let
				    Origen = GoogleSheets.Contents(#"BCN G Pressio"),
				    #"055BAR_Table" = Origen{[name="055BAR",ItemKind="Table"]}[Data],
				     #"Encabezados promovidos" = Table.PromoteHeaders(#"055BAR_Table", [PromoteAllScalars=true]),
				     // 2. Limpieza de nombres de columna (minúsculas, sin acentos y con _)
				    EncabezadosLimpios = Table.TransformColumnNames(#"Encabezados promovidos", each 
				        let
				            sinSaltos = Text.Replace(Text.Replace(_, "#(lf)", " "), "#(cr)", " "),
				            textoBase = Text.Replace(Text.Lower(Text.Trim(sinSaltos)), " ", "_"),
				            reemplazos = {
				                {"á","a"}, {"é","e"}, {"í","i"}, {"ó","o"}, {"ú","u"}, 
				                {"à","a"}, {"è","e"}, {"ò","o"}, 
				                {"ï","i"}, {"ü","u"}
				            },
				            textoLimpio = List.Accumulate(reemplazos, textoBase, (estado, actual) => Text.Replace(estado, actual{0}, actual{1}))
				        in
				            textoLimpio
				    ),
				    #"Columnas quitadas" = Table.RemoveColumns(EncabezadosLimpios,{ "20-130", "pzedifici_1", "pteorica_2", "20-130_4"}),
				
				
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas quitadas",{{"zeta", type number}, {"profunditats", type number}, {"nombre", type text}, {"pz_nit", type number}, {"pzedifici", type number}, {"pteorica", type number}, {"preal", type number}, {"grup_pressio", type number}, {"te_?", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"te_?", "te_nit"}, {"te_?_6", "te_dia"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","","No Disponible",Replacer.ReplaceValue,{"te_nit", "te_dia"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado",{{"pz_dia", type number}, {"preal_3", type number}, {"grup_pressio_5", type number}}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Tipo cambiado1",{{"iden", "nº_de_nudo"}, {"zeta", "z(m)"}, {"profunditats", "profundidad(m)"}, {"sector", "zona_2"}, {"grup_pressio_5", "grup_pressio_dia"}, {"grup_pressio", "grup_pressio_nit"}}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"zona_2", type number}})
				in
				    #"Tipo cambiado2"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

