table dim_pozos
	lineageTag: fc48ed61-febc-4dba-b251-d810c4ca3597

	column Object_id
		dataType: string
		lineageTag: 3ec5e4cd-5557-4c49-bd26-e12ce30fe427
		summarizeBy: none
		sourceColumn: Object_id

		annotation SummarizationSetBy = Automatic

	column sap_id
		dataType: int64
		formatString: 0
		lineageTag: 9225e483-95d9-4c53-9e73-832270bf28d4
		summarizeBy: sum
		sourceColumn: sap_id

		annotation SummarizationSetBy = Automatic

	column material
		dataType: string
		lineageTag: 711a14af-4339-4e9b-87db-794318e14a37
		summarizeBy: none
		sourceColumn: material

		annotation SummarizationSetBy = Automatic

	column diametre_n
		dataType: int64
		formatString: 0
		lineageTag: 5d3b322d-c9ed-4a80-8d0d-13cdeffa7f1b
		summarizeBy: sum
		sourceColumn: diametre_n

		annotation SummarizationSetBy = Automatic

	column gestio
		dataType: string
		lineageTag: 1dad925e-d89c-4ff1-b8f7-c9355fa2adcc
		summarizeBy: none
		sourceColumn: gestio

		annotation SummarizationSetBy = Automatic

	column data_insta
		dataType: int64
		formatString: 0
		lineageTag: b317c3fe-9fa5-4b6a-92ed-22e9c447550d
		summarizeBy: sum
		sourceColumn: data_insta

		annotation SummarizationSetBy = Automatic

	column mun
		dataType: string
		lineageTag: d656397e-5903-4c00-9b4b-384f4058a2c8
		summarizeBy: none
		sourceColumn: mun

		annotation SummarizationSetBy = Automatic

	column tipus
		dataType: string
		lineageTag: aff74742-5764-42d7-8096-1f78a93725db
		summarizeBy: none
		sourceColumn: tipus

		annotation SummarizationSetBy = Automatic

	column tram_sap_i
		dataType: string
		lineageTag: e48cdbb7-d17b-4809-811a-37e964ee8e25
		summarizeBy: none
		sourceColumn: tram_sap_i

		annotation SummarizationSetBy = Automatic

	column afor_polis
		dataType: string
		lineageTag: 769debf2-4b1e-4ffc-a025-5faf9d016256
		summarizeBy: none
		sourceColumn: afor_polis

		annotation SummarizationSetBy = Automatic

	column sector_id
		dataType: int64
		formatString: 0
		lineageTag: ac47ea88-e12e-40d3-b587-efda890075fe
		summarizeBy: sum
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column afor_pol_1
		dataType: string
		lineageTag: cd455272-dfdc-401c-8f4e-ca4e59bef93f
		summarizeBy: none
		sourceColumn: afor_pol_1

		annotation SummarizationSetBy = Automatic

	column afor_us_ai
		dataType: int64
		formatString: 0
		lineageTag: 2ed3aa10-20f6-4af0-ab3a-107dc3d4c23f
		summarizeBy: sum
		sourceColumn: afor_us_ai

		annotation SummarizationSetBy = Automatic

	column afor_us_1
		dataType: string
		lineageTag: a95e9361-d5a2-465d-bc0d-6b28b3334793
		summarizeBy: none
		sourceColumn: afor_us_1

		annotation SummarizationSetBy = Automatic

	column afor_situa
		dataType: string
		lineageTag: efde30dd-bec7-425c-a1b8-09a073c9e2d2
		summarizeBy: none
		sourceColumn: afor_situa

		annotation SummarizationSetBy = Automatic

	column afor_tip_s
		dataType: string
		lineageTag: a671b91f-e237-4934-9aae-292d049f3db6
		summarizeBy: none
		sourceColumn: afor_tip_s

		annotation SummarizationSetBy = Automatic

	column afor_tipus
		dataType: string
		lineageTag: 0b06b9a7-39d9-496c-aed2-22958d1de8f8
		summarizeBy: none
		sourceColumn: afor_tipus

		annotation SummarizationSetBy = Automatic

	column afor_dotac
		dataType: int64
		formatString: 0
		lineageTag: 227c22a2-15a6-4ed6-ae1f-63b528bed2cf
		summarizeBy: sum
		sourceColumn: afor_dotac

		annotation SummarizationSetBy = Automatic

	column afor_class
		dataType: string
		lineageTag: d4a2f101-0563-4d4e-94ac-89db33c6673d
		summarizeBy: none
		sourceColumn: afor_class

		annotation SummarizationSetBy = Automatic

	column afor_num_i
		dataType: int64
		formatString: 0
		lineageTag: d58cc09d-9227-423e-9b47-01db8bab6cdc
		summarizeBy: sum
		sourceColumn: afor_num_i

		annotation SummarizationSetBy = Automatic

	column afor_num_f
		dataType: int64
		formatString: 0
		lineageTag: 217c0d2e-9940-4cb0-bf35-99fbea8eea31
		summarizeBy: sum
		sourceColumn: afor_num_f

		annotation SummarizationSetBy = Automatic

	column afor_sit_f
		dataType: int64
		formatString: 0
		lineageTag: 13cee110-f4d7-47ed-a3c7-2abca1098706
		summarizeBy: sum
		sourceColumn: afor_sit_f

		annotation SummarizationSetBy = Automatic

	column afor_nom_m
		dataType: string
		lineageTag: f1865336-3946-47bd-b71e-89bc16c5265b
		summarizeBy: none
		sourceColumn: afor_nom_m

		annotation SummarizationSetBy = Automatic

	partition dim_pozos = m
		mode: import
		queryGroup: Dimensiones
		source = ```
				let
				    // ORIGEN
				    Origen = GoogleSheets.Contents(Pozos),
				    Datos = Origen{[name = "Pous declarats a l'ACA", ItemKind = "Table"]}[Data], 
				    Encabezados = Table.PromoteHeaders(        Datos,        [PromoteAllScalars = true]    ),
				 
				    // RENOMBRAR COLUMNAS
				
				    Renombradas = Table.RenameColumns(
				
				        Encabezados,
				
				        {
				
				            {"OBJECTID", "Object_id"},
				
				            {"SAP_ID", "sap_id"},
				
				            {"MATERIAL", "material"},
				
				            {"DIAMETRE_N", "diametre_n"},
				
				            {"GESTIO", "gestio"},
				
				            {"DATA_INSTA", "data_insta"},
				
				            {"MUN", "mun"},
				
				            {"CARRER", "carrer"},
				
				            {"TIPUS", "tipus"},
				
				            {"TRAM_SAP_I", "tram_sap_i"},
				
				            {"Afor_POLIS", "afor_polis"},
				
				            {"Afor_SECTO", "sector_id"},
				
				            {"Afor_POL_1", "afor_pol_1"},
				
				            {"Afor_US_AI", "afor_us_ai"},
				
				            {"Afor_US__1", "afor_us_1"},
				
				            {"Afor_SITUA", "afor_situa"},
				
				            {"Afor_TIP_S", "afor_tip_s"},
				
				            {"Afor_TIPUS", "afor_tipus"},
				
				            {"Afor_DOTAC", "afor_dotac"},
				
				            {"Afor_CLASS", "afor_class"},
				
				            {"Afor_NOM_C", "afor_nom_c"},
				
				            {"Afor_NUM_I", "afor_num_i"},
				
				            {"Afor_NUM_F", "afor_num_f"},
				
				            {"Afor_COMP_", "afor_comp_"},
				
				            {"Afor_COM_1", "afor_com_1"},
				
				            {"Afor_SIT_F", "afor_sit_f"},
				
				            {"Afor_ORD_F", "afor_ord_f"},
				
				            {"Afor_OBS_A", "afor_obs_a"},
				
				            {"Afor_PIS_P", "afor_pis_p"},
				
				            {"Afor_NOM_M", "afor_nom_m"},
				
				            {"Afor_SECCI", "afor_secci"},
				
				            {"Afor_EPIGR", "afor_epigr"},
				
				            {"Afor_QL_SU", "afor_ql_su"}
				
				        },
				
				        MissingField.Ignore
				
				    ),
				 
				    //  ELIMINAR COLUMNAS NO UTILIZADAS
				
				    ColumnasNecesarias = Table.RemoveColumns(
				
				        Renombradas,
				
				        {
				
				            "afor_nom_c",
				
				            "carrer",
				
				            "afor_obs_a",
				
				            "afor_secci",
				
				            "afor_epigr",
				
				            "afor_ql_su",
				
				            "afor_ord_f",
				
				            "afor_pis_p",
				
				            "afor_comp_",
				
				            "afor_com_1"
				
				        },
				
				        MissingField.Ignore
				
				    ),
				 
				    
				
				    //  TIPOS
				
				    Tipos = Table.TransformColumnTypes(
				
				        ColumnasNecesarias,
				
				        {
				
				            {"Object_id", type text},
				
				            {"sap_id", Int64.Type},
				
				            {"material", type text},
				
				            {"diametre_n", Int64.Type},
				
				            {"gestio", type text},
				
				            {"data_insta", Int64.Type},
				
				            {"mun", type text},
				
				            {"tipus", type text},
				
				            {"tram_sap_i", type text},
				
				            {"afor_polis", type text},
				
				            {"sector_id", Int64.Type},
				
				            {"afor_pol_1", type text},
				
				            {"afor_us_ai", Int64.Type},
				
				            {"afor_us_1", type text},
				
				            {"afor_situa", type text},
				
				            {"afor_tip_s", type text},
				
				            {"afor_tipus", type text},
				
				            {"afor_dotac", Int64.Type},
				
				            {"afor_class", type text},
				
				            {"afor_num_i", Int64.Type},
				
				            {"afor_num_f", Int64.Type},
				
				            {"afor_sit_f", Int64.Type},
				
				            {"afor_nom_m", type text}
				
				        }
				
				    ),
				 
				    
				
				    //NORMALIZACIÓN
				
				    NormalizarTexto = (
				
				        valor as nullable text,
				
				        proper as logical,
				
				        defecto as nullable text
				
				    ) as nullable text =>
				
				        let
				
				            Texto = 
				
				                if valor = null 
				
				                then null 
				
				                else Text.Trim(Text.Clean(valor)),
				 
				            Resultado =
				
				                if Texto = null or Texto = "" then
				
				                    defecto
				
				                else if proper then
				
				                    Text.Proper(Texto)
				
				                else
				
				                    Texto
				
				        in
				
				            Resultado,
				 
				
				
				    //  NORMALIZAR TEXTOS
				
				    Textos = Table.TransformColumns(
				
				        Tipos,
				
				        {
				
				            // Proper + No Disponible
				
				            {"mun", each NormalizarTexto(_, true, "No Disponible"), type text},
				 
				            // Solo limpiar
				
				            {"tipus", each NormalizarTexto(_, false, null), type text},
				 
				            // Solo limpiar + No Disponible
				
				            {"afor_pol_1", each NormalizarTexto(_, false, "No Disponible"), type text},
				
				            {"afor_tipus", each NormalizarTexto(_, false, "No Disponible"), type text},
				 
				            // Proper
				
				            {"afor_us_1", each NormalizarTexto(_, true, null), type text},
				
				            {"afor_situa", each NormalizarTexto(_, true, null), type text},
				
				            {"afor_nom_m", each NormalizarTexto(_, true, null), type text},
				 
				            // Sí -> Si
				
				            {
				
				                "gestio",
				
				                each if _ = "Sí" then "Si" else _,
				
				                type text
				
				            }
				
				        }
				
				    ),
				 
				    //  VALORES POR DEFECTO NUMÉRICOS
				
				    Valores = Table.TransformColumns(
				
				        Textos,
				
				        {
				
				            {"data_insta", each if _ = null then 2100 else _, Int64.Type},
				
				            {"afor_num_f", each if _ = null then 0 else _, Int64.Type},
				
				            {"sector_id", each if _ = null then -1 else _, Int64.Type}
				
				        }
				
				    ),
				 
				    
				
				    //  ELIMINAR DUPLICADOS
				
				    Resultado = Table.Distinct(Valores)
				 
				in
				
				    Resultado
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

