table dim_tipus_operac_fraus
	lineageTag: b5a1924d-49eb-4dfa-a1a1-7783a4153207

	column tipus_ope
		dataType: string
		lineageTag: 8de88da3-f1ed-4639-8ffc-908882144974
		summarizeBy: none
		sourceColumn: tipus_ope

		annotation SummarizationSetBy = Automatic

	column descr_ope
		dataType: string
		lineageTag: 1f30a97a-d71e-44fb-b266-fe1ef14ef827
		summarizeBy: none
		sourceColumn: descr_ope

		annotation SummarizationSetBy = Automatic

	column Tipus_equip_a_treball
		dataType: string
		lineageTag: e7d7e779-a42b-496d-a69a-29ca784e9d42
		summarizeBy: none
		sourceColumn: Tipus_equip_a_treball

		annotation SummarizationSetBy = Automatic

	column 'Estat _ope'
		dataType: string
		lineageTag: 629a536a-414c-4420-9a5a-b3c3990f5ea8
		summarizeBy: none
		sourceColumn: Estat _ope

		annotation SummarizationSetBy = Automatic

	column grup_execu
		dataType: string
		lineageTag: 29a7f20b-3555-4bb5-b2a2-b2837c84c2aa
		summarizeBy: none
		sourceColumn: grup_execu

		annotation SummarizationSetBy = Automatic

	column tipo_parte_reposta
		dataType: string
		lineageTag: dc79b782-7731-4c0b-be46-64fe1691c4c0
		summarizeBy: none
		sourceColumn: tipo_parte_reposta

		annotation SummarizationSetBy = Automatic

	partition dim_tipus_operac_fraus = m
		mode: import
		queryGroup: Dimensiones
		source =
				let
				  Origen = GoogleSheets.Contents(#"TABLA OPERACIONES SISTEMÁTICAS"),
				  #"Navegación 1" = Origen{[name = "Operacions Sistemàtiques", ItemKind = "Table"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Encabezados promovidos",{{"Codi Operació", "tipus_ope"}, {"Nom operació", "descr_ope"}, {"Tipus d'equip sobre el que es fa el treball", "Tipus_equip_a_treball"}, {"Estat operació", "Estat _ope"}, {"Grup d'execució", "grup_execu"}, {"Tipo Parte Resposta", "tipo_parte_reposta"}}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columnas con nombre cambiado",{{"TIPO resposta", "tipo_resposta"}}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas con nombre cambiado1", each ([tipus_ope] = "C84" or [tipus_ope] = "C85" or [tipus_ope] = "C86" or [tipus_ope] = "C87" or [tipus_ope] = "C88" or [tipus_ope] = "C89" or [tipus_ope] = "C94")),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Filas filtradas",{"", "_1", "Descrpció", "Sistema origen", "Operació duplicada per comptador gran (>20 mm)?", "Realitzen empreses subcontractistes?", "La operació es pot crear en Camp (S/N)", "Parella (P) o solitari (S)?", "tipo_resposta"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas quitadas",{{"Estat _ope", type text}, {"descr_ope", type text}, {"Tipus_equip_a_treball", type text}, {"grup_execu", type text}, {"tipo_parte_reposta", type text}, {"tipus_ope", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

