table dim_sector
	lineageTag: 2081387d-7f27-4ebf-b6af-dea129b732f3

	column sector_id
		dataType: int64
		formatString: 0
		lineageTag: aa19c239-2a2a-48b9-8c9f-ecd71233fbd8
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column sector
		dataType: string
		lineageTag: 627172a6-6fd0-4fb4-83cd-286bfea0ca82
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column gerencia
		dataType: string
		lineageTag: c93f018c-8aa6-46de-a468-20d6a3741f5e
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	partition dim_sector = m
		mode: import
		source = ```
				// ESTA DIM SE GENERA A PARTIR DEL ARCHIVO 
				//              dim_sector
				// PESTAÑA:
				//              Sheet1
				let
				    Origen = GoogleSheets.Contents( "https://docs.google.com/spreadsheets/d/1pYWzB4BZBUnIqSPzeg1ezMwfhR1SevyUKxsCw8IAuKk/edit?gid=1370942235#gid=1370942235" ),
				    Datos = Origen{[name="Sheet1", ItemKind="Table"]}[Data],
				
				    #"Encabezados promovidos" = Table.PromoteHeaders(Datos, [PromoteAllScalars = true]),
				    #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"sector_id", Int64.Type}, {"denomin", type text}, {"gerencia", type text}}, "es"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo de columna cambiado",{{"denomin", "sector"}}),
				    #"Texto en formato título" =
				        Table.TransformColumns(
				            #"Columnas con nombre cambiado",
				            {
				                {"sector", Text.Proper, type text}
				            }
				        )
				    in
				        #"Texto en formato título"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

