table dim_aux_tipus_reg_cabali
	lineageTag: 6cde9412-9420-4d20-8339-b7cea178766d

	column cod_gerenciapc
		dataType: string
		lineageTag: e2051f3e-b6d3-47cf-a10d-79421afb931c
		summarizeBy: none
		sourceColumn: cod_gerenciapc

		annotation SummarizationSetBy = Automatic

	column tipus_regulac
		dataType: string
		lineageTag: e255c3ac-d843-4fa9-8863-023a66c6c738
		summarizeBy: none
		sourceColumn: tipus_regulac

		annotation SummarizationSetBy = Automatic

	partition dim_aux_tipus_reg_cabali = m
		mode: import
		queryGroup: Dimensiones
		source =
				let
				  Origen = GoogleSheets.Contents(Tipus_Regul_Cabal),
				  #"Navegación 1" = Origen{[name = "Reductors", ItemKind = "Table"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"Gerència", "ID", "Data Instal·lació", "Tipus Regulació","Núm. PC"}),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Otras columnas quitadas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Filas en blanco eliminadas",{{"Tipus Regulació", Text.Proper, type text}}),
				    #"Texto recortado" = Table.TransformColumns(#"Poner En Mayúsculas Cada Palabra",{{"Tipus Regulació", Text.Trim, type text}}),
				    #"Texto limpio" = Table.TransformColumns(#"Texto recortado",{{"Tipus Regulació", Text.Clean, type text}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Texto limpio",{{"ID", type text}}),
				    #"Poner En Mayúsculas Cada Palabra1" = Table.TransformColumns(#"Tipo cambiado",{{"ID", Text.Proper, type text}}),
				    #"Texto recortado1" = Table.TransformColumns(#"Poner En Mayúsculas Cada Palabra1",{{"ID", Text.Trim, type text}}),
				    #"Texto limpio1" = Table.TransformColumns(#"Texto recortado1",{{"ID", Text.Clean, type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Texto limpio1",{{"Gerència", "gerencia"}, {"ID", "id"}, {"Data Instal·lació", "data_instal"}, {"Tipus Regulació", "tipus_regulac"}}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"data_instal", type date}, {"gerencia", type text}}),
				    #"Poner En Mayúsculas Cada Palabra2" = Table.TransformColumns(#"Tipo cambiado1",{{"gerencia", Text.Proper, type text}}),
				    #"Filas ordenadas" = Table.Sort(#"Poner En Mayúsculas Cada Palabra2",{{"id", Order.Ascending}}),
				    #"Filas filtradas" = Table.SelectRows(#"Filas ordenadas", each true),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Filas filtradas",{{"Núm. PC", "cod_gerenciapc"}}),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Columnas con nombre cambiado1",{"cod_gerenciapc", "gerencia", "id", "data_instal", "tipus_regulac"}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas reordenadas",{{"cod_gerenciapc", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado2",{"id", "gerencia", "data_instal"}),
				    #"Filas ordenadas1" = Table.Sort(#"Columnas quitadas",{{"cod_gerenciapc", Order.Ascending}})
				in
				    #"Filas ordenadas1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

