table dim_art_bcn_g_pressio_101MIR
	lineageTag: f3a415fc-c037-404e-a9b9-a942955117c3

	column nº_de_nudo
		dataType: string
		lineageTag: 6ebd4a42-4b83-4451-a1b7-78912b5f62d2
		summarizeBy: none
		sourceColumn: nº_de_nudo

		annotation SummarizationSetBy = Automatic

	column z(m)
		dataType: double
		lineageTag: b4495145-1313-4fdb-926d-48a304ad14c2
		summarizeBy: sum
		sourceColumn: z(m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column profundidad(m)
		dataType: double
		lineageTag: 48211056-944a-4e78-9932-4cbdd74bdfc4
		summarizeBy: sum
		sourceColumn: profundidad(m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column zona_2
		dataType: double
		lineageTag: e8fbc0b3-b066-4ef6-8ade-8a4ea269a0a0
		summarizeBy: sum
		sourceColumn: zona_2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nombre
		dataType: string
		lineageTag: 588d5fea-bc03-4843-9003-d07b57bcfaf0
		summarizeBy: none
		sourceColumn: nombre

		annotation SummarizationSetBy = Automatic

	column pz_nit
		dataType: double
		lineageTag: f04def63-5f82-4412-bb13-c23bdef6ae86
		summarizeBy: sum
		sourceColumn: pz_nit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pzedifici
		dataType: double
		lineageTag: 88e5750c-8eef-4802-89b5-2f2b46ee6951
		summarizeBy: sum
		sourceColumn: pzedifici

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pteorica
		dataType: double
		lineageTag: 0aaa1351-9893-4806-8309-b2d569b94f77
		summarizeBy: sum
		sourceColumn: pteorica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preal
		dataType: double
		lineageTag: 9ebc718e-7f52-422d-9c5d-57f325e64f9e
		summarizeBy: sum
		sourceColumn: preal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column complim?
		dataType: string
		lineageTag: 8f6df165-b0c3-4131-a8ae-e195396a2162
		summarizeBy: none
		sourceColumn: complim?

		annotation SummarizationSetBy = Automatic

	column grup_pressio_nit
		dataType: double
		lineageTag: 55ab16f6-2334-44a9-b5bf-e75c91ba90d7
		summarizeBy: sum
		sourceColumn: grup_pressio_nit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column te_nit
		dataType: string
		lineageTag: 09b39019-1bda-4520-8976-93451bcad272
		summarizeBy: none
		sourceColumn: te_nit

		annotation SummarizationSetBy = Automatic

	column pz_dia
		dataType: double
		lineageTag: 26108a64-4f5c-40df-a857-bd01ea69d0d2
		summarizeBy: sum
		sourceColumn: pz_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preal_3
		dataType: double
		lineageTag: 58ba48ce-4d2b-46ff-b118-d686af97c48c
		summarizeBy: sum
		sourceColumn: preal_3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grup_pressio_dia
		dataType: double
		lineageTag: a671c654-c8cd-40ab-85f7-ddcf47265a0f
		summarizeBy: sum
		sourceColumn: grup_pressio_dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column te_dia
		dataType: string
		lineageTag: eaf03161-b6fb-4f1b-a3b3-28d52a53d0b2
		summarizeBy: none
		sourceColumn: te_dia

		annotation SummarizationSetBy = Automatic

	partition dim_art_bcn_g_pressio_101MIR = m
		mode: import
		queryGroup: Auxiliares\dim_art_bcn_g_pressio
		source = ```
				let
				    Origen = GoogleSheets.Contents(#"BCN G Pressio"),
				    #"101MIR_Table" = Origen{[name="101MIR",ItemKind="Table"]}[Data],
				     #"Encabezados promovidos" = Table.PromoteHeaders(#"101MIR_Table", [PromoteAllScalars=true]),
				     // 2. Limpieza de nombres de columna (minúsculas, sin acentos y con _)
				    EncabezadosLimpios = Table.TransformColumnNames(#"Encabezados promovidos", each 
				        let
				            sinSaltos = Text.Replace(Text.Replace(_, "#(lf)", " "), "#(cr)", " "),
				            textoBase = Text.Replace(Text.Lower(Text.Trim(sinSaltos)), " ", "_"),
				            reemplazos = {
				                {"á","a"}, {"é","e"}, {"í","i"}, {"ó","o"}, {"ú","u"}, 
				                {"à","a"}, {"è","e"}, {"ò","o"}, 
				                {"ï","i"}, {"ü","u"}
				            },
				            textoLimpio = List.Accumulate(reemplazos, textoBase, (estado, actual) => Text.Replace(estado, actual{0}, actual{1}))
				        in
				            textoLimpio
				    ),
				    #"Columnas quitadas" = Table.RemoveColumns(EncabezadosLimpios,{"20-130", "pzedifici_1", "pteorica_2"}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas quitadas",{{"sector", Int64.Type}}),
				
				
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Tipo cambiado2",{{"zeta", type number}, {"profunditats", type number}, {"nombre", type text}, {"pz_nit", type number}, {"pzedifici", type number}, {"pteorica", type number}, {"preal", type number}, {"grup_pressio", type number}, {"te_?", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"te_?", "te_nit"}, {"te_?_5", "te_dia"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","","No Disponible",Replacer.ReplaceValue,{"te_nit", "te_dia"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado",{{"pz_dia", type number}, {"preal_3", type number}, {"grup_pressio_4", type number}}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Tipo cambiado1",{{"iden", "nº_de_nudo"}, {"zeta", "z(m)"}, {"profunditats", "profundidad(m)"}, {"sector", "zona_2"}, {"grup_pressio_4", "grup_pressio_dia"}, {"grup_pressio", "grup_pressio_nit"}, {"compleix?", "complim?"}}),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"zona_2", type number}})
				in
				    #"Tipo cambiado3"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

