table dim_arteria
	lineageTag: 1669ea0a-40db-4c42-81ae-b3b0675727ca

	column gerencia
		dataType: string
		lineageTag: 4d738b66-1b42-460c-9c1b-0976b6b29d56
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	column arteria
		dataType: string
		lineageTag: e294918d-42ba-4578-81ff-5eb4ab3354a4
		summarizeBy: none
		sourceColumn: arteria

		annotation SummarizationSetBy = Automatic

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: 6563a7d1-99ce-420c-a034-d39dbc8635e7
		summarizeBy: none
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

	partition dim_arteria = m
		mode: import
		queryGroup: Dimensiones
		source =
				let
				    Union =
				        Table.Combine({
				            fact_rend_anr_arterias_llobregadsub_mensual,
				            fact_rend_anr_arterias_llobregadnord_mensual,
				            fact_rend_anr_arterias_bcn_sud_mensual,
				            fact_rend_anr_arterias_bcn_nord_mensual,
				            fact_rend_anr_arterias_besos_mensual,
				            fact_rend_anr_arterias_multi_dz_mensual
				        }),
				
				    DimArteria =
				        Table.Distinct(
				            Table.SelectColumns(Union, {"gerencia", "arteria"})
				        ),
				
				    Resultado =
				        Table.ReplaceValue(
				            Table.ReplaceValue(
				                DimArteria,
				                "Bcn", "Barcelona",
				                Replacer.ReplaceText,
				                {"gerencia"}
				            ),
				            "Besos", "Besòs",
				            Replacer.ReplaceText,
				            {"gerencia"}
				        ),
				    #"Consultas combinadas" = Table.NestedJoin(Resultado, {"gerencia"}, dim_gerencia, {"gerencia"}, "dim_gerencia", JoinKind.LeftOuter),
				    #"Se expandió dim_gerencia" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_gerencia", {"gerencia_id"}, {"gerencia_id"})
				in
				    #"Se expandió dim_gerencia"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

