table dim_dades_sectors
	lineageTag: 7dda3706-9e1d-480c-91fe-1f379530847f

	column sector_id
		dataType: int64
		formatString: 0
		lineageTag: 3c909e2b-60b0-42c3-86c7-4518524ba32e
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column pressio
		dataType: string
		lineageTag: 2ce56a7b-9726-412f-9966-5861277b4bad
		summarizeBy: none
		sourceColumn: pressio

		annotation SummarizationSetBy = Automatic

	column long_xarxa
		dataType: int64
		formatString: 0
		lineageTag: 38e1e369-ea48-4acb-987b-e87957e13d4d
		summarizeBy: sum
		sourceColumn: long_xarxa

		annotation SummarizationSetBy = Automatic

	column ramals_controlats
		dataType: int64
		formatString: 0
		lineageTag: e07528cd-4df1-4a7e-a330-29c4691d5794
		summarizeBy: sum
		sourceColumn: ramals_controlats

		annotation SummarizationSetBy = Automatic

	column subministraments_controlats
		dataType: int64
		formatString: 0
		lineageTag: df39eec1-ba21-47aa-b007-0d3800d9375f
		summarizeBy: sum
		sourceColumn: subministraments_controlats

		annotation SummarizationSetBy = Automatic

	column pressio_mitjana
		dataType: double
		lineageTag: 0a24ec85-f43e-4334-9e26-0409bd53484c
		summarizeBy: sum
		sourceColumn: pressio_mitjana

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lambert
		dataType: double
		lineageTag: f4bd4f08-9bfd-4fa7-961c-0de1436ea245
		summarizeBy: sum
		sourceColumn: lambert

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column afor_l_s
		dataType: double
		lineageTag: 8d9940a6-b13e-4106-9196-e73525f1f498
		summarizeBy: sum
		sourceColumn: afor_l_s

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column referencia
		dataType: double
		lineageTag: 015d8aba-932b-46eb-8fc1-c3544cdedd47
		summarizeBy: sum
		sourceColumn: referencia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sector_activo
		dataType: string
		lineageTag: 58c38cfd-cca4-4ac8-8a3c-d0a8c6a09cc8
		summarizeBy: none
		sourceColumn: sector_activo

		annotation SummarizationSetBy = Automatic

	column gerencia_id
		dataType: double
		lineageTag: b85ac79d-0599-4e72-8e15-615de54eb56f
		summarizeBy: none
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sector
		dataType: string
		lineageTag: 99862d3b-49d7-4239-816b-27fe432b215a
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column latitud
		dataType: string
		lineageTag: e7e6061b-cf89-4d33-8f27-41de3dad2bcd
		summarizeBy: none
		sourceColumn: latitud

		annotation SummarizationSetBy = Automatic

	column longitud
		dataType: string
		lineageTag: fd8f2174-a0c6-4332-a756-e85cb1ccd1c6
		summarizeBy: none
		sourceColumn: longitud

		annotation SummarizationSetBy = Automatic

	column gerencia
		dataType: string
		lineageTag: ef9d1ddb-c48c-409a-b552-2f18c200dcde
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	column num_points
		dataType: int64
		formatString: 0
		lineageTag: c3c3eae8-9421-4fe4-a3f3-9f6d36f5397e
		summarizeBy: sum
		sourceColumn: num_points

		annotation SummarizationSetBy = Automatic

	partition dim_dades_sectors = m
		mode: import
		queryGroup: Dimensiones
		source =
				let
					Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1ZffEmnNoWOUZV2BWTDYGZTjcNVbZ07il0J7N43DN_IU/edit?gid=1520384286#gid=1520384286"),
				 	#"Navegación 1" = Origen{[name = "Dades Sectors", ItemKind = "Table"]}[Data],
					#"Encabezados promovidos1" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars=true]),
					#"Columnas con nombre cambiado2" = Table.RenameColumns(#"Encabezados promovidos1",{{"Sector / Artèria", "sector_id"}, {"Sector", "sector"}, {"Pis de Pressió", "pressio"}, {"Gerència", "gerencia"}, {"Long de xarxa", "long_xarxa"}, {"Ramals Controlats", "ramals_controlats"}, {"Subministraments Controlats", "subministraments_controlats"}, {"Pressió mitjana", "pressio_mitjana"}, {"Lambert", "lambert"}, {"afor (l/s)", "afor_l_s"}, {"Referència", "referencia"}, {"Sector en Servei", "sector_activo"}}),
					#"Columnas quitadas1" = Table.RemoveColumns(#"Columnas con nombre cambiado2",{""}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas quitadas1",{{"long_xarxa", Int64.Type}, {"ramals_controlats", Int64.Type}, {"subministraments_controlats", Int64.Type}, {"pressio_mitjana", type number}, {"lambert", type number}, {"afor_l_s", type number}, {"referencia", type number}, {"sector_id", Int64.Type}}),
				    #"Errores quitados" = Table.RemoveRowsWithErrors(#"Tipo cambiado", {"sector_id"}),
				    #"Filas vacías quitadas" =
				    Table.SelectRows(
				        #"Errores quitados",
				        each List.AnyTrue(
				            List.Transform(
				                Record.FieldValues(_),
				                each _ <> null and _ <> ""
				            )
				        )
				    ),
				    #"Consultas combinadas" = Table.NestedJoin(#"Filas vacías quitadas", {"gerencia"}, dim_gerencia, {"gerencia"}, "dim_gerencia", JoinKind.LeftOuter),
				    #"Se expandió dim_gerencia" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_gerencia", {"gerencia_id"}, {"gerencia_id"}),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Se expandió dim_gerencia",{{"sector", Text.Proper, type text}}),
				    #"Texto limpio" = Table.TransformColumns(#"Poner En Mayúsculas Cada Palabra",{{"sector", Text.Clean, type text}}),
				    #"Texto recortado" = Table.TransformColumns(#"Texto limpio",{{"sector", Text.Trim, type text}}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Texto recortado", {"sector_id"}, aux_dim_sector, {"sector_id"}, "aux_dim_sector", JoinKind.LeftOuter),
				    #"Se expandió aux_dim_sector" = Table.ExpandTableColumn(#"Consultas combinadas1", "aux_dim_sector", {"latitud", "longitud"}, {"latitud", "longitud"}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Se expandió aux_dim_sector",null,3,Replacer.ReplaceValue,{"gerencia_id"}),
				    #"Consulta anexada" = Table.Combine({#"Valor reemplazado", aux_sector_no_disp}),
				    #"Duplicados quitados" = Table.Distinct(#"Consulta anexada"),
				    #"Filas filtradas" =Table.SelectRows(
				        #"Duplicados quitados",
				        each not ([latitud] = null and [longitud] = null)
				    ),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Filas filtradas",{{"sector_id", Int64.Type}, {"long_xarxa", Int64.Type}, {"ramals_controlats", Int64.Type}, {"subministraments_controlats", Int64.Type}, {"pressio_mitjana", type number}, {"lambert", type number}, {"afor_l_s", type number}, {"referencia", type number}, {"sector_activo", type text}}),
				    #"Columnas quitadas2" = Table.RemoveColumns(#"Tipo cambiado1",{"_1", "_2"}),
				    #"Consultas combinadas2" = Table.NestedJoin(#"Columnas quitadas2", {"sector_id"}, aux_dim_ortomat_sectores, {"sector_id"}, "aux_dim_ortomat_sectores", JoinKind.LeftOuter),
				    #"Se expandió aux_dim_ortomat_sectores" = Table.ExpandTableColumn(#"Consultas combinadas2", "aux_dim_ortomat_sectores", {"num_points"}, {"aux_dim_ortomat_sectores.num_points"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió aux_dim_ortomat_sectores",{{"aux_dim_ortomat_sectores.num_points", "num_points"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

