table dim_sector
	lineageTag: 5a9aac1f-43db-436e-ab7e-5d103f702119

	column sector_id
		dataType: int64
		formatString: 0
		lineageTag: 29327a4a-e2ee-4cfe-90db-f4c27ffd36dd
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column latitud
		dataType: double
		lineageTag: 6e60a9e8-3b25-4823-af58-2cc0ba4bc1d8
		summarizeBy: sum
		sourceColumn: latitud

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitud
		dataType: double
		lineageTag: 46c90447-fa4b-418d-92d6-92785b0fe283
		summarizeBy: sum
		sourceColumn: longitud

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sector
		dataType: string
		lineageTag: 04ec2c77-1b6c-4d1b-b9e3-d9a412cb825b
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: 092a1534-ab98-4d23-952d-284e1de07e95
		summarizeBy: none
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

	partition dim_sector = m
		mode: import
		source = ```
				// TABLA 1 -Coordenadas
				
				let 
				    Origen1 = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1l9btpQJf9bOrnwWyDpkAZpQXill8mdHHxKlHcdf_DVQ/edit?gid=1726033904#gid=1726033904"), 
				    Nav1 = Origen1{[name = "coordenadas por sector bcn.csv", 
				    ItemKind = "Table"]}[Data], 
				    Quitadas = Table.RemoveColumns(Nav1,{"Column1", "Column2", "Column3"}), 
				    Headers1 = Table.PromoteHeaders(Quitadas, [PromoteAllScalars=true]),
				    Tipos1 = Table.TransformColumnTypes(Headers1,{{"sector_id", Int64.Type}, {"latitud", type number}, {"longitud", type number}}), 
				    SinDuplicados = Table.Distinct(Tipos1), 
				    Coordenadas = Table.SelectRows(SinDuplicados, each List.NonNullCount(Record.FieldValues(_)) > 0),
				// TABLA 2 - Sectores 
				    Origen2 = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vRH4WiST8QUNFuYRZ1ilIw7p1mfJMiAz5bImbBz2ffnYgrxn2MyRB5O192pgqrP_SyFQdf6CJroUA9G/pub?gid=0&single=true&output=csv"), [Delimiter = ",", Columns = 3, Encoding = 65001, QuoteStyle = QuoteStyle.None]), 
				    Headers2 = Table.PromoteHeaders(Origen2, [PromoteAllScalars = true]),
				    Tipos2 = Table.TransformColumnTypes(Headers2, {{"sector_id", Int64.Type}, {"denomin", type text}, {"gerencia", type text}}, "es"), 
				    Renombrada = Table.RenameColumns(Tipos2,{{"denomin", "sector"}}), 
				    Sectores = Table.TransformColumns(Renombrada, {{"sector", Text.Proper, type text}}),
				    // UNION
				    Join = Table.NestedJoin( Coordenadas, {"sector_id"},Sectores, {"sector_id"},"Sectores", JoinKind.LeftOuter ),
				    Resultado = Table.ExpandTableColumn( Join, "Sectores", {"sector", "gerencia"}, {"sector", "gerencia"} ),
				    #"Valor reemplazado" = Table.ReplaceValue(Resultado,null,"No Disponible",Replacer.ReplaceValue,{"gerencia"}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Valor reemplazado", {"gerencia"}, dim_gerencia, {"gerencia"}, "dim_gerencia", JoinKind.LeftOuter),
				    #"Se expandió dim_gerencia" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_gerencia", {"gerencia_id"}, {"gerencia_id"}),
				    auxiliar =
				    Table.Combine({
				        #"Se expandió dim_gerencia",
				        dim_sector_aux
				    }),
				    #"Columnas quitadas" = Table.RemoveColumns(auxiliar,{"gerencia"})
				in
				    #"Columnas quitadas"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

