table fact_cabals_mínims
	lineageTag: 2b8a1269-956c-48ff-b0ff-5b8c1f1bcf33

	column sector_id
		dataType: int64
		formatString: 0
		lineageTag: 67379891-00af-44a9-96a8-13b6037aac08
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column gerencia
		dataType: string
		lineageTag: 90421e71-f9ff-4ff7-9c3d-e482ac1775b4
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	column preguntar
		dataType: string
		lineageTag: 2d3bf6ae-e08b-4d16-9f24-0e4930f0329f
		summarizeBy: none
		sourceColumn: preguntar

		annotation SummarizationSetBy = Automatic

	column sectors
		dataType: string
		lineageTag: b091a18d-3b1d-41a3-b9c4-c4a53b8d4a5e
		summarizeBy: none
		sourceColumn: sectors

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5d6a8e90-4e5a-4cfe-8b0f-d48eceae4e25
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column q_min
		dataType: double
		lineageTag: 4a5995df-ad08-46ce-ba10-204791094bde
		summarizeBy: sum
		sourceColumn: q_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_cabals_mínims = m
		mode: import
		source =
				let
				    Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1ZffEmnNoWOUZV2BWTDYGZTjcNVbZ07il0J7N43DN_IU/edit?gid=1259268357#gid=1259268357"),
				    Datos = Origen{[name="Cabals Mínims", ItemKind="Table"]}[Data],
				    DatosLimpios = Table.PromoteHeaders(
				        Table.Skip(Datos, 2),
				        [PromoteAllScalars = true]
				    ),
				    Renombradas = Table.RenameColumns(DatosLimpios, {
				        {"Nº", "sector_id"},
				        {"Gerència", "gerencia"},
				        {"Sectors", "sectors"},
				        {"Q ref", "q_ref"},
				        {"", "preguntar"}
				    }),
				    Eliminadas = Table.RemoveColumns(Renombradas, {"q_ref", "_1", "_2", "_3"}),
				    Despivotadas = Table.UnpivotOtherColumns(
				        Eliminadas,
				        {"sector_id", "preguntar", "gerencia", "sectors"},
				        "fecha",
				        "q_min"
				    ),
				    Tipos = Table.TransformColumnTypes(
				        Despivotadas,
				        {
				            {"sector_id", Int64.Type},
				            {"gerencia", type text},
				            {"preguntar", type text},
				            {"sectors", type text},
				            {"fecha", type date},
				            {"q_min", type number}
				        }
				    ),
				    #"Filas filtradas" = Table.SelectRows(Tipos, each true)
				in
				    #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

