table fact_inventari_xarxa_mensual
	lineageTag: 2b91454c-c160-4687-a602-165ee754b802

	column Mes
		dataType: string
		lineageTag: 0100f23f-1557-4d55-9f33-73d078cb70a9
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'L (km) '
		dataType: string
		lineageTag: 3158eaef-2f9f-4f5e-b5fd-a95ef8dc2eab
		summarizeBy: none
		sourceColumn: "L (km) "

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses'
		dataType: string
		lineageTag: 84445138-6aa9-49c4-b376-87c030106071
		summarizeBy: none
		sourceColumn: Nombre escomeses

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin.'
		dataType: string
		lineageTag: e132bac3-0715-4879-8d33-c9be9353684c
		summarizeBy: none
		sourceColumn: Nombre Submin.

		annotation SummarizationSetBy = Automatic

	column 'L (km) _1'
		dataType: string
		lineageTag: 0d79d75a-1376-4b5d-a139-6c469adb158b
		summarizeBy: none
		sourceColumn: L (km) _1

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses_2'
		dataType: string
		lineageTag: f3a7298a-58dc-472f-9771-7237433ded2a
		summarizeBy: none
		sourceColumn: Nombre escomeses_2

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin._3'
		dataType: string
		lineageTag: 1ea9e0d3-9720-4672-8ce3-f603f82a2333
		summarizeBy: none
		sourceColumn: Nombre Submin._3

		annotation SummarizationSetBy = Automatic

	column 'L (km) _4'
		dataType: string
		lineageTag: 9d6b17a3-aa6f-406c-b9b2-72be2c356587
		summarizeBy: none
		sourceColumn: L (km) _4

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses_5'
		dataType: string
		lineageTag: 3c9398fa-5142-42c3-a9ca-76084587d233
		summarizeBy: none
		sourceColumn: Nombre escomeses_5

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin._6'
		dataType: string
		lineageTag: a0071c99-d9bf-4a53-9901-3b3f82001946
		summarizeBy: none
		sourceColumn: Nombre Submin._6

		annotation SummarizationSetBy = Automatic

	column 'L (km) _7'
		dataType: string
		lineageTag: a75c490e-6773-4acb-b4cf-5f5e6ac182b9
		summarizeBy: none
		sourceColumn: L (km) _7

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses_8'
		dataType: string
		lineageTag: aeb21082-eaf2-41c4-a4c5-5ff4c8333683
		summarizeBy: none
		sourceColumn: Nombre escomeses_8

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin._9'
		dataType: string
		lineageTag: c23708a0-8040-4967-a425-bb0d8a97c152
		summarizeBy: none
		sourceColumn: Nombre Submin._9

		annotation SummarizationSetBy = Automatic

	column 'L (km) _10'
		dataType: string
		lineageTag: 40286ea6-8e16-46cc-b922-71c932e0d1cd
		summarizeBy: none
		sourceColumn: L (km) _10

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses_11'
		dataType: string
		lineageTag: 6f2aad9f-3b18-449a-bbff-0ed74f7676a9
		summarizeBy: none
		sourceColumn: Nombre escomeses_11

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin._12'
		dataType: string
		lineageTag: 855dc279-a554-4605-8475-f0e799bb8db9
		summarizeBy: none
		sourceColumn: Nombre Submin._12

		annotation SummarizationSetBy = Automatic

	column 'L (km) _13'
		dataType: string
		lineageTag: dd510899-3778-4d45-a83a-120d97e4e908
		summarizeBy: none
		sourceColumn: L (km) _13

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses_14'
		dataType: string
		lineageTag: 6a8bc450-858f-4759-9096-ea7cfc513e18
		summarizeBy: none
		sourceColumn: Nombre escomeses_14

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin._15'
		dataType: string
		lineageTag: 51213479-bab2-4e72-88b9-62e9d0ec73ce
		summarizeBy: none
		sourceColumn: Nombre Submin._15

		annotation SummarizationSetBy = Automatic

	column 'L (km) _16'
		dataType: string
		lineageTag: 4baab4fa-484c-4736-ba52-721c250bc3b2
		summarizeBy: none
		sourceColumn: L (km) _16

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses Controlades'
		dataType: string
		lineageTag: 215f4cef-0528-43ba-89af-50380cb4ea7f
		summarizeBy: none
		sourceColumn: Nombre escomeses Controlades

		annotation SummarizationSetBy = Automatic

	column 'Nombre Subministraments Controlades'
		dataType: string
		lineageTag: c6b9dbdb-79ac-41e3-ba95-be01ea833104
		summarizeBy: none
		sourceColumn: Nombre Subministraments Controlades

		annotation SummarizationSetBy = Automatic

	column 'L (km)'
		dataType: string
		lineageTag: d997d67a-e9ae-4b77-98d1-b44099eb1300
		summarizeBy: none
		sourceColumn: L (km)

		annotation SummarizationSetBy = Automatic

	column 'L + T (km)'
		dataType: string
		lineageTag: 951af53a-5c34-44b3-a5f3-a9ef7c84c8a5
		summarizeBy: none
		sourceColumn: L + T (km)

		annotation SummarizationSetBy = Automatic

	column 'Nombre Escomeses Totals'
		dataType: string
		lineageTag: e2d47cdb-5c04-424f-8005-8a7b8ce68e39
		summarizeBy: none
		sourceColumn: Nombre Escomeses Totals

		annotation SummarizationSetBy = Automatic

	column 'Nombre Subministraments Totals'
		dataType: string
		lineageTag: cdb78077-049f-4475-8c64-0b97977cf0ed
		summarizeBy: none
		sourceColumn: Nombre Subministraments Totals

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: ee38a44d-623e-4df9-8d2c-2c1b7221508e
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_inventari_xarxa_mensual = m
		mode: import
		source = ```
				let
				  Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vQYF-6nyJqkaezSpkqBN_a0Qmxw1GysBfL8py3eq4WzwX0xzzitdfbvqMzf9D-0YQ/pub?gid=664401204&single=true&output=csv"),[Delimiter=",", Columns=48, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Filas superiores quitadas" = Table.Skip(Origen,374),
				    #"Conservar filas superiores" = Table.FirstN(#"Filas superiores quitadas",13),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Conservar filas superiores", [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"Mes", "L (km) ", "Nombre escomeses", "Nombre Submin.", "L (km) _1", "Nombre escomeses_2", "Nombre Submin._3", "L (km) _4", "Nombre escomeses_5", "Nombre Submin._6", "L (km) _7", "Nombre escomeses_8", "Nombre Submin._9", "L (km) _10", "Nombre escomeses_11", "Nombre Submin._12", "L (km) _13", "Nombre escomeses_14", "Nombre Submin._15", "L (km) _16", "Nombre escomeses Controlades", "Nombre Subministraments Controlades", "L (km)", "L + T (km)", "Nombre Escomeses Totals", "Nombre Subministraments Totals"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Otras columnas quitadas", "fecha", each let
				    txt0  = [Mes],
				    // pasar a minúsculas
				    txt1  = Text.Lower(txt0),
				    // quitar "de ", "d’" y puntos
				    txt2  = Text.Replace(Text.Replace(Text.Replace(txt1,"de ",""),"d’",""),".",""),
				    // separar mes y año por el guion -
				    mesTxt = Text.BeforeDelimiter(txt2,"-"),
				    anioTxt = Text.AfterDelimiter(txt2,"-"),
				    // convertir año tipo "21" -> 2021
				    anio = 2000 + Number.FromText(anioTxt),
				    // mapear mes catalán -> número
				    mes = 
				        if mesTxt = "gen"  then 1 else
				        if mesTxt = "febr" then 2 else
				        if mesTxt = "març" then 3 else
				        if mesTxt = "abr"  then 4 else
				        if mesTxt = "maig" then 5 else
				        if mesTxt = "juny" then 6 else
				        if mesTxt = "jul"  then 7 else
				        if mesTxt = "ag"   then 8 else
				        if mesTxt = "set"  then 9 else
				        if mesTxt = "oct"  then 10 else
				        if mesTxt = "nov"  then 11 else
				        if mesTxt = "des"  then 12 else
				        null
				in
				    #date(anio, mes, 1))
				in
				    #"Personalizada agregada"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

