table fact_fraudes
	lineageTag: 01a25b1f-66dc-4dac-a68d-4fb6624188a7

	column polissa_subm
		dataType: string
		lineageTag: 12672754-c4ea-4668-8f63-100e98eb5aa1
		summarizeBy: none
		sourceColumn: polissa_subm

		annotation SummarizationSetBy = Automatic

	column codi_comanda
		dataType: int64
		formatString: 0
		lineageTag: 56b50f32-bd4f-464c-9ae6-5fcbbe815097
		summarizeBy: sum
		sourceColumn: codi_comanda

		annotation SummarizationSetBy = Automatic

	column comanda_posterior
		dataType: int64
		formatString: 0
		lineageTag: 405d6522-5bb1-4476-9777-1e0ec5cd9579
		summarizeBy: sum
		sourceColumn: comanda_posterior

		annotation SummarizationSetBy = Automatic

	column data_creacio_original
		dataType: dateTime
		formatString: Short Date
		lineageTag: 67270f96-46e7-4692-a83b-2ebb6d587759
		summarizeBy: none
		sourceColumn: data_creacio_original

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column tipus_ope
		dataType: string
		lineageTag: e4ab7d47-d233-4071-b25e-ef26adaa5adc
		summarizeBy: none
		sourceColumn: tipus_ope

		annotation SummarizationSetBy = Automatic

	column data_creacio_final
		dataType: dateTime
		formatString: Short Date
		lineageTag: c5fe74f9-bafb-4880-807f-dc296a512bc4
		summarizeBy: none
		sourceColumn: data_creacio_final

		variation Variación
			isDefault
			relationship: 2fc70948-9d9c-45be-8951-17760ee1eb52
			defaultHierarchy: LocalDateTable_77b8393a-f732-455b-b181-036d3a654a06.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_fi_execucio_final
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9f934ca1-b9a6-417b-8517-b095a5041856
		summarizeBy: none
		sourceColumn: data_fi_execucio_final

		variation Variación
			isDefault
			relationship: a7aa4235-4173-471e-b72d-7a75debf293f
			defaultHierarchy: LocalDateTable_809296de-066e-4947-bada-14641abef3cd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ind_resultat
		dataType: string
		lineageTag: 4d404e83-9bb3-4002-8bbd-a48fd485608c
		summarizeBy: none
		sourceColumn: ind_resultat

		annotation SummarizationSetBy = Automatic

	column codi_ope_fi
		dataType: int64
		formatString: 0
		lineageTag: 2a14d99b-24b2-4f20-a9e4-388ef20b6efb
		summarizeBy: sum
		sourceColumn: codi_ope_fi

		annotation SummarizationSetBy = Automatic

	column tipus_ope_pendent
		dataType: string
		lineageTag: 436ce439-8c29-4562-9f60-5d6d8fec93a6
		summarizeBy: none
		sourceColumn: tipus_ope_pendent

		annotation SummarizationSetBy = Automatic

	column data_creacio_actual
		dataType: dateTime
		formatString: Short Date
		lineageTag: dff58697-da08-4c16-8297-b282e16c4e71
		summarizeBy: none
		sourceColumn: data_creacio_actual

		variation Variación
			isDefault
			relationship: 5d4923f7-0e43-4af5-829c-baeeebd09d6e
			defaultHierarchy: LocalDateTable_084fd0ed-46dd-41aa-9f1d-e4b9df9ed9c1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_fraudes = m
		mode: import
		source =
				let
				  Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vTkaRRTpAF3cjORlQlBr64cW8dF1PQno-yNRXYHRo0G_2T6Nx_slDfrZQ6mfLL-uA/pub?gid=273809892&single=true&output=csv"), [Delimiter = ",", Columns = 11, QuoteStyle = QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(
				        Origen,
				        [PromoteAllScalars = true]
				    ),
				
				    #"Tipo cambiado" = Table.TransformColumnTypes(
				        #"Encabezados promovidos",
				        {
				            {"POLISSA_SUBM", type text},
				            {"CODI_COMANDA", Int64.Type},
				            {"COMANDA_POSTERIOR", Int64.Type},
				            {"DATA_CREACIO_ORIGINAL", type datetime},
				            {"TIPUS_OPE", type text},
				            {"DATA_CREACIO_FINAL", type datetime},
				            {"DATA_FI_EXECUCIO_FINAL", type datetime},
				            {"IND_RESULTAT", type text},
				            {"CODI_OPE_FI", Int64.Type},
				            {"TIPUS_OPE_PENDENT", type text},
				            {"DATA_CREACIO_ACTUAL", type datetime}
				        }
				    ),
				
				    #"Fechas sin hora" = Table.TransformColumns(
				        #"Tipo cambiado",
				        {
				            {"DATA_CREACIO_ORIGINAL", DateTime.Date, type date},
				            {"DATA_CREACIO_FINAL", DateTime.Date, type date},
				            {"DATA_FI_EXECUCIO_FINAL", DateTime.Date, type date},
				            {"DATA_CREACIO_ACTUAL", DateTime.Date, type date}
				        }
				    ),
				
				    #"Encabezados Title Case" = Table.TransformColumnNames(
				        #"Fechas sin hora",
				        each Text.Proper(Text.Lower(_))
				    ),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Encabezados Title Case",{{"Polissa_Subm", "polissa_subm"}, {"Codi_Comanda", "codi_comanda"}, {"Comanda_Posterior", "comanda_posterior"}, {"Data_Creacio_Original", "data_creacio_original"}, {"Tipus_Ope", "tipus_ope"}, {"Data_Creacio_Final", "data_creacio_final"}, {"Data_Fi_Execucio_Final", "data_fi_execucio_final"}, {"Ind_Resultat", "ind_resultat"}, {"Codi_Ope_Fi", "codi_ope_fi"}, {"Tipus_Ope_Pendent", "tipus_ope_pendent"}, {"Data_Creacio_Actual", "data_creacio_actual"}})
				
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

