table fact_dades_consum
	lineageTag: 371bb792-34d1-4b76-8722-f46c4af7d3c0

	column polissa_subm
		dataType: string
		lineageTag: fd36f7e0-c9e7-4e19-a365-441a257b1622
		summarizeBy: none
		sourceColumn: polissa_subm

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5b6cb097-26df-496f-8fdc-0027278b7ee0
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column qmin_hora
		dataType: double
		lineageTag: 534c8f9c-e500-40a4-b2bd-bee057e29678
		summarizeBy: sum
		sourceColumn: qmin_hora

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qmax_hora
		dataType: double
		lineageTag: 09b4d12d-8678-42e0-b224-2c2426b665bc
		summarizeBy: sum
		sourceColumn: qmax_hora

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consum_mensual_real
		dataType: double
		lineageTag: d3d2b868-e4af-4445-8f57-7838907c71a5
		summarizeBy: sum
		sourceColumn: consum_mensual_real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consum_mensual_estimat
		dataType: double
		lineageTag: 0a02645a-a9d4-48d1-aa71-f67f4f302c51
		summarizeBy: sum
		sourceColumn: consum_mensual_estimat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lectures_rebudes
		dataType: double
		lineageTag: a9b617bb-bd81-428e-b458-01d2ce016bb1
		summarizeBy: sum
		sourceColumn: lectures_rebudes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dies_llegits
		dataType: double
		lineageTag: 2fd9a77d-c149-433f-9e89-09dda026b9fe
		summarizeBy: sum
		sourceColumn: dies_llegits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dies_absents
		dataType: double
		lineageTag: 5e5ec502-1ef1-4164-8dd9-b75c6c6e7d67
		summarizeBy: sum
		sourceColumn: dies_absents

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dies_amb_registre
		dataType: double
		lineageTag: 016290a2-38cd-4bad-9834-a0497a501119
		summarizeBy: sum
		sourceColumn: dies_amb_registre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dies_amb_consum_0
		dataType: double
		lineageTag: ac9f6e33-fd01-4337-99a0-6843d4e2a694
		summarizeBy: sum
		sourceColumn: dies_amb_consum_0

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column num_series_contador_2025_mes
		dataType: double
		lineageTag: 1efe8709-3a90-425d-a480-1fc79063690c
		summarizeBy: sum
		sourceColumn: num_series_contador_2025_mes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_dades_consum = m
		mode: import
		source =
				let
				    // Cargar parquet 2025
				    T2025 = Parquet.Document(File.Contents("C:\data\dades_tlt_snowflake_2025.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				
				    // Cargar parquet 2026
				    T2026 = Parquet.Document(
				                File.Contents("C:\data\dades_tlt_snowflake_2026.parquet"),
				                [Compression=null, LegacyColumnNameEncoding=false]
				            ),
				
				    // Combinar ambos
				    Combined = Table.Combine({T2025, T2026}),
				
				    // Convertir nombres de columnas a minúsculas
				    LowerCols = Table.TransformColumnNames(Combined, Text.Lower),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(LowerCols,{{"mes", "fecha"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

