table fact_inventari_xarxa_distribucion
	lineageTag: 2b91454c-c160-4687-a602-165ee754b802

	measure escomeses_12m_mitjana = ```
			
			    CALCULATE(
			    AVERAGE( 'fact_inventari_xarxa_distribucion'[escomeses] ),
			    DATESINPERIOD(
			        dim_calendario[Date],
			        MAX(dim_calendario[Date]),
			        -12,
			        MONTH
			    )
			) 
			```
		displayFolder: _medidas_2
		lineageTag: 3e5694ec-4087-44a6-a248-c3829d5cef0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure escomeses_mensual = ```
			SUM(fact_inventari_xarxa_distribucion[escomeses]) 
			
			```
		displayFolder: _medidas_2
		lineageTag: 42333873-7464-4cbb-a175-96c232591efc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure l_km_12m_mitjana = ```
			
			
			VAR L =
			    CALCULATE(
			    AVERAGE(fact_inventari_xarxa_distribucion[xarxa]),
			    DATESINPERIOD(
			        'dim_calendario'[Date],
			        MAX('dim_calendario'[Date]),
			        -12,
			        MONTH
			    )
			) 
			RETURN
			    DIVIDE(L, 1000)
			```
		displayFolder: _medidas_2
		lineageTag: ea72ced7-49b5-4576-bf6a-722dade6303a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure l_km_mensual =
			
			VAR L = SUM(fact_inventari_xarxa_distribucion[xarxa])
			RETURN
			    DIVIDE(L, 1000)
		displayFolder: _medidas_2
		lineageTag: 9ac0b385-e8bc-40f7-9bbe-77005439c4c2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ANR_l_esc_dia = ```
			[anr_acum_12m] /[escomeses_12m_mitjana]/365*1000
			
			```
		displayFolder: _medidas_2
		lineageTag: f8e5e9a0-479d-4e58-bc42-3e5f8e16358b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ANR_l_subm_dia = ```
			[anr_acum_12m] /[subministraments_12m_mitjana]/365*1000
			
			```
		displayFolder: _medidas_2
		lineageTag: 1e024d7c-0645-4bc0-9570-c412449875de

	measure ANR_m3_km_dia = ```
			[anr_acum_12m] /[l_km_12m_mitjana]/365
			
			```
		displayFolder: _medidas_2
		lineageTag: 82b87267-a640-4b09-9de5-0309f22184a3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure l_km_ytd = ```
			
			CALCULATE(
			    SUM(fact_inventari_xarxa_distribucion[xarxa]),
			     DATESYTD(
			        'dim_calendario'[Date]
			    )
			)/1000
			
			
			```
		displayFolder: _medidas_2
		lineageTag: 15bd9e8e-0814-4cde-9ad9-bb012757b6bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fecha
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: dc357952-415c-45f0-8a6c-b03e55b17232
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column xarxa
		dataType: double
		formatString: #,0.00
		lineageTag: 583c8eac-7578-40e4-88c1-1b11f6b07286
		summarizeBy: sum
		sourceColumn: xarxa

		annotation SummarizationSetBy = Automatic

	column escomeses
		dataType: double
		lineageTag: 96c4993e-478b-4192-b222-432fe4758673
		summarizeBy: sum
		sourceColumn: escomeses

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column subministraments
		dataType: double
		lineageTag: 13ff4302-7961-4e1a-af86-f510cea67cf6
		summarizeBy: sum
		sourceColumn: subministraments

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gerencia_fecha
		dataType: string
		lineageTag: f69a3172-7cd1-4e1e-8781-8872fe0acab1
		summarizeBy: none
		sourceColumn: gerencia_fecha

		annotation SummarizationSetBy = Automatic

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: 4d50e330-dd67-4e40-a86d-e2d08297f028
		summarizeBy: none
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

	partition fact_inventari_xarxa_distribucion = m
		mode: import
		queryGroup: Hechos
		source = ```
				let
				    //==========================================================
				    // Origen
				    //==========================================================
				    Origen =
				        GoogleSheets.Contents(
				            #"Indicadors ANR 2026"
				        ),
				
				    Datos =
				        Origen{[name="Inventari xarxa", ItemKind="Table"]}[Data],
				
				    Tabla =
				        Table.SelectColumns(
				            Table.FirstN(
				                Table.Skip(
				                    Table.RemoveColumns(Datos, {"Column1"}),
				                    2
				                ),
				                182
				            ),
				            List.FirstN(
				                Table.ColumnNames(
				                    Table.FirstN(
				                        Table.Skip(
				                            Table.RemoveColumns(Datos, {"Column1"}),
				                            2
				                        ),
				                        164
				                    )
				                ),
				                19
				            )
				        ),
				
				    //==========================================================
				    // Cabeceras
				    //==========================================================
				    Sectores =
				        List.Transform(
				            Record.ToList(Tabla{0}),
				            each try Text.Trim(Text.From(_)) otherwise ""
				        ),
				
				    Zonas =
				        List.Transform(
				            Record.ToList(Tabla{1}),
				            each try Text.Trim(Text.From(_)) otherwise ""
				        ),
				
				    SectoresRellenos =
				        List.Accumulate(
				            Sectores,
				            {},
				            (estado, actual) =>
				                estado &
				                {
				                    if actual = "" then
				                        if List.Count(estado) = 0 then ""
				                        else List.Last(estado)
				                    else
				                        actual
				                }
				        ),
				
				    NuevosNombres =
				        List.Transform(
				            List.Positions(SectoresRellenos),
				            (i) =>
				                if i = 0 then
				                    "Mes"
				                else if Zonas{i} = "" then
				                    SectoresRellenos{i}
				                else
				                    SectoresRellenos{i} & " - " & Zonas{i}
				        ),
				
				    //==========================================================
				    // Transformación
				    //==========================================================
				    Renombrada =
				        Table.RenameColumns(
				            Table.Skip(Tabla, 2),
				            List.Zip({Table.ColumnNames(Tabla), NuevosNombres}),
				            MissingField.Ignore
				        ),
				
				    Despivotada =
				        Table.UnpivotOtherColumns(
				            Renombrada,
				            {"Mes"},
				            "kpi",
				            "valor"
				        ),
				
				    Split =
				        Table.SplitColumn(
				            Despivotada,
				            "kpi",
				            Splitter.SplitTextByDelimiter(" - ", QuoteStyle.Csv),
				            {"kpi", "gerencia"}
				        ),
				
				    Resultado =
				        Table.TransformColumns(
				            Split,
				            {
				                {"kpi", Text.Trim, type text},
				                {"gerencia", Text.Trim, type text}
				            }
				        ),
				
				    //==========================================================
				    // Mapeo de KPIs
				    //==========================================================
				    MapaKPI =
				        [
				            #"XARXA DISTRIBUCIÓ (DM Xarxes)" = "xarxa",
				            #"SUBMINISTRAMENTS CONTROLATS (DM Xarxes)" = "subministraments",
				            #"RAMALS CONTROLATS (DM Xarxes)" = "escomeses"
				        ],
				
				    KPIMapeado =
				        Table.TransformColumns(
				            Resultado,
				            {
				                {
				                    "kpi",
				                    each Record.FieldOrDefault(MapaKPI, _, _),
				                    type text
				                }
				            }
				        ),
				
				    //==========================================================
				    // Limpieza
				    //==========================================================
				    ValorLimpio =
				        Table.TransformColumns(
				            KPIMapeado,
				            {
				                {
				                    "valor",
				                    each
				                        if _ = null or _ = "" then
				                            0
				                        else
				                            Number.From(_),
				                    type number
				                }
				            }
				        ),
				
				    Pivotado =
				        Table.Pivot(
				            ValorLimpio,
				            List.Distinct(ValorLimpio[kpi]),
				            "kpi",
				            "valor",
				            List.Sum
				        ),
				    #"Valor reemplazado" = Table.ReplaceValue(Pivotado,"BCN Nord","Barcelona Nord",Replacer.ReplaceText,{"gerencia"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","BCN Sud","Barcelona Sud",Replacer.ReplaceText,{"gerencia"}),
				    #"Mes convertido" =
				        Table.TransformColumns(
				            #"Valor reemplazado1",
				            {
				                {
				                    "Mes",
				                    each 
				                        #date(
				                            Number.FromText(Text.Start(Text.From(_),4)),
				                            Number.FromText(Text.End(Text.From(_),2)),
				                            1
				                        ),
				                    type date
				                }
				            }
				        ),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Mes convertido",{{"Mes", "fecha"}}),
				    #"Columna combinada insertada" = Table.AddColumn(#"Columnas con nombre cambiado", "gerencia_fecha", each Text.Combine({[gerencia], "-", Text.From([fecha], "es-ES"), " "}), type text),
				    #"Filas filtradas" = Table.SelectRows(#"Columna combinada insertada", each ([fecha] = #date(2025, 1, 1) or [fecha] = #date(2025, 2, 1) or [fecha] = #date(2025, 3, 1) or [fecha] = #date(2025, 4, 1) or [fecha] = #date(2025, 5, 1) or [fecha] = #date(2025, 6, 1) or [fecha] = #date(2025, 7, 1) or [fecha] = #date(2025, 8, 1) or [fecha] = #date(2025, 9, 1) or [fecha] = #date(2025, 10, 1) or [fecha] = #date(2025, 11, 1) or [fecha] = #date(2025, 12, 1) or [fecha] = #date(2026, 1, 1) or [fecha] = #date(2026, 2, 1) or [fecha] = #date(2026, 3, 1) or [fecha] = #date(2026, 4, 1) or [fecha] = #date(2026, 5, 1) or [fecha] = #date(2026, 6, 1) or [fecha] = #date(2026, 7, 1) or [fecha] = #date(2026, 8, 1) or [fecha] = #date(2026, 9, 1) or [fecha] = #date(2026, 10, 1) or [fecha] = #date(2026, 11, 1) or [fecha] = #date(2026, 12, 1))),
				    #"Consultas combinadas" = Table.NestedJoin(#"Filas filtradas", {"gerencia"}, dim_gerencia, {"gerencia"}, "dim_gerencia", JoinKind.LeftOuter),
				    #"Se expandió dim_gerencia" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_gerencia", {"gerencia_id"}, {"gerencia_id"}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Se expandió dim_gerencia",{"gerencia"}),
				    #"Columna dividida" = Table.TransformColumns(#"Columnas quitadas", {{"xarxa", each _ / 1000, type number}})
				in
				    #"Columna dividida"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

