table fact_estadístiques_comp
	lineageTag: 1f4a1c1d-23ce-46a9-8d90-13b531f6f6c1

	column 'Agrupació Canvi'
		dataType: string
		lineageTag: 808909f3-dab4-4690-84ad-28d1d43651cb
		summarizeBy: none
		sourceColumn: Agrupació Canvi

		annotation SummarizationSetBy = Automatic

	column 'Agrupació edat'
		dataType: string
		lineageTag: 403521a0-1009-496c-abca-71e69c6fef16
		summarizeBy: none
		sourceColumn: Agrupació edat

		annotation SummarizationSetBy = Automatic

	column 'Tip Submin'
		dataType: string
		lineageTag: 9030c887-1d4e-4d30-83ce-f344d1bb80fc
		summarizeBy: none
		sourceColumn: Tip Submin

		annotation SummarizationSetBy = Automatic

	column 'Grup DN'
		dataType: string
		lineageTag: c9b226b5-14c8-4852-8a45-b0a453667835
		summarizeBy: none
		sourceColumn: Grup DN

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: int64
		formatString: 0
		lineageTag: 463abbee-bd4d-4516-bcf7-c702d6560456
		summarizeBy: sum
		sourceColumn: Total

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column DESC_CODI
		dataType: string
		lineageTag: 1b063bfc-3023-4cdf-b8e9-e9b2ecf4290e
		summarizeBy: none
		sourceColumn: DESC_CODI

		annotation SummarizationSetBy = Automatic

	column 'Nom executor'
		dataType: string
		lineageTag: ceb74094-5fdd-4a9c-a501-ed373e41593c
		summarizeBy: none
		sourceColumn: Nom executor

		annotation SummarizationSetBy = Automatic

	column 'Zona Operacions'
		dataType: string
		lineageTag: 7233614e-6e1f-4a2a-bfac-6d9de61e66a9
		summarizeBy: none
		sourceColumn: Zona Operacions

		annotation SummarizationSetBy = Automatic

	column Estratègics
		dataType: string
		lineageTag: 758892d5-ba00-4125-8e34-f2ed70ec5d65
		summarizeBy: none
		sourceColumn: Estratègics

		annotation SummarizationSetBy = Automatic

	column DIAM_COMP
		dataType: string
		lineageTag: 9aac5d6d-9cfa-42aa-a2ef-9ef44bc6a3ab
		summarizeBy: none
		sourceColumn: DIAM_COMP

		annotation SummarizationSetBy = Automatic

	column QL_COMPT_NOU
		dataType: string
		lineageTag: 61c8b79f-df90-432f-9648-d951b583c2ec
		summarizeBy: none
		sourceColumn: QL_COMPT_NOU

		annotation SummarizationSetBy = Automatic

	column 'Agrupació edat GA'
		dataType: string
		lineageTag: a4a6b68e-82ef-4e41-b815-cab7ce2504b7
		summarizeBy: none
		sourceColumn: Agrupació edat GA

		annotation SummarizationSetBy = Automatic

	column 'Número Mes'
		dataType: string
		lineageTag: 72d5c6e5-542c-47a3-b5f0-a9dd8e5d846f
		summarizeBy: none
		sourceColumn: Número Mes

		annotation SummarizationSetBy = Automatic

	column 'Tipus Executor'
		dataType: string
		lineageTag: 74babe91-d4ce-4af3-b0a1-d19f298e5399
		summarizeBy: none
		sourceColumn: Tipus Executor

		annotation SummarizationSetBy = Automatic

	column 'Codi mes'
		dataType: string
		lineageTag: 6757ec2d-d3d0-417f-a21f-f9bbc4e58f7b
		summarizeBy: none
		sourceColumn: Codi mes

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 29a42bfc-1365-45b5-919e-eed0d7895a79
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_estadístiques_comp = m
		mode: import
		source = ```
				let
				  Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vSBdujYtm-k6b1sHDL1XjoEupA6bWpiO7est-_tshOR30XuF361C6fvUabG2i616w/pub?gid=524487380&single=true&output=csv"),[Delimiter=",", Columns=48, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"Agrupació Canvi", "Agrupació edat", "Tip Submin", "Grup DN", "﻿Total", "DESC_CODI", "Nom executor", "Zona Operacions", "Estratègics", "DIAM_COMP", "QL_COMPT_NOU", "Agrupació edat GA", "Número Mes", "Tipus Executor", "Codi mes"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Otras columnas quitadas", "fecha", each 
				let
				    txt0 = [Codi mes],
				
				    // pasar a minúsculas
				    txt1 = Text.Lower(txt0),
				
				    // quitar puntos
				    txt2 = Text.Replace(txt1, ".", ""),
				
				    // limpiar espacios múltiples
				    txt3 = Text.Trim(Text.Replace(txt2, "  ", " ")),
				
				    // asegurar separador consistente
				    txt4 = Text.Replace(txt3, " - ", "-"),
				    txt5 = Text.Replace(txt4, " -", "-"),
				    txt6 = Text.Replace(txt5, "- ", "-"),
				
				    // separar número de mes
				    mesNumTxt = Text.BeforeDelimiter(txt6, "-"),
				    mesNum = Number.FromText(Text.Trim(mesNumTxt)),
				
				    // año actual
				    anio = Date.Year(DateTime.LocalNow()),
				
				    // construir fecha
				    Fecha = #date(anio, mesNum, 1)
				in
				    Fecha)
				in
				    #"Personalizada agregada"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

