table fact_vol_fraud
	lineageTag: e2ad68d9-a4d3-46ad-933c-209961daff47

	column Tipologia
		dataType: string
		lineageTag: f16f137e-d9e2-40e0-8581-1c96fa374e3c
		summarizeBy: none
		sourceColumn: Tipologia

		annotation SummarizationSetBy = Automatic

	column 'Polissa Subm'
		dataType: string
		lineageTag: de48eadd-abe8-47a8-a357-01d541666b95
		summarizeBy: none
		sourceColumn: Polissa Subm

		annotation SummarizationSetBy = Automatic

	column 'Data Fi Execucio Final'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: aa3287db-8f5a-496b-b248-3b7079d1c615
		summarizeBy: none
		sourceColumn: Data Fi Execucio Final

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Codi Ope'
		dataType: string
		lineageTag: d0966cba-14b2-47d2-a041-5b92dcd1d2d4
		summarizeBy: none
		sourceColumn: Codi Ope

		annotation SummarizationSetBy = Automatic

	column 'Tip Habit Subm'
		dataType: string
		lineageTag: f865146c-8cd1-45b9-bbb5-7bc5378dd6d6
		summarizeBy: none
		sourceColumn: Tip Habit Subm

		annotation SummarizationSetBy = Automatic

	column 'Us Aigua Subm'
		dataType: string
		lineageTag: 4f7956b5-643c-45d4-b874-a1f39a642314
		summarizeBy: none
		sourceColumn: Us Aigua Subm

		annotation SummarizationSetBy = Automatic

	column 'Sector Cial'
		dataType: int64
		formatString: 0
		lineageTag: 11aeb0da-0305-4727-8c49-36d54206a73e
		summarizeBy: sum
		sourceColumn: Sector Cial

		annotation SummarizationSetBy = Automatic

	column 'Imp Cobrat Frau Total'
		dataType: double
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		lineageTag: b08ac3f4-7360-4f1c-821f-f51cd640d4e5
		summarizeBy: sum
		sourceColumn: Imp Cobrat Frau Total

		annotation SummarizationSetBy = Automatic

	column 'Volumen Total'
		dataType: double
		lineageTag: d93fd849-68c9-44ab-bb23-6a4640f6ade6
		summarizeBy: sum
		sourceColumn: Volumen Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: 742e212f-6b18-4b72-88cf-647da8fff0a1
		summarizeBy: sum
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

	partition fact_vol_fraud = m
		mode: import
		queryGroup: Hechos
		source = ```
				let
				  Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1w51CCzDW84rqW3XTHaf1JPJYDKfVQuy2vzKhTL01odo/edit?pli=1&gid=24661993#gid=24661993"),
				   #"Navegación" = Origen{[name = "Sheet1", ItemKind = "Table"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Navegación, [PromoteAllScalars=true]),
				     #"Nombres en título" =
				        Table.TransformColumnNames(
				            #"Encabezados promovidos",
				            each Text.Proper(Text.Replace(Text.Lower(_), "_", " "))
				        ),
				
				    #"Tipo cambiado" =
				        Table.TransformColumnTypes(
				            #"Nombres en título",
				            {
				                {"Tipologia", type text},
				                {"Gerencia", type text},
				                {"Data Fi Execucio Final", type date},
				                {"Codi Ope", type text},
				                {"Tip Habit Subm", type text},
				                {"Us Aigua Subm", type text},
				                {"Sector Cial", Int64.Type},
				                {"Imp Cobrat Frau Total", type number},
				                {"Volumen Total", type number}
				            }
				        ),
				
				    #"Valores en título" =
				        Table.TransformColumns(
				            #"Tipo cambiado",
				            {
				                {"Tipologia", Text.Proper, type text},
				                {"Gerencia", Text.Proper, type text},
				                {"Codi Ope", Text.Proper, type text},
				                {"Tip Habit Subm", Text.Proper, type text},
				                {"Us Aigua Subm", Text.Proper, type text}
				            }
				        ),
				    
				    #"Consultas combinadas" = Table.NestedJoin(#"Valores en título", {"Gerencia"}, dim_gerencia, {"gerencia"}, "dim_gerencia", JoinKind.LeftOuter),
				    #"Se expandió dim_gerencia" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_gerencia", {"gerencia_id"}, {"gerencia_id"}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Se expandió dim_gerencia",{"Gerencia"})
				in
				    #"Columnas quitadas"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

