table fact_aigua_no_registrada_12m
	lineageTag: 17944b20-54dd-4407-93fe-f02962a5c271

	column sector
		dataType: int64
		formatString: 0
		lineageTag: 8c220462-cee0-4513-a8ec-e9fd9b50291b
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column gerencia
		dataType: string
		lineageTag: ee55c4f1-ef0c-4b2f-bf6a-052aa6ba8042
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	column sectors
		dataType: string
		lineageTag: dcfd39b2-4838-4606-9d9b-67d28523f5b0
		summarizeBy: none
		sourceColumn: sectors

		annotation SummarizationSetBy = Automatic

	column valor
		dataType: int64
		formatString: 0
		lineageTag: d0298248-6764-4c55-90cc-8575e6a29e46
		summarizeBy: sum
		sourceColumn: valor

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3ed4ab1e-295d-4725-8716-9260c30d9b2a
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column pis_pressio
		dataType: string
		lineageTag: 1f84601b-6ab1-431f-ae08-b23d4b3b0418
		summarizeBy: none
		sourceColumn: pis_pressio

		annotation SummarizationSetBy = Automatic

	partition fact_aigua_no_registrada_12m = m
		mode: import
		source = ```
				let
				    Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vQu04YqiUjROdeKjkF1OKAb2UI0cIt8n44NDzq3nAdSvDc2p0zBvWngL_DNulEpHw/pub?gid=1960240863&single=true&output=csv"),[Delimiter=",", Columns=48, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Filas superiores quitadas" = Table.Skip(Origen,2),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Filas superiores quitadas", [PromoteAllScalars=true]),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Encabezados promovidos",{""}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas", each ([Nº] <> "")),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Filas filtradas",{{"Nº", Int64.Type}, {"Gerència", type text}, {"Pis Pressió", type text}, {"Sectors", type text},  {"de gen.-21", Int64.Type}, {"de febr.-21", Int64.Type}, {"de març-21", Int64.Type}, {"d’abr.-21", Int64.Type}, {"de maig-21", Int64.Type}, {"de juny-21", Int64.Type}, {"de jul.-21", Int64.Type}, {"d’ag.-21", Int64.Type}, {"de set.-21", Int64.Type}, {"d’oct.-21", Int64.Type}, {"de nov.-21", Int64.Type}, {"de des.-21", Int64.Type}, {"de gen.-22", Int64.Type}, {"de febr.-22", Int64.Type}, {"de març-22", Int64.Type}, {"d’abr.-22", Int64.Type}, {"de maig-22", Int64.Type}, {"de juny-22", Int64.Type}, {"de jul.-22", Int64.Type}, {"d’ag.-22", Int64.Type}, {"de set.-22", Int64.Type}, {"d’oct.-22", Int64.Type}, {"de nov.-22", Int64.Type}, {"de des.-22", Int64.Type}, {"de gen.-23", Int64.Type}, {"de febr.-23", Int64.Type}, {"de març-23", Int64.Type}, {"d’abr.-23", Int64.Type}, {"de maig-23", Int64.Type}, {"de juny-23", Int64.Type}, {"de jul.-23", Int64.Type}, {"d’ag.-23", Int64.Type}, {"de set.-23", Int64.Type}, {"d’oct.-23", Int64.Type}, {"de nov.-23", Int64.Type}, {"de des.-23", Int64.Type}, {"de gen.-24", Int64.Type}, {"de febr.-24", Int64.Type}, {"de març-24", Int64.Type}, {"d’abr.-24", Int64.Type}, {"de maig-24", Int64.Type}, {"de juny-24", Int64.Type}, {"de jul.-24", Int64.Type}}),
				    #"Columna de anulación de dinamización" = Table.UnpivotOtherColumns(#"Tipo cambiado", {"Nº", "Gerència", "Pis Pressió", "Sectors"}, "Atributo", "Valor"),
				    #"Personalizada agregada" = Table.AddColumn(#"Columna de anulación de dinamización", "fecha", each let
				        txt0  = [Atributo],
				        txt1  = Text.Lower(txt0),
				        txt2  = Text.Replace(Text.Replace(Text.Replace(txt1,"de ",""),"d’",""),".",""),
				        mesTxt = Text.BeforeDelimiter(txt2,"-"),
				        anioTxt = Text.AfterDelimiter(txt2,"-"),
				        anio = 2000 + Number.FromText(anioTxt),
				        mes = 
				            if mesTxt = "gen"  then 1 else
				            if mesTxt = "febr" then 2 else
				            if mesTxt = "març" then 3 else
				            if mesTxt = "abr"  then 4 else
				            if mesTxt = "maig" then 5 else
				            if mesTxt = "juny" then 6 else
				            if mesTxt = "jul"  then 7 else
				            if mesTxt = "ag"   then 8 else
				            if mesTxt = "set"  then 9 else
				            if mesTxt = "oct"  then 10 else
				            if mesTxt = "nov"  then 11 else
				            if mesTxt = "des"  then 12 else
				            null
				        in
				            #date(anio, mes, 1)
				    ),
				    // 🔥 NORMALIZAR NOMBRES DE COLUMNAS
				    #"Columnas normalizadas" = 
				        Table.TransformColumnNames(#"Personalizada agregada", 
				            each Text.Replace(Text.Lower(_), " ", "_")),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas normalizadas",{{"nº", "n"}, {"gerència", "gerencia"}, {"pis_pressió", "pis_pressio"}}),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Columnas con nombre cambiado",{"atributo"}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columnas quitadas1",{{"n", "sector"}})
				in
				    #"Columnas con nombre cambiado1"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

