table fact_consum_no_control
	lineageTag: 46b0711c-d59e-4076-ba66-f5f91b20b68c

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: e1e48717-b4fc-431e-875a-7259bdfb9ee0
		summarizeBy: none
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: e9f8b962-bbc8-4e33-ac52-707388ba9535
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: fd987926-1f39-4a08-a417-338a1a238440
			defaultHierarchy: LocalDateTable_29c03b30-cb8b-4dce-8c7f-ee0bb554b41d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column tipo_consum
		dataType: string
		lineageTag: 36c6155a-21ac-4199-92bb-1fb5be1a72ab
		summarizeBy: none
		sourceColumn: tipo_consum

		annotation SummarizationSetBy = Automatic

	column consumo
		dataType: int64
		formatString: 0
		lineageTag: d724d681-3826-4587-bf2e-7e9c8b998905
		summarizeBy: sum
		sourceColumn: consumo

		annotation SummarizationSetBy = Automatic

	partition fact_consum_no_control = m
		mode: import
		queryGroup: Hechos
		source =
				let
				    Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1ZffEmnNoWOUZV2BWTDYGZTjcNVbZ07il0J7N43DN_IU/edit?gid=372424086#gid=372424086"),
				    Tabla = Origen{[name="Consums No Controlats", ItemKind="Table"]}[Data],
				    Limpia = Table.SelectRows(
				        Table.RemoveColumns(Tabla, {"Column1","Column76"}),
				        each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))
				    ),
				
				    Rango = Table.Range(Limpia,0,15),
				
				    Categoria = Table.FillDown(
				        Table.AddColumn(
				            Rango,
				            "categoria_org",
				            each
				                if [Column2] <> null and Text.StartsWith(Text.Trim(Text.From([Column2])),"Consum")
				                then [Column2]
				                else null
				        ),
				        {"categoria_org"}
				    ),
				
				    Gerencia = Table.AddColumn(
				        Table.RemoveRows(Categoria,7,1),
				        "gerencia",
				        each
				            if [Column2] <> null
				                and Text.Trim(Text.From([Column2]))<>""
				                and not Text.StartsWith(Text.Trim(Text.From([Column2])),"Consum")
				                and not Text.StartsWith(Text.Trim(Text.From([Column2])),"Venda")
				            then [Column2]
				            else if ([Column2]=null or Text.Trim(Text.From([Column2]))="")
				                and [Column3]<>null
				                and Text.Trim(Text.From([Column3]))<>""
				            then [Column3]
				            else null
				    ),
				
				    SubCategoria = Table.AddColumn(
				        Gerencia,
				        "subcategoria",
				        each
				            if [Column2]<>null
				                and Text.Trim(Text.From([Column2]))<>""
				                and not Text.StartsWith(Text.Trim(Text.From([Column2])),"Consum")
				            then [Column3]
				            else null
				    ),
				
				    Encabezados = Table.PromoteHeaders(
				        Table.Skip(
				            Table.RemoveColumns(SubCategoria,{"Column2","Column3"}),
				            1
				        ),
				        [PromoteAllScalars=true]
				    ),
				
				    Renombradas = Table.RenameColumns(
				        Encabezados,
				        {
				            {"Consum No Controlat Baixa","categoria_org"},
				            {"Column74","gerencia"},
				            {"Column75","subcategoria"}
				        }
				    ),
				
				    Datos = Table.RemoveRows(Renombradas,5,2),
				
				    Unpivot = Table.UnpivotOtherColumns(
				        Datos,
				        {"categoria_org","gerencia","subcategoria"},
				        "Atributo",
				        "Valor"
				    ),
				
				    Transformada = Table.TransformColumnTypes(
				        Table.ReplaceValue(Unpivot,"","0",Replacer.ReplaceValue,{"Valor"}),
				        {{"Valor", Int64.Type}}
				    ),
				
				    Fecha = Table.AddColumn(
				        Transformada,
				        "Fecha",
				        each #date(
				            Number.From(Text.Start(Text.From([Atributo]),4)),
				            Number.From(Text.End(Text.From([Atributo]),2)),
				            1
				        ),
				        type date
				    ),
				
				    FinalTexto = Table.TransformColumns(
				        Table.ReplaceValue(
				            Table.RemoveColumns(Fecha,{"Atributo"}),
				            null,
				            "Baixa",
				            Replacer.ReplaceValue,
				            {"subcategoria"}
				        ),
				        {
				            {"gerencia", each Text.Proper(Text.Trim(Text.Clean(_))), type text}
				        }
				    ),
				
				    JoinGerencia = Table.ExpandTableColumn(
				        Table.NestedJoin(
				            FinalTexto,
				            {"gerencia"},
				            dim_gerencia,
				            {"gerencia"},
				            "dim_gerencia",
				            JoinKind.LeftOuter
				        ),
				        "dim_gerencia",
				        {"gerencia_id"},
				        {"gerencia_id"}
				    ),
				
				    Resultado = Table.ReorderColumns(
				        Table.RenameColumns(
				            Table.RemoveColumns(
				                JoinGerencia,
				                {"gerencia","categoria_org"}
				            ),
				            {{"subcategoria","tipo_consum"},{"Valor","consumo"}}
				        ),
				        {"gerencia_id","Fecha","tipo_consum","consumo"}
				    ),
				    #"Filas filtradas" = Table.SelectRows(Resultado, each [Fecha] > #date(2021, 12, 31))
				in
				    #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

