table fact_rend_anr_arterias
	lineageTag: 2bd7fae2-b1ab-462b-971d-88c228ce16be

	column arteria
		dataType: string
		lineageTag: 98134d12-6770-4fc3-b461-9aeba5a05fb7
		summarizeBy: none
		sourceColumn: arteria

		annotation SummarizationSetBy = Automatic

	column rendiment
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: bd43ac57-a12e-4b2b-a8c5-6bf97b7f833a
		summarizeBy: sum
		sourceColumn: rendiment

		annotation SummarizationSetBy = Automatic

	column anr_m3
		dataType: int64
		formatString: #,0
		lineageTag: 442dd6c9-5363-4fb8-9f3b-982a0bedb571
		summarizeBy: sum
		sourceColumn: anr_m3

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 91a4dd3c-3987-4003-a4de-cae32169760e
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column sortit_m3
		dataType: int64
		formatString: #,0
		lineageTag: 7e56a2f3-4d4e-4a2d-bd56-0505b484e534
		summarizeBy: sum
		sourceColumn: sortit_m3

		annotation SummarizationSetBy = Automatic

	column entrat_m3
		dataType: int64
		formatString: #,0
		lineageTag: 9a1b8714-7c86-46f9-91ed-37ab0fb3bf26
		summarizeBy: sum
		sourceColumn: entrat_m3

		annotation SummarizationSetBy = Automatic

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: 79214a7c-261c-4549-ad95-14a5b2c9c477
		summarizeBy: sum
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

	partition fact_rend_anr_arterias = m
		mode: import
		queryGroup: Hechos
		source =
				let
				    Union =
				        Table.Combine({
				            fact_rend_anr_arterias_llobregadsub_mensual,
				            fact_rend_anr_arterias_llobregadnord_mensual,
				            fact_rend_anr_arterias_bcn_sud_mensual,
				            fact_rend_anr_arterias_bcn_nord_mensual,
				            fact_rend_anr_arterias_besos_mensual,
				            fact_rend_anr_arterias_multi_dz_mensual
				        }),
				
				    Gerencias =
				        Table.ReplaceValue(
				            Table.ReplaceValue(
				                Union,
				                "Bcn", "Barcelona",
				                Replacer.ReplaceText, {"gerencia"}
				            ),
				            "Besos", "Besòs",
				            Replacer.ReplaceText, {"gerencia"}
				        ),
				
				    Result =
				        Table.Sort(
				            Gerencias,
				            {
				                {"gerencia", Order.Ascending},
				                {"arteria", Order.Ascending},
				                {"fecha", Order.Ascending}
				            }
				        ),
				    #"Texto limpio" = Table.TransformColumns(Result,{{"gerencia", Text.Clean, type text}}),
				    #"Texto recortado" = Table.TransformColumns(#"Texto limpio",{{"gerencia", Text.Trim, type text}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Texto recortado", {"gerencia"}, dim_gerencia, {"gerencia"}, "dim_gerencia", JoinKind.LeftOuter),
				    #"Se expandió dim_gerencia" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_gerencia", {"gerencia_id"}, {"gerencia_id"}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Se expandió dim_gerencia",{"gerencia"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

