table fact_aigua_no_registrada_12m
	lineageTag: 17944b20-54dd-4407-93fe-f02962a5c271

	column sector
		dataType: string
		lineageTag: 8c220462-cee0-4513-a8ec-e9fd9b50291b
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column gerencia
		dataType: string
		lineageTag: ee55c4f1-ef0c-4b2f-bf6a-052aa6ba8042
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	column sectors
		dataType: string
		lineageTag: dcfd39b2-4838-4606-9d9b-67d28523f5b0
		summarizeBy: none
		sourceColumn: sectors

		annotation SummarizationSetBy = Automatic

	column valor
		dataType: int64
		formatString: 0
		lineageTag: d0298248-6764-4c55-90cc-8575e6a29e46
		summarizeBy: sum
		sourceColumn: valor

		annotation SummarizationSetBy = Automatic

	column pis_pressio
		dataType: string
		lineageTag: 1f84601b-6ab1-431f-ae08-b23d4b3b0418
		summarizeBy: none
		sourceColumn: pis_pressio

		annotation SummarizationSetBy = Automatic

	column fecha_texto
		dataType: string
		lineageTag: e0c7751a-49b0-4b07-9f8e-18bc61df241e
		summarizeBy: none
		sourceColumn: fecha_texto

		annotation SummarizationSetBy = Automatic

	partition fact_aigua_no_registrada_12m = m
		mode: import
		source =
				let
				    Origen =
				        GoogleSheets.Contents(
				            "https://docs.google.com/spreadsheets/d/1ZffEmnNoWOUZV2BWTDYGZTjcNVbZ07il0J7N43DN_IU/edit?gid=1960240863#gid=1960240863"
				        ),
				
				    Datos = Origen{[name="Aigua No Registrada 12 mesos", ItemKind="Table"]}[Data],
				
				    Datos2 = Table.PromoteHeaders(Table.Skip(Datos, 2), [PromoteAllScalars = true]),
				    Datos3 = Table.RemoveColumns(Datos2, List.Select(Table.ColumnNames(Datos2), each _ = "")),
				    Datos4 = Table.SelectRows(Datos3, each ([Nº] <> "")),
				
				    ColumnasFijas = {"Nº", "Gerència", "Pis Pressió", "Sectors"},
				    ColumnasMeses = List.Difference(Table.ColumnNames(Datos4), ColumnasFijas),
				
				    Datos5 =
				        Table.TransformColumnTypes(
				            Datos4,
				            List.Transform(ColumnasMeses, each {_, Int64.Type})
				        ),
				
				    Datos6 =
				        Table.UnpivotOtherColumns(
				            Datos5,
				            ColumnasFijas,
				            "atributo",
				            "valor"
				        ),
				
				    // 🔥 Reemplazar errores en "valor" por 0
				    Datos7 =
				        Table.ReplaceErrorValues(
				            Datos6,
				            {{"valor", 0}}
				        ),
				
				    Datos8 =
				        Table.TransformColumnNames(
				            Datos7,
				            each Text.Replace(Text.Lower(_), " ", "_")
				        ),
				
				    Resultado =
				        Table.RenameColumns(
				            Datos8,
				            {
				                {"nº", "sector"},
				                {"gerència", "gerencia"},
				                {"pis_pressió", "pis_pressio"},
				                {"atributo", "fecha_texto"}
				            }
				        )
				in
				    Resultado

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

