table fact_rend_anr_arterias_12m
	lineageTag: 7cd6cc25-6fbf-4d46-923e-fb970a910a51

	column gerencia
		dataType: string
		lineageTag: 2265c568-ee91-46d7-83f8-0929bb7b7352
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	column arteria
		dataType: string
		lineageTag: e94a6b88-aa05-4e81-b478-ef0983ab48b5
		summarizeBy: none
		sourceColumn: arteria

		annotation SummarizationSetBy = Automatic

	column rendiment
		dataType: double
		lineageTag: 648d7561-2404-4972-878d-de0bad338257
		summarizeBy: sum
		sourceColumn: rendiment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anr_m3
		dataType: int64
		formatString: 0
		lineageTag: 3c430bcd-06a3-4a5d-96d2-812e512e4e62
		summarizeBy: sum
		sourceColumn: anr_m3

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0100f778-3783-4ba5-9054-1b786f915143
		summarizeBy: none
		sourceColumn: fecha

		variation Variación
			isDefault
			relationship: 0f7fefc2-617e-41e5-89c7-aa354c9f351e
			defaultHierarchy: LocalDateTable_be0a4368-dc3b-44b4-91bc-f86d876d45a7.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column sortit_m3
		dataType: int64
		formatString: 0
		lineageTag: 00db6bc8-22f1-4462-ac6b-25939ef39d87
		summarizeBy: sum
		sourceColumn: sortit_m3

		annotation SummarizationSetBy = Automatic

	column entrat_m3
		dataType: int64
		formatString: 0
		lineageTag: 9170944a-a2cb-479f-bb45-3edbc440732d
		summarizeBy: sum
		sourceColumn: entrat_m3

		annotation SummarizationSetBy = Automatic

	partition fact_rend_anr_arterias_12m = m
		mode: import
		source =
				let
				    Union =
				        Table.Combine({
				            fact_rend_anr_arterias_llobregadsub_12m,
				            fact_rend_anr_arterias_llobregadnord_12m,
				            fact_rend_anr_arterias_bcn_sud_12m,
				            fact_rend_anr_arterias_bcn_nord_12m,
				            fact_rend_anr_arterias_besos_12m,
				            fact_rend_anr_arterias_multi_dz_12m
				        }),
				
				    Transformado =
				        Table.RenameColumns(
				            Table.ReplaceValue(
				                Table.ReplaceValue(
				                    Table.Sort(
				                        Union,
				                        {
				                            {"gerencia", Order.Ascending},
				                            {"arteria", Order.Ascending},
				                            {"date", Order.Ascending}
				                        }
				                    ),
				                    "Bcn", "Barcelona", Replacer.ReplaceText, {"gerencia"}
				                ),
				                "Besos", "Besòs", Replacer.ReplaceText, {"gerencia"}
				            ),
				            {{"date", "fecha"}}
				        ),
				    sinVacios =
				        Table.SelectRows(
				            Transformado,
				            each [sortit_m3] <> null
				        )
				in
				    sinVacios

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

