table fact_estadístiques_comp
	lineageTag: 1f4a1c1d-23ce-46a9-8d90-13b531f6f6c1

	column desc_codi
		dataType: string
		lineageTag: f61ef780-1d54-45b4-9758-c9cb85ac5e98
		summarizeBy: none
		sourceColumn: desc_codi

		annotation SummarizationSetBy = Automatic

	column estrategics
		dataType: string
		lineageTag: 3d92c1c4-24bb-4af3-ac54-95cb7fd664d5
		summarizeBy: none
		sourceColumn: estrategics

		annotation SummarizationSetBy = Automatic

	column diam_comp
		dataType: int64
		formatString: 0
		lineageTag: 382aabb6-9fb3-4f56-af89-1f0effb75e76
		summarizeBy: sum
		sourceColumn: diam_comp

		annotation SummarizationSetBy = Automatic

	column ql_compt_nou
		dataType: string
		lineageTag: c9fd050c-b96a-4e89-bbbc-d793a833c679
		summarizeBy: none
		sourceColumn: ql_compt_nou

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 29a42bfc-1365-45b5-919e-eed0d7895a79
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column agrupacio_canvi
		dataType: string
		lineageTag: b0511eea-808d-4784-b448-126d7a99d91d
		summarizeBy: none
		sourceColumn: agrupacio_canvi

		annotation SummarizationSetBy = Automatic

	column agrupacio_edat
		dataType: string
		lineageTag: 227db6a2-14d1-495d-bc8e-760e1f3c1bb6
		summarizeBy: none
		sourceColumn: agrupacio_edat

		annotation SummarizationSetBy = Automatic

	column tip_submin
		dataType: string
		lineageTag: f3913d25-81f7-4177-8369-b50e4e842c99
		summarizeBy: none
		sourceColumn: tip_submin

		annotation SummarizationSetBy = Automatic

	column grup_dn
		dataType: string
		lineageTag: 8299449b-ab15-44be-bc67-9e66acd183eb
		summarizeBy: none
		sourceColumn: grup_dn

		annotation SummarizationSetBy = Automatic

	column ﻿total
		dataType: int64
		lineageTag: 84ae67bf-0664-4175-9d95-bc4480675c2e
		summarizeBy: sum
		sourceColumn: ﻿total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nom_executor
		dataType: string
		lineageTag: 53cda4af-16ba-411c-a5c3-e45232861352
		summarizeBy: none
		sourceColumn: nom_executor

		annotation SummarizationSetBy = Automatic

	column gerencia
		dataType: string
		lineageTag: 731aa6c4-f23e-4ce4-a85e-49047b1ec42a
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	column agrupacio_edat_ga
		dataType: string
		lineageTag: 3ba52090-c2bc-466a-a515-37188d0475b7
		summarizeBy: none
		sourceColumn: agrupacio_edat_ga

		annotation SummarizationSetBy = Automatic

	column tipus_executor
		dataType: string
		lineageTag: 0a7d8276-b57a-4adc-b876-39a7948df10b
		summarizeBy: none
		sourceColumn: tipus_executor

		annotation SummarizationSetBy = Automatic

	partition fact_estadístiques_comp = m
		mode: import
		source =
				let
				    // Origen
				    Origen =
				        GoogleSheets.Contents(
				            "https://docs.google.com/spreadsheets/d/1iq1grQXRgfmpth57wCKCeJDOMoEJOXdaFIKPwqHidUo/edit?gid=1719815457#gid=1719815457"
				        ),
				    Datos = Origen{[name="Estadístiques comp", ItemKind="Table"]}[Data],
				
				    // Encabezados
				    Encabezados = Table.PromoteHeaders(Datos, [PromoteAllScalars = true]),
				
				    // Selección de columnas
				    Seleccion =
				        Table.SelectColumns(
				            Encabezados,
				            {
				                "Agrupació Canvi",
				                "Agrupació edat",
				                "Tip Submin",
				                "Grup DN",
				                "﻿Total",
				                "DESC_CODI",
				                "Nom executor",
				                "Zona Operacions",
				                "Estratègics",
				                "DIAM_COMP",
				                "QL_COMPT_NOU",
				                "Agrupació edat GA",
				                "Número Mes",
				                "Tipus Executor",
				                "Codi mes"
				            }
				        ),
				
				    // Tipos
				    Tipos =
				        Table.TransformColumnTypes(
				            Seleccion,
				            {
				                {"﻿Total", Int64.Type},
				                {"DIAM_COMP", Int64.Type},
				                {"Número Mes", Int64.Type}
				            }
				        ),
				
				    // Crear fecha (versión compacta)
				    ConFecha =
				        Table.AddColumn(
				            Tipos,
				            "fecha",
				            each
				                let
				                    raw = Text.Lower([Codi mes]),
				                    limpio =
				                        Text.Trim(
				                            Text.Replace(
				                                Text.Replace(
				                                    Text.Replace(
				                                        Text.Replace(raw, ".", ""),
				                                        "  ", " "
				                                    ),
				                                    " - ", "-"
				                                ),
				                                "- ", "-"
				                            )
				                        ),
				                    mes = Number.FromText(Text.BeforeDelimiter(limpio, "-")),
				                    anio = Date.Year(DateTime.LocalNow())
				                in
				                    #date(anio, mes, 1),
				            type date
				        ),
				
				    // Normalizar nombres
				    Normalizadas =
				        Table.TransformColumnNames(
				            ConFecha,
				            each Text.Replace(Text.Lower(_), " ", "_")
				        ),
				
				    // Quitar columnas
				    Quitadas =
				        Table.RemoveColumns(
				            Normalizadas,
				            {"número_mes", "codi_mes"}
				        ),
				
				    // Renombrados finales
				    Renombradas =
				        Table.RenameColumns(
				            Quitadas,
				            {
				                {"agrupació_edat", "agrupacio_edat"},
				                {"agrupació_canvi", "agrupacio_canvi"},
				                {"estratègics", "estrategics"},
				                {"agrupació_edat_ga", "agrupacio_edat_ga"},
				                {"zona_operacions", "gerencia"}
				            }
				        ),
				
				    // Formato título
				    FormatoTitulo =
				        Table.TransformColumns(
				            Renombradas,
				            {
				                {"nom_executor", Text.Proper, type text},
				                {"gerencia", Text.Proper, type text}
				            }
				        )
				in
				    FormatoTitulo

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

