table fact_anr_global_acum
	lineageTag: b9338bb5-df5a-4911-a628-9396a160ed6d

	column fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2b7d5a03-2f48-4464-89f0-e5f08091a2e7
		summarizeBy: none
		sourceColumn: fecha

		variation Variación
			isDefault
			relationship: 0ae69dd9-1ce9-4724-bbfe-d1c75b278c9f
			defaultHierarchy: LocalDateTable_c6561612-6700-474a-ba57-f229b5aeb539.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column lliurada_hm3
		dataType: double
		lineageTag: 6d8be2fe-60b2-4605-967d-02accf662a00
		summarizeBy: sum
		sourceColumn: lliurada_hm3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consumida_hm3
		dataType: double
		lineageTag: eb194b6a-43b4-4e5b-9e2f-09043282f9b5
		summarizeBy: sum
		sourceColumn: consumida_hm3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rth_global
		dataType: double
		lineageTag: ba7064ea-7fa5-4386-ae13-d12eb81498bd
		summarizeBy: sum
		sourceColumn: rth_global

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anr_global_hm3
		dataType: double
		lineageTag: 14c97829-8c1e-4769-bc6f-e4d6d4dbb556
		summarizeBy: sum
		sourceColumn: anr_global_hm3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_anr_global_acum = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vRS1zkWHKwzcm2ZLhnMstWbjgJtQC3DCBLdSY_mCFGtR3x8Z4xdlut8iUNJwB5KVQ/pub?gid=315911922&single=true&output=csv"),
				        [Delimiter = ",", Columns = 48, Encoding = 65001, QuoteStyle = QuoteStyle.None]
				    ),
				    Data =
				        Table.PromoteHeaders(
				            Table.SelectColumns(
				                Table.Range(Source, 20, 13),
				                {"Column1", "Column2", "Column3", "Column4", "Column5"}
				            ),
				            [PromoteAllScalars = true]
				        ),
				    Renamed =
				        Table.RenameColumns(Data,{{"Any", "fecha"}, {"Aigua Lliurada (hm3)", "lliurada_hm3"}, {"Aigua Consumida (hm3)", "consumida_hm3"}, {"RTH Global", "rth_global"}, {"ANR Global (hm3)", "anr_global_hm3"}}),
				    ReplaceDots =
				        Table.TransformColumns(
				            Renamed,
				            List.Transform(
				                List.RemoveItems(Table.ColumnNames(Renamed), {"date"}),
				                each {_, (x) => Text.Replace(x, ".", ","), type text}
				            )
				        ),
				    Result =
				        Table.TransformColumnTypes(
				            ReplaceDots,
				            {
				                {"fecha", type date},
				                {"lliurada_hm3", type number},
				                {"consumida_hm3", type number},
				                {"rth_global", type number},
				                {"anr_global_hm3", type number}
				            }
				        )
				in
				    Result

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

