table fact_volum_cons_lliur
	lineageTag: 8286f1c2-e36e-429d-aba8-f580f0f4bf51

	column fecha
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: c17f293e-3776-4b77-a78b-54d692980570
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column sector_id
		dataType: int64
		lineageTag: b64c3f90-11a5-4054-be24-92907a71ee32
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: bcc42484-0b2d-4d96-a481-399fcb7c5d0c
		summarizeBy: none
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = User

	column pis_pressio
		dataType: string
		lineageTag: 2d632057-c720-49a1-b2b0-e9e8076d247f
		summarizeBy: none
		sourceColumn: pis_pressio

		annotation SummarizationSetBy = Automatic

	column volum_consumit
		dataType: double
		formatString: #,0
		lineageTag: 220f85c0-2b50-4b82-8280-0ee02a713013
		summarizeBy: sum
		sourceColumn: volum_consumit

		annotation SummarizationSetBy = Automatic

	column volum_lliurat
		dataType: double
		formatString: #,0
		lineageTag: 8106c71b-5902-4bfb-9195-63a43868c216
		summarizeBy: sum
		sourceColumn: volum_lliurat

		annotation SummarizationSetBy = Automatic

	column gerencia
		dataType: string
		lineageTag: a0822bb5-03f6-418a-bbce-c4b83e13895f
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	column sector
		dataType: string
		lineageTag: 21c2b51a-0a88-4340-88c5-bd444e64c8b2
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	partition fact_volum_cons_lliur = m
		mode: import
		queryGroup: Hechos
		source =
				let
				    Union =
				        Table.Combine({
				            fact_volum_consumit,
				            fact_volum_lliurat}),
				    #"Columnas reordenadas" = Table.ReorderColumns(Union,{"fecha", "sector_id", "gerencia_id", "pis_pressio", "volum_consumit", "volum_lliurat"}),
				    // Limpiar datos
				    SinDuplicados = Table.Distinct(#"Columnas reordenadas"),
				    SinFilasVacias = Table.SelectRows(
				        SinDuplicados,
				        each List.NonNullCount(Record.FieldValues(_)) > 0
				    ),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(SinFilasVacias,{{"Sectors", "sector"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","Río","Rio",Replacer.ReplaceText,{"sector"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado",null,0,Replacer.ReplaceValue,{"volum_consumit"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1",null,0,Replacer.ReplaceValue,{"volum_lliurat"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Valor reemplazado2",{{"sector_id", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

