table fact_volum_lliurat
	lineageTag: 5cd2196b-62b2-4d8b-88f8-2a19a749bef6

	column sector_id
		dataType: int64
		formatString: 0
		lineageTag: d90cf0b5-fe98-4e81-96b4-7e6f37091c4d
		summarizeBy: sum
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column gerencia
		dataType: string
		lineageTag: 51f0be7b-7cb3-4b16-bad7-ae47dbc2f408
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	column pis_pressio
		dataType: string
		lineageTag: 10e05d81-1351-4bcf-88ab-ef550fdb556c
		summarizeBy: none
		sourceColumn: pis_pressio

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 06518a1c-964b-46b6-bfa7-b6c6dcecc7c9
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column volum_lliurat
		dataType: int64
		formatString: #,0
		lineageTag: 2a5e5433-0757-4336-9325-796543d7af1e
		summarizeBy: sum
		sourceColumn: volum_lliurat

		annotation SummarizationSetBy = Automatic

	partition fact_volum_lliurat = m
		mode: import
		source =
				let
				  Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1ZffEmnNoWOUZV2BWTDYGZTjcNVbZ07il0J7N43DN_IU/edit?gid=512415232#gid=512415232"),
				  TablaOrigen = Origen{[name = "Volums Lliurats", ItemKind = "Table"]}[Data],
				
				    // Preparación de datos
				    SaltarFilas = Table.Skip(TablaOrigen, 2),
				    PromoverEncabezados = Table.PromoteHeaders(SaltarFilas, [PromoteAllScalars = true]),
				
				    // Eliminar columnas innecesarias
				    EliminarColumnas = Table.RemoveColumns(
				        PromoverEncabezados,
				        {
				            "_1", "", "01/06/2026", "01/07/2026", "01/08/2026",
				            "01/09/2026", "01/10/2026", "01/11/2026", "01/12/2026"
				        }
				    ),
				
				    // Pasar las fechas a filas
				    DespivotarFechas = Table.UnpivotOtherColumns(
				        EliminarColumnas,
				        {"Nº", "Gerència", "Pis Pressió", "Sectors"},
				        "fecha",
				        "volum_lliurat"
				    ),
				
				    // Renombrar columnas
				    RenombrarColumnas = Table.RenameColumns(
				        DespivotarFechas,
				        {
				            {"Nº", "sector_id"},
				            {"Gerència", "gerencia"},
				            {"Pis Pressió", "pis_pressio"}
				        }
				    ),
				
				    // Eliminar columnas no necesarias
				    EliminarSectors = Table.RemoveColumns(RenombrarColumnas, {"Sectors"}),
				
				    // Asignar tipos de datos
				    CambiarTipos = Table.TransformColumnTypes(
				        EliminarSectors,
				        {
				            {"sector_id", Int64.Type},
				            {"gerencia", type text},
				            {"pis_pressio", type text},
				            {"fecha", type date},
				            {"volum_lliurat", Int64.Type}
				        }
				    ),
				
				    // Limpiar datos
				    SinDuplicados = Table.Distinct(CambiarTipos),
				    SinFilasVacias = Table.SelectRows(
				        SinDuplicados,
				        each List.NonNullCount(Record.FieldValues(_)) > 0
				    ),
				    #"Valor reemplazado" = Table.ReplaceValue(SinFilasVacias,"",null,Replacer.ReplaceValue,{"pis_pressio"})
				in
				    #"Valor reemplazado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

