table fact_dades_consum
	lineageTag: 56af65f5-8936-4c93-aaa9-ffa0727b9c34

	column POLISSA_SUBM
		dataType: string
		lineageTag: 06643eda-0ab4-4f42-8dfa-8526eb891d08
		summarizeBy: none
		sourceColumn: POLISSA_SUBM

		annotation SummarizationSetBy = Automatic

	column MES
		dataType: dateTime
		formatString: Long Date
		lineageTag: 68537c20-6c53-4050-9515-0ffc58876978
		summarizeBy: none
		sourceColumn: MES

		variation Variación
			isDefault
			relationship: 52b9b4b0-6318-45dc-97bf-b9c4eb7f5f60
			defaultHierarchy: LocalDateTable_5f85af88-49d8-4195-a4c1-37c75f1b54e0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column QMIN_HORA
		dataType: string
		lineageTag: f8431dfe-c2c9-4a0a-874c-9ddbe0cbad69
		summarizeBy: none
		sourceColumn: QMIN_HORA

		annotation SummarizationSetBy = Automatic

	column QMAX_HORA
		dataType: string
		lineageTag: c21b2a33-ffca-4efc-a854-4cd99a287857
		summarizeBy: none
		sourceColumn: QMAX_HORA

		annotation SummarizationSetBy = Automatic

	column CONSUM_MENSUAL_REAL
		dataType: string
		lineageTag: 225c614d-1e91-404f-a8e8-dd32b1f40878
		summarizeBy: none
		sourceColumn: CONSUM_MENSUAL_REAL

		annotation SummarizationSetBy = Automatic

	column CONSUM_MENSUAL_ESTIMAT
		dataType: string
		lineageTag: 17dacd7b-a6d3-4268-b3b8-d167c929a2a1
		summarizeBy: none
		sourceColumn: CONSUM_MENSUAL_ESTIMAT

		annotation SummarizationSetBy = Automatic

	column LECTURES_REBUDES
		dataType: string
		lineageTag: 4a496725-1633-4289-9135-ee896dcd9149
		summarizeBy: none
		sourceColumn: LECTURES_REBUDES

		annotation SummarizationSetBy = Automatic

	column DIES_LLEGITS
		dataType: string
		lineageTag: 395b15c4-fd9d-4afb-b4e9-0c30114693ad
		summarizeBy: none
		sourceColumn: DIES_LLEGITS

		annotation SummarizationSetBy = Automatic

	column DIES_ABSENTS
		dataType: string
		lineageTag: 06dd1a0f-b6a2-4b76-9ad8-e25bc86352f4
		summarizeBy: none
		sourceColumn: DIES_ABSENTS

		annotation SummarizationSetBy = Automatic

	column DIES_AMB_REGISTRE
		dataType: string
		lineageTag: 95c3b6d1-c46d-4d07-928f-a19f94389d97
		summarizeBy: none
		sourceColumn: DIES_AMB_REGISTRE

		annotation SummarizationSetBy = Automatic

	column DIES_AMB_CONSUM_0
		dataType: string
		lineageTag: bdfc6f37-4c94-44e7-8966-20ae6957cef8
		summarizeBy: none
		sourceColumn: DIES_AMB_CONSUM_0

		annotation SummarizationSetBy = Automatic

	column dies_amb_consum_0_any
		dataType: string
		lineageTag: 5a0d2689-0576-4239-ab6b-2e57678a32ef
		summarizeBy: none
		sourceColumn: dies_amb_consum_0_any

		annotation SummarizationSetBy = Automatic

	column NUM_SERIES_CONTADOR_2026_MES
		dataType: string
		lineageTag: 2f852989-bcbf-43cc-a8a1-00718fc2a340
		summarizeBy: none
		sourceColumn: NUM_SERIES_CONTADOR_2026_MES

		annotation SummarizationSetBy = Automatic

	partition fact_dades_consum = m
		mode: import
		source = ```
				// ESTA FACT SE GENERA A PARTIR DEL ARCHIVO 
				
				//            dades consum 2026 dummy desde drive, este archivo es para hacer maquetación hasta que nos den los datos reales desde snowflake ya que no hay acceso.
				// PESTAÑA:
				
				//              dades consum
				 
				
				let
				  Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/18Il4Zl3lWRN82U12wIePS-sEjeF815d91dmeAOId42c/edit?gid=https://docs.google.com/spreadsheets/d/18Il4Zl3lWRN82U12wIePS-sEjeF815d91dmeAOId42c/edit?gid=94400887#gid=9440088794400887#gid=94400887"),
				  #"Navegación 1" = Origen{[name = "Sheet", ItemKind = "Table"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"POLISSA_SUBM", "MES", "QMIN_HORA", "QMAX_HORA", "CONSUM_MENSUAL_REAL", "CONSUM_MENSUAL_ESTIMAT", "LECTURES_REBUDES", "DIES_LLEGITS", "DIES_ABSENTS", "DIES_AMB_REGISTRE", "DIES_AMB_CONSUM_0", "dies_amb_consum_0_any", "NUM_SERIES_CONTADOR_2026_MES"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Otras columnas quitadas",{{"MES", type date}}),
				    #"Errores quitados" = Table.RemoveRowsWithErrors(#"Tipo cambiado", {"MES"})
				in
				    #"Errores quitados"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

