table fact_estim_volum_munic_pob
	lineageTag: a322194d-526d-4972-9935-7fb6a0a97090

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5dedb020-2a77-49bf-a117-56b02ea8b85f
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column volum_estimado
		dataType: int64
		formatString: #,0
		lineageTag: afe5e64f-0e08-4781-bd12-cebddc4bc7f5
		summarizeBy: sum
		sourceColumn: volum_estimado

		annotation SummarizationSetBy = Automatic

	column id_mun
		dataType: int64
		formatString: 0
		lineageTag: 23051077-bd8a-4406-8a5b-9e8877eaa730
		summarizeBy: none
		sourceColumn: id_mun

		annotation SummarizationSetBy = Automatic

	column poblacion
		dataType: int64
		formatString: #,0
		lineageTag: 9a26a113-3f6e-4099-9570-0c85e4af49cd
		summarizeBy: sum
		sourceColumn: poblacion

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: 6b79a24c-5a5a-4097-b3a2-4eaaaceeeb34
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	partition fact_estim_volum_munic_pob = m
		mode: import
		queryGroup: Hechos
		source =
				let
				      Origen = GoogleSheets.Contents(#"Estimació Volums Lliurats i Dotacions Municipis AB"),
				      #"Navegación 1" = Origen{[name = "Estimació Volums Municipals", ItemKind = "Table"]}[Data],
				        #"Columnas quitadas" = Table.RemoveColumns(#"Navegación 1",{"Column62"}),
				        #"Encabezados promovidos" = Table.PromoteHeaders(#"Columnas quitadas", [PromoteAllScalars=true]),
				        #"Columnas con nombre cambiado" = Table.RenameColumns(#"Encabezados promovidos",{{"ESTACIO", "municipio"}}),
				        #"Filas inferiores quitadas" = Table.RemoveLastN(#"Columnas con nombre cambiado",5),
				        #"Otras columnas con anulación de dinamización" = Table.UnpivotOtherColumns(#"Filas inferiores quitadas", {"municipio"}, "Atributo", "Valor"),
				        #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Otras columnas con anulación de dinamización",{{"Atributo", "fecha"}, {"Valor", "volum_estimado"}}),
				        #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"volum_estimado", type number}, {"fecha", type date}}),
				        #"Texto limpio" = Table.TransformColumns(#"Tipo cambiado",{{"municipio", Text.Clean, type text}}),
				        #"Texto recortado" = Table.TransformColumns(#"Texto limpio",{{"municipio", Text.Trim, type text}}),
				        #"Columnas reordenadas" = Table.ReorderColumns(#"Texto recortado",{ "municipio", "fecha", "volum_estimado"}),
				        #"Valor reemplazado" = Table.ReplaceValue(#"Columnas reordenadas",null,0,Replacer.ReplaceValue,{"volum_estimado"}),
				        #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado",{{"volum_estimado", Int64.Type}}),
				        #"Consultas combinadas" = Table.NestedJoin(#"Tipo cambiado1", {"municipio"}, dim_municipio, {"municipio"}, "dim_municipio", JoinKind.LeftOuter),
				        #"Se expandió dim_municipio" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_municipio", {"id_mun"}, {"id_mun"}),
				        #"Columnas quitadas1" = Table.RemoveColumns(#"Se expandió dim_municipio",{"municipio"}),
				    #"Mes insertado" = Table.AddColumn(#"Columnas quitadas1", "Mes", each Date.Month([fecha]), Int64.Type),
				        #"Consultas combinadas1" = Table.NestedJoin(#"Mes insertado", {"Mes", "id_mun"}, aux_fact_poblacion_munic, {"Mes", "id_mun"}, "aux_fact_poblacion_munic", JoinKind.LeftOuter),
				        #"Se expandió aux_fact_poblacion_munic" = Table.ExpandTableColumn(#"Consultas combinadas1", "aux_fact_poblacion_munic", {"Valor"}, {"Valor"}),
				    #"Columnas con nombre cambiado2" = Table.RenameColumns(#"Se expandió aux_fact_poblacion_munic",{{"Valor", "poblacion"}}),
				        #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas con nombre cambiado2",{{"poblacion", Int64.Type}})
				in
				    #"Tipo cambiado2"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

