table fact_perimetre_comptadors
	lineageTag: 91320900-a8f9-4598-9593-2168faea73b4

	column polissa_subm
		dataType: string
		lineageTag: e23071de-9336-4599-ab97-fdddbc9203a4
		summarizeBy: none
		sourceColumn: polissa_subm

		annotation SummarizationSetBy = Automatic

	column data_alt_subm_serv
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8110aba9-dbff-4e5a-b0fd-c57d5066dc33
		summarizeBy: none
		sourceColumn: data_alt_subm_serv

		variation Variación
			isDefault
			relationship: cf06cc2c-52dd-47b9-9724-267ec31b9355
			defaultHierarchy: LocalDateTable_b40c45dc-4a67-441b-bfe4-5743b3011ce5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column tip_subm_serv
		dataType: string
		lineageTag: 9053cff7-97a0-45b7-a170-e3c6ef98d360
		summarizeBy: none
		sourceColumn: tip_subm_serv

		annotation SummarizationSetBy = Automatic

	column us_aigua_gest
		dataType: string
		lineageTag: 0b6396c5-84c2-435a-89ee-71b32fdb7bed
		summarizeBy: none
		sourceColumn: us_aigua_gest

		annotation SummarizationSetBy = Automatic

	column ind_compt_estrategic
		dataType: string
		lineageTag: ab12867b-9eb9-47e2-aa3d-ef00395c572f
		summarizeBy: none
		sourceColumn: ind_compt_estrategic

		annotation SummarizationSetBy = Automatic

	column polissa_ramal
		dataType: string
		lineageTag: 1692db50-71e5-4c52-a1bc-5b1247b93618
		summarizeBy: none
		sourceColumn: polissa_ramal

		annotation SummarizationSetBy = Automatic

	column pis_pressio
		dataType: string
		lineageTag: 115bc88c-2627-4a13-a0b6-acb3da6835f9
		summarizeBy: none
		sourceColumn: pis_pressio

		annotation SummarizationSetBy = Automatic

	column num_complet
		dataType: string
		lineageTag: 5811a8ea-e8a3-452c-a106-b913881adb66
		summarizeBy: none
		sourceColumn: num_complet

		annotation SummarizationSetBy = Automatic

	column data_inst_comp
		dataType: dateTime
		formatString: Long Date
		lineageTag: b5356a19-493b-403d-992a-e084b98113bf
		summarizeBy: none
		sourceColumn: data_inst_comp

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column diam_comp
		dataType: string
		lineageTag: dbddfc9d-a0ff-439e-bc4d-1744aa9f754b
		summarizeBy: none
		sourceColumn: diam_comp

		annotation SummarizationSetBy = Automatic

	column diam_comp_cte
		dataType: string
		lineageTag: 300fe662-dac2-4af7-a982-1eb69ad52c5b
		summarizeBy: none
		sourceColumn: diam_comp_cte

		annotation SummarizationSetBy = Automatic

	column cabal_q3
		dataType: string
		lineageTag: 904b9e3e-2c14-4258-ab2e-f622b709d3b2
		summarizeBy: none
		sourceColumn: cabal_q3

		annotation SummarizationSetBy = Automatic

	column ratio_comp
		dataType: string
		lineageTag: 93a68a4e-ca57-4472-beb9-7191f0c8bb2b
		summarizeBy: none
		sourceColumn: ratio_comp

		annotation SummarizationSetBy = Automatic

	column rati_classe
		dataType: string
		lineageTag: bcbb4960-6a83-4efb-8865-e3bb24f1b98c
		summarizeBy: none
		sourceColumn: rati_classe

		annotation SummarizationSetBy = Automatic

	column ql_sistema_model
		dataType: string
		lineageTag: f8302c7b-6351-47db-ad55-cca55b5d180c
		summarizeBy: none
		sourceColumn: ql_sistema_model

		annotation SummarizationSetBy = Automatic

	column tecno_tele
		dataType: string
		lineageTag: f5619a4c-3465-4967-9e64-17a30e2a8f21
		summarizeBy: none
		sourceColumn: tecno_tele

		annotation SummarizationSetBy = Automatic

	column ind_fact_bdts
		dataType: string
		lineageTag: d1f8ae30-7b4a-4875-ae8c-c199d5d1fc5a
		summarizeBy: none
		sourceColumn: ind_fact_bdts

		annotation SummarizationSetBy = Automatic

	column reg_i_font
		dataType: string
		lineageTag: 2b7c3c4e-48e2-4898-8923-0ac8a82b0913
		summarizeBy: none
		sourceColumn: reg_i_font

		annotation SummarizationSetBy = Automatic

	column marca_comp
		dataType: string
		isHidden
		lineageTag: a529f234-efaf-4644-8df3-d430d161118e
		summarizeBy: none
		sourceColumn: marca_comp

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column codi_model
		dataType: string
		isHidden
		lineageTag: 67b3560e-eb52-4d2e-9850-f9deafe2dc35
		summarizeBy: none
		sourceColumn: codi_model

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_marca_modelo
		dataType: string
		lineageTag: 7fce0c4c-b650-47af-bdcc-ee9b283e24b5
		summarizeBy: none
		sourceColumn: id_marca_modelo

		annotation SummarizationSetBy = Automatic

	column sector_id
		dataType: string
		lineageTag: 47be6257-4914-4a45-8de7-4024f74b37c8
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: f700d126-c835-4b69-82b0-89f59278c17f
		summarizeBy: sum
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

	partition fact_perimetre_comptadors = m
		mode: import
		queryGroup: Hechos
		source =
				let
				    Union =
				        Table.Combine({
				           perimetre_comptadors_2026,
				            perimetre_comptadors_2025,
				            perimetre_comptadors_2024
				        }),
				    #"Duplicados quitados" = Table.Distinct(Union),
				    #"Consultas combinadas" = Table.NestedJoin(#"Duplicados quitados", {"gerencia"}, dim_gerencia, {"gerencia"}, "dim_gerencia", JoinKind.LeftOuter),
				    #"Se expandió dim_gerencia" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_gerencia", {"gerencia_id"}, {"gerencia_id"}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Se expandió dim_gerencia",{"gerencia"}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas", each ([sector_id] = ""))
				in
				    #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

