table fact_ortomat
	lineageTag: f018d9f1-c1c0-4bb4-baba-e2ab1458a84c

	column sector_id
		dataType: string
		lineageTag: 89b6b877-8686-4e07-9f90-d587834a927b
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column unidad_sensors
		dataType: string
		lineageTag: 7e93b9c9-ed04-426a-ab32-c4680cdbf388
		summarizeBy: none
		sourceColumn: unidad_sensors

		annotation SummarizationSetBy = Automatic

	column tiene_sensor
		dataType: int64
		formatString: 0
		lineageTag: 13bb37de-feb6-4673-9c07-0d93f3bff880
		summarizeBy: sum
		sourceColumn: tiene_sensor

		annotation SummarizationSetBy = Automatic

	partition fact_ortomat = m
		mode: import
		source =
				let
				  Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1dca9OE3HQzH16kwQty0mn2sH6krPn0RFOmR9uFBWXJI/edit?gid=709331709#gid=709331709"),
				  #"Navegación 1" = Origen{[name = "Sectores_sembrados_numero", ItemKind = "Table"]}[Data],
				
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars=true]),
				
				    #"Columnas quitadas" = Table.RemoveColumns(
				        #"Encabezados promovidos",
				        {"OBJECTID", "DENOMIN_2", "SHAPE_Le_1", "SHAPE_Ar_1"}
				    ),
				
				    #"Columnas renombradas" = Table.RenameColumns(
				        #"Columnas quitadas",
				        {
				            {"SAP_ID_2", "sector_id"},
				            {"NUMPOINTS", "unidad_sensors"}
				        }
				    ),
				
				    #"Valores reemplazados" = Table.ReplaceValue(
				        #"Columnas renombradas",
				        "",
				        null,
				        Replacer.ReplaceValue,
				        {"sector_id","unidad_sensors"}
				    ),
				
				    #"Tiene sensor agregado" = Table.AddColumn(
				        #"Valores reemplazados",
				        "tiene_sensor",
				        each if [unidad_sensors] = null or [unidad_sensors] = 0 then 0 else 1,
				        Int64.Type
				    ),
				
				    #"Filas vacías eliminadas" = Table.SelectRows(
				        #"Tiene sensor agregado",
				        each not (
				            [sector_id] = null and
				            ([unidad_sensors] = null or [unidad_sensors] = 0) and
				            [tiene_sensor] = 0
				        )
				    ),
				
				    #"Filas en blanco eliminadas" = Table.SelectRows(
				        #"Filas vacías eliminadas",
				        each not List.IsEmpty(
				            List.RemoveMatchingItems(Record.FieldValues(_), {"", null})
				        )
				    ),
				
				    #"Duplicados quitados" = Table.Distinct(#"Filas en blanco eliminadas")
				
				in
				    #"Duplicados quitados"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

