table fact_cabals_mínims
	lineageTag: 2b8a1269-956c-48ff-b0ff-5b8c1f1bcf33

	column sector_id
		dataType: double
		formatString: 0
		lineageTag: 67379891-00af-44a9-96a8-13b6037aac08
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column arteria
		dataType: string
		lineageTag: 2d3bf6ae-e08b-4d16-9f24-0e4930f0329f
		summarizeBy: none
		sourceColumn: arteria

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 5d6a8e90-4e5a-4cfe-8b0f-d48eceae4e25
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column q_min
		dataType: double
		lineageTag: 4a5995df-ad08-46ce-ba10-204791094bde
		summarizeBy: sum
		sourceColumn: q_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: f27ea86a-c564-489d-a3f1-3a7b3dd8f244
		summarizeBy: sum
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

	partition fact_cabals_mínims = m
		mode: import
		queryGroup: Hechos
		source =
				let
				    Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1ZffEmnNoWOUZV2BWTDYGZTjcNVbZ07il0J7N43DN_IU/edit?gid=1259268357#gid=1259268357"),
				    Datos = Origen{[name="Cabals Mínims", ItemKind="Table"]}[Data],
				    DatosLimpios = Table.PromoteHeaders(
				        Table.Skip(Datos, 2),
				        [PromoteAllScalars = true]
				    ),
				    #"Filas filtradas" = Table.SelectRows(DatosLimpios, each ([Nº] <> "")),
				    Renombradas = Table.RenameColumns(#"Filas filtradas",{{"Nº", "sector_id"}, {"Gerència", "gerencia"}, {"Sectors", "sectors"}, {"Q ref", "q_ref"}, {"", "arteria"}}),
				    Eliminadas = Table.RemoveColumns(Renombradas, {"q_ref", "_1", "_2", "_3"}),
				    Despivotadas = Table.UnpivotOtherColumns(
				        Eliminadas,
				        {"sector_id", "arteria", "gerencia", "sectors"},
				        "fecha",
				        "q_min"
				    ),
				    Tipos = Table.TransformColumnTypes(
				        Despivotadas,
				        {
				            {"sector_id", Int64.Type},
				            {"gerencia", type text},
				            {"arteria", type text},
				            {"sectors", type text},
				            {"fecha", type date},
				            {"q_min", type number}
				        }
				    ),
				    #"Valor reemplazado" = Table.ReplaceValue(Tipos,"","No Disponible",Replacer.ReplaceValue,{"gerencia"}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Valor reemplazado", {"gerencia"}, dim_gerencia, {"gerencia"}, "dim_gerencia", JoinKind.LeftOuter),
				    #"Se expandió dim_gerencia" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_gerencia", {"gerencia_id"}, {"gerencia_id"}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Se expandió dim_gerencia",{"gerencia"}),
				    #"Valores reemplazados" = Table.ReplaceValue(Table.ReplaceValue(#"Columnas quitadas","","No Disponible",Replacer.ReplaceValue,{"sectors"}),null,-1,Replacer.ReplaceValue,{"sector_id"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valores reemplazados","","No Disponible",Replacer.ReplaceValue,{"arteria"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","Río","Rio",Replacer.ReplaceText,{"sectors"}),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Valor reemplazado2",{"sectors"})
				in
				    #"Columnas quitadas1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

