table fact_inventari_xarxa_mensual
	lineageTag: 2b91454c-c160-4687-a602-165ee754b802

	column nombre_escomeses_totals
		dataType: string
		lineageTag: 2f9ce981-53d4-43c1-8198-8eee475d7412
		summarizeBy: none
		sourceColumn: nombre_escomeses_totals

		annotation SummarizationSetBy = Automatic

	column nombre_subministraments_totals
		dataType: string
		lineageTag: 7c816a6c-c396-4488-84a2-b88daa7520e7
		summarizeBy: none
		sourceColumn: nombre_subministraments_totals

		annotation SummarizationSetBy = Automatic

	column l_+_t_km
		dataType: string
		lineageTag: b2828f6c-df90-43a1-a706-53974c4ac75f
		summarizeBy: none
		sourceColumn: l_+_t_km

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: string
		lineageTag: e4009b57-a2ad-4abd-a8de-35ef1075cbec
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

	partition fact_inventari_xarxa_mensual = m
		mode: import
		source = ```
				// ESTA FACT SE GENERA A PARTIR DEL ARCHIVO 
				//              Indicadors ANR 2026
				// PESTAÑA:
				//              Inventari xarxa
				let
				    // Origen
				    Origen = GoogleSheets.Contents(
				        "https://docs.google.com/spreadsheets/d/1LK5D7QclVwCBGy5-hONVLgP1GgW35okgrxNLr1kJCoE/edit?gid=664401204#gid=664401204"
				    ),
				    Datos = Origen{[name="Inventari xarxa", ItemKind="Table"]}[Data],
				
				    // Tomar filas y promover encabezados
				    DatosFiltrados = Table.PromoteHeaders(
				        Table.FirstN(Table.Skip(Datos, 373), 13),
				        [PromoteAllScalars = true]
				    ),
				
				    // Selección y renombrado en un solo bloque
				    Seleccion = Table.SelectColumns(
				        DatosFiltrados,
				        {
				            "Mes",
				            "L + T (km)",
				            "Nombre Escomeses Totals",
				            "Nombre Subministraments Totals"
				        }
				    ),
				
				    Renombradas = Table.RenameColumns(
				        Seleccion,
				        {
				            {"Mes", "fecha"},
				            {"L + T (km)", "L + T km"}
				        }
				    ),
				
				    // Normalización final
				    Normalizadas = Table.TransformColumnNames(
				        Renombradas,
				        each Text.Replace(Text.Lower(_), " ", "_")
				    )
				in
				    Normalizadas
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

