table fact_inventari_xarxa_mitjana_12m
	lineageTag: 3ba91347-40e9-443f-a0f7-cf3c1c908be9

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: ef0396ad-1533-4f35-820d-f0361b4bfe55
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column nombre_escomeses_totals
		dataType: double
		lineageTag: c68e0452-4c37-483f-9aca-8b36bd4ed131
		summarizeBy: sum
		sourceColumn: nombre_escomeses_totals

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nombre_subministraments_totals
		dataType: double
		lineageTag: cba49637-526d-4a50-8aaa-0e7cc64f592d
		summarizeBy: sum
		sourceColumn: nombre_subministraments_totals

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column l_+_t_km
		dataType: double
		lineageTag: dddf41a6-b0bb-45f5-a5a0-1838ad1ca7f0
		summarizeBy: sum
		sourceColumn: l_+_t_km

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_inventari_xarxa_mitjana_12m = m
		mode: import
		source = ```
				let
				    Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vQYF-6nyJqkaezSpkqBN_a0Qmxw1GysBfL8py3eq4WzwX0xzzitdfbvqMzf9D-0YQ/pub?gid=664401204&single=true&output=csv"),[Delimiter=",", Columns=48, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Filas superiores quitadas" = Table.Skip(Origen,394),
				    #"Conservar filas superiores" = Table.FirstN(#"Filas superiores quitadas",13),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Conservar filas superiores", [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{
				        "Mes",  "L + T (km)", "Nombre Escomeses Totals", "Nombre Subministraments Totals"
				    }),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Otras columnas quitadas",{{"L + T (km)", "L + T km"}}),
				
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "fecha", each 
				        let
				            txt0  = [Mes],
				            txt1  = Text.Lower(txt0),
				            txt2  = Text.Replace(Text.Replace(Text.Replace(txt1,"de ",""),"d’",""),".",""),
				            mesTxt = Text.BeforeDelimiter(txt2,"-"),
				            anioTxt = Text.AfterDelimiter(txt2,"-"),
				            anio = 2000 + Number.FromText(anioTxt),
				            mes = 
				                if mesTxt = "gen"  then 1 else
				                if mesTxt = "febr" then 2 else
				                if mesTxt = "març" then 3 else
				                if mesTxt = "abr"  then 4 else
				                if mesTxt = "maig" then 5 else
				                if mesTxt = "juny" then 6 else
				                if mesTxt = "jul"  then 7 else
				                if mesTxt = "ag"   then 8 else
				                if mesTxt = "set"  then 9 else
				                if mesTxt = "oct"  then 10 else
				                if mesTxt = "nov"  then 11 else
				                if mesTxt = "des"  then 12 else
				                null
				        in
				            #date(anio, mes, 1)
				    ),
				
				    // 🔥 NORMALIZAR NOMBRES DE COLUMNAS
				    #"Columnas normalizadas" =
				        Table.TransformColumnNames(#"Personalizada agregada",
				            each Text.Replace(Text.Lower(_), " ", "_")
				        ),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Columnas normalizadas",{"mes"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas quitadas",{{"l_+_t_km", type number}, {"nombre_escomeses_totals", type number}, {"nombre_subministraments_totals", type number}, {"fecha", type date}})
				
				in
				    #"Tipo cambiado"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

