table fact_anr_global_mensual
	lineageTag: 9504b9d8-b020-4172-8847-a7e2ec32c38b

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: fc6bd2b9-8631-4bab-b96c-8999c9c885a5
		summarizeBy: none
		sourceColumn: fecha

		variation Variación
			isDefault
			relationship: 7d115471-1de3-4301-bc17-edc8a939b8b7
			defaultHierarchy: LocalDateTable_d1b90805-bd5a-402f-9490-942013cea1b8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column lliurada_hm3
		dataType: double
		lineageTag: 95008ab9-c28c-4e9a-bb4a-be11883cb154
		summarizeBy: sum
		sourceColumn: lliurada_hm3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consumida_hm3
		dataType: double
		lineageTag: a558f85a-9796-4996-b276-ef6c85251aa8
		summarizeBy: sum
		sourceColumn: consumida_hm3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rth_global
		dataType: double
		lineageTag: 61cac931-8049-4841-84c8-d46df6557178
		summarizeBy: sum
		sourceColumn: rth_global

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anr_global_hm3
		dataType: double
		lineageTag: 9e04d3b5-a2cc-4410-a368-92c8a8ac89f2
		summarizeBy: sum
		sourceColumn: anr_global_hm3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_anr_global_mensual = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vRS1zkWHKwzcm2ZLhnMstWbjgJtQC3DCBLdSY_mCFGtR3x8Z4xdlut8iUNJwB5KVQ/pub?gid=315911922&single=true&output=csv"),
				        [Delimiter = ",", Columns = 48, Encoding = 65001, QuoteStyle = QuoteStyle.None]
				    ),
				    Data =
				        Table.PromoteHeaders(
				            Table.SelectColumns(
				                Table.Range(Source, 4, 13),
				                {"Column1", "Column2", "Column3", "Column4", "Column5"}
				            ),
				            [PromoteAllScalars = true]
				        ),
				    Renamed =
				        Table.RenameColumns(Data,{{"Any", "fecha"}, {"Aigua Lliurada (hm3)", "lliurada_hm3"}, {"Aigua Consumida (hm3)", "consumida_hm3"}, {"RTH Global", "rth_global"}, {"ANR Global (hm3)", "anr_global_hm3"}}),
				    ReplaceDots =
				        Table.TransformColumns(
				            Renamed,
				            List.Transform(
				                List.RemoveItems(Table.ColumnNames(Renamed), {"date"}),
				                each {_, (x) => Text.Replace(x, ".", ","), type text}
				            )
				        ),
				    Result =
				        Table.TransformColumnTypes(
				            ReplaceDots,
				            {
				                {"fecha", type date},
				                {"lliurada_hm3", type number},
				                {"consumida_hm3", type number},
				                {"rth_global", type number},
				                {"anr_global_hm3", type number}
				            }
				        )
				in
				    Result

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Exception

