table fact_consum_no_control
	lineageTag: 8ec90fee-7236-4047-8005-66ff5855db1c

	column gerencia_id
		dataType: int64
		formatString: 0
		lineageTag: 5720fa0c-6ea3-4de9-9c57-d0fc202594ca
		summarizeBy: sum
		sourceColumn: gerencia_id

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: fcd11ba1-7856-4108-b953-5c0c65927095
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column tipo_consum
		dataType: string
		lineageTag: 5c71caa3-ba66-4eff-9de5-5910415f59cc
		summarizeBy: none
		sourceColumn: tipo_consum

		annotation SummarizationSetBy = Automatic

	column consumo
		dataType: int64
		formatString: 0
		lineageTag: bdf5171c-7caa-4401-8610-55db10886c6e
		summarizeBy: sum
		sourceColumn: consumo

		annotation SummarizationSetBy = Automatic

	partition fact_consum_no_control = m
		mode: import
		queryGroup: Hechos
		source = ```
				let
				    Origen = let
								    Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1ZffEmnNoWOUZV2BWTDYGZTjcNVbZ07il0J7N43DN_IU/edit?gid=372424086#gid=372424086"),
								    Tabla = Origen{[name="Consums No Controlats", ItemKind="Table"]}[Data],
								    Limpia = Table.SelectRows(
								        Table.RemoveColumns(Tabla, {"Column1","Column76"}),
								        each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))
								    ),
								
								    Rango = Table.Range(Limpia,0,15),
								
								    Categoria = Table.FillDown(
								        Table.AddColumn(
								            Rango,
								            "categoria_org",
								            each
								                if [Column2] <> null and Text.StartsWith(Text.Trim(Text.From([Column2])),"Consum")
								                then [Column2]
								                else null
								        ),
								        {"categoria_org"}
								    ),
								
								    Gerencia = Table.AddColumn(
								        Table.RemoveRows(Categoria,7,1),
								        "gerencia",
								        each
								            if [Column2] <> null
								                and Text.Trim(Text.From([Column2]))<>""
								                and not Text.StartsWith(Text.Trim(Text.From([Column2])),"Consum")
								                and not Text.StartsWith(Text.Trim(Text.From([Column2])),"Venda")
								            then [Column2]
								            else if ([Column2]=null or Text.Trim(Text.From([Column2]))="")
								                and [Column3]<>null
								                and Text.Trim(Text.From([Column3]))<>""
								            then [Column3]
								            else null
								    ),
								
								    SubCategoria = Table.AddColumn(
								        Gerencia,
								        "subcategoria",
								        each
								            if [Column2]<>null
								                and Text.Trim(Text.From([Column2]))<>""
								                and not Text.StartsWith(Text.Trim(Text.From([Column2])),"Consum")
								            then [Column3]
								            else null
								    ),
								
								    Encabezados = Table.PromoteHeaders(
								        Table.Skip(
								            Table.RemoveColumns(SubCategoria,{"Column2","Column3"}),
								            1
								        ),
								        [PromoteAllScalars=true]
								    ),
								
								    Renombradas = Table.RenameColumns(
								        Encabezados,
								        {
								            {"Consum No Controlat Baixa","categoria_org"},
								            {"Column74","gerencia"},
								            {"Column75","subcategoria"}
								        }
								    ),
								
								    Datos = Table.RemoveRows(Renombradas,5,2),
								
								    Unpivot = Table.UnpivotOtherColumns(
								        Datos,
								        {"categoria_org","gerencia","subcategoria"},
								        "Atributo",
								        "Valor"
								    ),
								
								    Transformada = Table.TransformColumnTypes(
								        Table.ReplaceValue(Unpivot,"","0",Replacer.ReplaceValue,{"Valor"}),
								        {{"Valor", Int64.Type}}
								    ),
								
								    Fecha = Table.AddColumn(
								        Transformada,
								        "Fecha",
								        each #date(
								            Number.From(Text.Start(Text.From([Atributo]),4)),
								            Number.From(Text.End(Text.From([Atributo]),2)),
								            1
								        ),
								        type date
								    ),
								
								    FinalTexto = Table.TransformColumns(
								        Table.ReplaceValue(
								            Table.RemoveColumns(Fecha,{"Atributo"}),
								            null,
								            "Baixa",
								            Replacer.ReplaceValue,
								            {"subcategoria"}
								        ),
								        {
								            {"gerencia", each Text.Proper(Text.Trim(Text.Clean(_))), type text}
								        }
								    ),
								
								    JoinGerencia = Table.ExpandTableColumn(
								        Table.NestedJoin(
								            FinalTexto,
								            {"gerencia"},
								            dim_gerencia,
								            {"gerencia"},
								            "dim_gerencia",
								            JoinKind.LeftOuter
								        ),
								        "dim_gerencia",
								        {"gerencia_id"},
								        {"gerencia_id"}
								    ),
								
								    Resultado = Table.ReorderColumns(
								        Table.RenameColumns(
								            Table.RemoveColumns(
								                JoinGerencia,
								                {"gerencia","categoria_org"}
								            ),
								            {{"subcategoria","tipo_consum"},{"Valor","consumo"}}
								        ),
								        {"gerencia_id","Fecha","tipo_consum","consumo"}
								    ),
								    #"Filas filtradas" = Table.SelectRows(Resultado, each [Fecha] > #date(2021, 12, 31))
								in
								    #"Filas filtradas"
				in
				    Origen
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

