table fact_dades_consum
	lineageTag: 5773743e-c258-46ba-b92b-c905e2beb234

	column polissa_subm
		dataType: string
		lineageTag: de68a846-6e71-4bff-9e6a-d4e99aa287d0
		summarizeBy: none
		sourceColumn: polissa_subm

		annotation SummarizationSetBy = Automatic

	column qmin_hora
		dataType: int64
		formatString: 0
		lineageTag: 209ac08b-dfcc-4a9d-a106-154efcfc1506
		summarizeBy: sum
		sourceColumn: qmin_hora

		annotation SummarizationSetBy = Automatic

	column qmax_hora
		dataType: int64
		formatString: 0
		lineageTag: 6afc2fdf-30ce-435d-8734-a555ef2849e4
		summarizeBy: sum
		sourceColumn: qmax_hora

		annotation SummarizationSetBy = Automatic

	column consum_mensual_real
		dataType: int64
		formatString: 0
		lineageTag: 1034e4ae-5649-4df7-a5be-e020ad1bcfb3
		summarizeBy: sum
		sourceColumn: consum_mensual_real

		annotation SummarizationSetBy = Automatic

	column consum_mensual_estimat
		dataType: int64
		formatString: 0
		lineageTag: 9eed98cc-ab60-4589-8bc5-b143011911b1
		summarizeBy: sum
		sourceColumn: consum_mensual_estimat

		annotation SummarizationSetBy = Automatic

	column lectures_rebudes
		dataType: int64
		formatString: 0
		lineageTag: d1407267-7c9b-42c1-a282-597a91fdd34c
		summarizeBy: sum
		sourceColumn: lectures_rebudes

		annotation SummarizationSetBy = Automatic

	column dies_llegits
		dataType: int64
		formatString: 0
		lineageTag: cc2bb109-5ed7-464b-be90-5b5d55dd7f2c
		summarizeBy: sum
		sourceColumn: dies_llegits

		annotation SummarizationSetBy = Automatic

	column dies_absents
		dataType: int64
		formatString: 0
		lineageTag: 19dbc640-9fd1-4165-b316-8e3547ec03c9
		summarizeBy: sum
		sourceColumn: dies_absents

		annotation SummarizationSetBy = Automatic

	column dies_amb_registre
		dataType: int64
		formatString: 0
		lineageTag: 7291b2db-86d7-40c5-b3c5-ece875afcb91
		summarizeBy: sum
		sourceColumn: dies_amb_registre

		annotation SummarizationSetBy = Automatic

	column dies_amb_consum_0
		dataType: int64
		formatString: 0
		lineageTag: 40270ba6-ae90-4892-a77d-0c6441abd588
		summarizeBy: sum
		sourceColumn: dies_amb_consum_0

		annotation SummarizationSetBy = Automatic

	column dies_amb_consum_0_any
		dataType: int64
		formatString: 0
		lineageTag: 1543b836-b682-477d-88a9-b31702c0d036
		summarizeBy: sum
		sourceColumn: dies_amb_consum_0_any

		annotation SummarizationSetBy = Automatic

	column num_series_contador_2026_mes
		dataType: int64
		formatString: 0
		lineageTag: e307533f-3bc6-44fa-9167-7dfdadad7a5c
		summarizeBy: sum
		sourceColumn: num_series_contador_2026_mes

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: b2b84bd7-c191-4721-a7c7-bcf08da595ac
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_dades_consum = m
		mode: import
		source =
				let
				    // Cargar origen
				    origen = GoogleSheets.Contents(
				        "https://docs.google.com/spreadsheets/d/18Il4Zl3lWRN82U12wIePS-sEjeF815d91dmeAOId42c/edit?gid=94400887#gid=94400887"
				    ),
				    tabla = origen{[name = "Sheet", ItemKind = "Table"]}[Data],
				
				    // Promover encabezados y convertirlos a minúsculas
				    encabezados = Table.PromoteHeaders(tabla, [PromoteAllScalars = true]),
				    minusculas = Table.TransformColumnNames(encabezados, Text.Lower),
				
				    // Quitar columnas innecesarias
				    quitarCols = Table.RemoveColumns(minusculas, {"mes nom", "any"}),
				
				    // Crear columna fecha optimizada
				    agregarFecha =
				        Table.AddColumn(
				            quitarCols,
				            "fecha",
				            each
				                let
				                    texto = Text.AfterDelimiter([mes], ", "),
				                    limpio = Text.Replace(texto, ",", ""),
				                    partes = Text.Split(limpio, " "),
				                    mesTxt = Text.Lower(partes{0}),
				                    dia = Number.FromText(partes{1}),
				                    año = Number.FromText(partes{2}),
				                    meses = {"ene","feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic"},
				                    mesNum = List.PositionOf(meses, mesTxt) + 1
				                in
				                    #date(año, mesNum, dia)
				        ),
				
				    // Eliminar columna original mes
				    resultado = Table.RemoveColumns(agregarFecha, {"mes"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(resultado,{{"polissa_subm", type text}, {"qmin_hora", Int64.Type}, {"qmax_hora", Int64.Type}, {"consum_mensual_real", Int64.Type}, {"consum_mensual_estimat", Int64.Type}, {"lectures_rebudes", Int64.Type}, {"dies_llegits", Int64.Type}, {"dies_absents", Int64.Type}, {"dies_amb_registre", Int64.Type}, {"dies_amb_consum_0", Int64.Type}, {"dies_amb_consum_0_any", Int64.Type}, {"num_series_contador_2026_mes", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

