table fact_estadístiques_comp
	lineageTag: 1f4a1c1d-23ce-46a9-8d90-13b531f6f6c1

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 29a42bfc-1365-45b5-919e-eed0d7895a79
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column agrupació_canvi
		dataType: string
		lineageTag: b0511eea-808d-4784-b448-126d7a99d91d
		summarizeBy: none
		sourceColumn: agrupació_canvi

		annotation SummarizationSetBy = Automatic

	column agrupació_edat
		dataType: string
		lineageTag: 227db6a2-14d1-495d-bc8e-760e1f3c1bb6
		summarizeBy: none
		sourceColumn: agrupació_edat

		annotation SummarizationSetBy = Automatic

	column tip_submin
		dataType: string
		lineageTag: f3913d25-81f7-4177-8369-b50e4e842c99
		summarizeBy: none
		sourceColumn: tip_submin

		annotation SummarizationSetBy = Automatic

	column grup_dn
		dataType: string
		lineageTag: 8299449b-ab15-44be-bc67-9e66acd183eb
		summarizeBy: none
		sourceColumn: grup_dn

		annotation SummarizationSetBy = Automatic

	column ﻿total
		dataType: double
		lineageTag: 84ae67bf-0664-4175-9d95-bc4480675c2e
		summarizeBy: sum
		sourceColumn: ﻿total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column desc_codi
		dataType: string
		lineageTag: f61ef780-1d54-45b4-9758-c9cb85ac5e98
		summarizeBy: none
		sourceColumn: desc_codi

		annotation SummarizationSetBy = Automatic

	column nom_executor
		dataType: string
		lineageTag: 53cda4af-16ba-411c-a5c3-e45232861352
		summarizeBy: none
		sourceColumn: nom_executor

		annotation SummarizationSetBy = Automatic

	column zona_operacions
		dataType: string
		lineageTag: 731aa6c4-f23e-4ce4-a85e-49047b1ec42a
		summarizeBy: none
		sourceColumn: zona_operacions

		annotation SummarizationSetBy = Automatic

	column estratègics
		dataType: string
		lineageTag: 3d92c1c4-24bb-4af3-ac54-95cb7fd664d5
		summarizeBy: none
		sourceColumn: estratègics

		annotation SummarizationSetBy = Automatic

	column diam_comp
		dataType: string
		lineageTag: 382aabb6-9fb3-4f56-af89-1f0effb75e76
		summarizeBy: none
		sourceColumn: diam_comp

		annotation SummarizationSetBy = Automatic

	column ql_compt_nou
		dataType: string
		lineageTag: c9fd050c-b96a-4e89-bbbc-d793a833c679
		summarizeBy: none
		sourceColumn: ql_compt_nou

		annotation SummarizationSetBy = Automatic

	column agrupació_edat_ga
		dataType: string
		lineageTag: 3ba52090-c2bc-466a-a515-37188d0475b7
		summarizeBy: none
		sourceColumn: agrupació_edat_ga

		annotation SummarizationSetBy = Automatic

	column número_mes
		dataType: string
		lineageTag: 2953c981-65a7-4c93-8346-cc78a3e5b502
		summarizeBy: none
		sourceColumn: número_mes

		annotation SummarizationSetBy = Automatic

	column tipus_executor
		dataType: string
		lineageTag: 0a7d8276-b57a-4adc-b876-39a7948df10b
		summarizeBy: none
		sourceColumn: tipus_executor

		annotation SummarizationSetBy = Automatic

	column codi_mes
		dataType: string
		lineageTag: 0ab2e888-e02e-435f-a3dc-04f095469c4a
		summarizeBy: none
		sourceColumn: codi_mes

		annotation SummarizationSetBy = Automatic

	partition fact_estadístiques_comp = m
		mode: import
		source = ```
				let
				    Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vSBdujYtm-k6b1sHDL1XjoEupA6bWpiO7est-_tshOR30XuF361C6fvUabG2i616w/pub?gid=524487380&single=true&output=csv"),[Delimiter=",", Columns=48, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"Agrupació Canvi", "Agrupació edat", "Tip Submin", "Grup DN", "﻿Total", "DESC_CODI", "Nom executor", "Zona Operacions", "Estratègics", "DIAM_COMP", "QL_COMPT_NOU", "Agrupació edat GA", "Número Mes", "Tipus Executor", "Codi mes"}),
				    
				    #"Personalizada agregada" = Table.AddColumn(#"Otras columnas quitadas", "fecha", each 
				        let
				            txt0 = [Codi mes],
				            txt1 = Text.Lower(txt0),
				            txt2 = Text.Replace(txt1, ".", ""),
				            txt3 = Text.Trim(Text.Replace(txt2, "  ", " ")),
				            txt4 = Text.Replace(txt3, " - ", "-"),
				            txt5 = Text.Replace(txt4, " -", "-"),
				            txt6 = Text.Replace(txt5, "- ", "-"),
				            mesNumTxt = Text.BeforeDelimiter(txt6, "-"),
				            mesNum = Number.FromText(Text.Trim(mesNumTxt)),
				            anio = Date.Year(DateTime.LocalNow()),
				            Fecha = #date(anio, mesNum, 1)
				        in
				            Fecha
				    ),
				
				    // 🔥 NORMALIZAR NOMBRES DE COLUMNAS
				    #"Columnas normalizadas" =
				        Table.TransformColumnNames(#"Personalizada agregada",
				            each Text.Replace(Text.Lower(_), " ", "_")
				        ),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas normalizadas",{{"﻿total", type number}})
				
				in
				    #"Tipo cambiado"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

