table fact_aigua_no_registrada_12m
	lineageTag: 17944b20-54dd-4407-93fe-f02962a5c271

	column Nº
		dataType: int64
		formatString: 0
		lineageTag: 4950e8a2-13aa-4ec8-974e-2479dcfc40b5
		summarizeBy: sum
		sourceColumn: Nº

		annotation SummarizationSetBy = Automatic

	column Gerència
		dataType: string
		lineageTag: e2e665ac-e82f-4777-a6e1-02a315e04cbc
		summarizeBy: none
		sourceColumn: Gerència

		annotation SummarizationSetBy = Automatic

	column 'Pis Pressió'
		dataType: string
		lineageTag: 92b4fc4a-dc43-4573-9d73-df7d0f154c33
		summarizeBy: none
		sourceColumn: Pis Pressió

		annotation SummarizationSetBy = Automatic

	column Sectors
		dataType: string
		lineageTag: e7eb2c98-9232-4cac-9a35-8afff06f01c9
		summarizeBy: none
		sourceColumn: Sectors

		annotation SummarizationSetBy = Automatic

	column Atributo
		dataType: string
		lineageTag: 74b11340-742b-412d-b88b-312950b336a3
		summarizeBy: none
		sourceColumn: Atributo

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: int64
		formatString: 0
		lineageTag: 7145cb0d-6348-43fe-998a-3ca474027bed
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3ed4ab1e-295d-4725-8716-9260c30d9b2a
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_aigua_no_registrada_12m = m
		mode: import
		source = ```
				let
				  Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vQu04YqiUjROdeKjkF1OKAb2UI0cIt8n44NDzq3nAdSvDc2p0zBvWngL_DNulEpHw/pub?gid=1960240863&single=true&output=csv"),[Delimiter=",", Columns=48, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Filas superiores quitadas" = Table.Skip(Origen,2),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Filas superiores quitadas", [PromoteAllScalars=true]),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Encabezados promovidos",{""}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas", each ([Nº] <> "")),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Filas filtradas",{{"Nº", Int64.Type}, {"Gerència", type text}, {"Pis Pressió", type text}, {"Sectors", type text},  {"de gen.-21", Int64.Type}, {"de febr.-21", Int64.Type}, {"de març-21", Int64.Type}, {"d’abr.-21", Int64.Type}, {"de maig-21", Int64.Type}, {"de juny-21", Int64.Type}, {"de jul.-21", Int64.Type}, {"d’ag.-21", Int64.Type}, {"de set.-21", Int64.Type}, {"d’oct.-21", Int64.Type}, {"de nov.-21", Int64.Type}, {"de des.-21", Int64.Type}, {"de gen.-22", Int64.Type}, {"de febr.-22", Int64.Type}, {"de març-22", Int64.Type}, {"d’abr.-22", Int64.Type}, {"de maig-22", Int64.Type}, {"de juny-22", Int64.Type}, {"de jul.-22", Int64.Type}, {"d’ag.-22", Int64.Type}, {"de set.-22", Int64.Type}, {"d’oct.-22", Int64.Type}, {"de nov.-22", Int64.Type}, {"de des.-22", Int64.Type}, {"de gen.-23", Int64.Type}, {"de febr.-23", Int64.Type}, {"de març-23", Int64.Type}, {"d’abr.-23", Int64.Type}, {"de maig-23", Int64.Type}, {"de juny-23", Int64.Type}, {"de jul.-23", Int64.Type}, {"d’ag.-23", Int64.Type}, {"de set.-23", Int64.Type}, {"d’oct.-23", Int64.Type}, {"de nov.-23", Int64.Type}, {"de des.-23", Int64.Type}, {"de gen.-24", Int64.Type}, {"de febr.-24", Int64.Type}, {"de març-24", Int64.Type}, {"d’abr.-24", Int64.Type}, {"de maig-24", Int64.Type}, {"de juny-24", Int64.Type}, {"de jul.-24", Int64.Type}}),
				    #"Columna de anulación de dinamización" = Table.UnpivotOtherColumns(#"Tipo cambiado", {"Nº", "Gerència", "Pis Pressió", "Sectors"}, "Atributo", "Valor"),
				    #"Personalizada agregada" = Table.AddColumn(#"Columna de anulación de dinamización", "fecha", each let
				    txt0  = [Atributo],
				    // pasar a minúsculas
				    txt1  = Text.Lower(txt0),
				    // quitar "de ", "d’" y puntos
				    txt2  = Text.Replace(Text.Replace(Text.Replace(txt1,"de ",""),"d’",""),".",""),
				    // separar mes y año por el guion -
				    mesTxt = Text.BeforeDelimiter(txt2,"-"),
				    anioTxt = Text.AfterDelimiter(txt2,"-"),
				    // convertir año tipo "21" -> 2021
				    anio = 2000 + Number.FromText(anioTxt),
				    // mapear mes catalán -> número
				    mes = 
				        if mesTxt = "gen"  then 1 else
				        if mesTxt = "febr" then 2 else
				        if mesTxt = "març" then 3 else
				        if mesTxt = "abr"  then 4 else
				        if mesTxt = "maig" then 5 else
				        if mesTxt = "juny" then 6 else
				        if mesTxt = "jul"  then 7 else
				        if mesTxt = "ag"   then 8 else
				        if mesTxt = "set"  then 9 else
				        if mesTxt = "oct"  then 10 else
				        if mesTxt = "nov"  then 11 else
				        if mesTxt = "des"  then 12 else
				        null
				in
				    #date(anio, mes, 1))
				in
				    #"Personalizada agregada"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

