table fact_tfuita_tinst
	lineageTag: d505f986-3b2b-4b84-9fd0-9ec15a65e7f5

	column aviso
		dataType: int64
		formatString: 0
		lineageTag: d6dc4a14-456c-4e2d-91b6-f7aa271e94ff
		summarizeBy: none
		sourceColumn: aviso

		annotation SummarizationSetBy = Automatic

	column clase_de_aviso
		dataType: string
		lineageTag: 23c9904f-f788-4638-b6a4-d053797840a0
		summarizeBy: none
		sourceColumn: clase_de_aviso

		annotation SummarizationSetBy = Automatic

	column inicio_deseado
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2b864734-8848-43c5-b183-6de2eaf5f5bb
		summarizeBy: none
		sourceColumn: inicio_deseado

		variation Variación
			isDefault
			relationship: e1ace401-ddea-4390-8eb2-d0c915189bf2
			defaultHierarchy: LocalDateTable_b480c33a-2edc-4e9d-b4e0-19cf90c48a90.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column inicio_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: c38227f0-b448-404a-b909-8f28b633be42
		summarizeBy: none
		sourceColumn: inicio_de_averia

		variation Variación
			isDefault
			relationship: 4fd51915-6e67-4a55-b20b-6fd9eb9183c0
			defaultHierarchy: LocalDateTable_e147d9b5-b9d7-424e-8f6f-b4eb8dc67278.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_de_inicio_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: f09a2239-8924-445e-bdbc-df6eefceb928
		summarizeBy: none
		sourceColumn: hora_de_inicio_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column hora_de_fin_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: 05a88601-4d7e-4858-b7e8-f3907d530471
		summarizeBy: none
		sourceColumn: hora_de_fin_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column fin_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6e5f46c1-1235-47ae-80b5-d13121bc61ca
		summarizeBy: none
		sourceColumn: fin_de_averia

		variation Variación
			isDefault
			relationship: 5354e93e-748f-48d6-a664-aef14c0baac5
			defaultHierarchy: LocalDateTable_45460af1-cca6-4aed-b3fa-9f9f4fcb3eb0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column orden
		dataType: int64
		formatString: 0
		lineageTag: d41ba262-a669-4b92-b529-ce8c80eb619c
		summarizeBy: sum
		sourceColumn: orden

		annotation SummarizationSetBy = Automatic

	column creado_el
		dataType: dateTime
		formatString: Long Date
		lineageTag: 32d111c8-f9af-4529-85da-f85f092b4413
		summarizeBy: none
		sourceColumn: creado_el

		variation Variación
			isDefault
			relationship: 6acf8c47-d015-4af8-824f-c338cba03585
			defaultHierarchy: LocalDateTable_c40bc9ee-ccfc-49ad-a094-8c57fff3fd1b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fecha_de_aviso
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1251075d-eed1-4a9a-8d19-83d4b83bf3b0
		summarizeBy: none
		sourceColumn: fecha_de_aviso

		variation Variación
			isDefault
			relationship: 78447037-bfe9-458d-96b1-2d1c87048e64
			defaultHierarchy: LocalDateTable_0682300b-4298-46bc-89c2-97863e03836d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_del_aviso
		dataType: dateTime
		formatString: Long Time
		lineageTag: 62478b34-d91a-4b84-b7c2-d9d74b34afde
		summarizeBy: none
		sourceColumn: hora_del_aviso

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column creado_por
		dataType: string
		lineageTag: 75426ecf-7502-4bc0-b70b-436ba6c3b8d5
		summarizeBy: none
		sourceColumn: creado_por

		annotation SummarizationSetBy = Automatic

	column grupo_planificacion
		dataType: string
		lineageTag: 8877cb49-9782-43fd-8b8b-b1f9a4d2284e
		summarizeBy: none
		sourceColumn: grupo_planificacion

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		lineageTag: b38267fa-2b0d-428d-a44f-457ceb6a4e5b
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	column poblacion
		dataType: string
		lineageTag: dac9fb28-86db-4d56-8421-4cc3d199423b
		summarizeBy: none
		sourceColumn: poblacion

		annotation SummarizationSetBy = Automatic

	column ubicacion_tecnica
		dataType: string
		lineageTag: 589dad52-ce28-4714-806a-18e2cced9500
		summarizeBy: none
		sourceColumn: ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column status_del_sistema
		dataType: string
		lineageTag: 36e81d8c-7890-452e-bfbf-2653e87d240a
		summarizeBy: none
		sourceColumn: status_del_sistema

		annotation SummarizationSetBy = Automatic

	column denominacion_de_la_ubicacion_tecnica
		dataType: string
		lineageTag: e946473c-630e-4301-b934-f341cc9dce69
		summarizeBy: none
		sourceColumn: denominacion_de_la_ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column fecha_de_referencia
		dataType: dateTime
		formatString: Long Date
		lineageTag: f6fc2d69-669e-4b28-b725-0d739a13c405
		summarizeBy: none
		sourceColumn: fecha_de_referencia

		variation Variación
			isDefault
			relationship: 2ed8aaa7-e634-4e40-bee4-4033d136867a
			defaultHierarchy: LocalDateTable_e347e876-76b9-4f33-8680-6e60e4db901b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column mes_tancament
		dataType: int64
		formatString: 0
		lineageTag: 8111612e-155a-42da-ae31-9bc5c10e2e6a
		summarizeBy: sum
		sourceColumn: mes_tancament

		annotation SummarizationSetBy = Automatic

	column any_tancament
		dataType: int64
		formatString: 0
		lineageTag: fd83abde-bf1a-42a3-8df0-c8d401f642ab
		summarizeBy: sum
		sourceColumn: any_tancament

		annotation SummarizationSetBy = Automatic

	column durada_dies
		dataType: int64
		formatString: 0
		lineageTag: bce6ab39-5126-4daa-af01-47cfe77021c6
		summarizeBy: sum
		sourceColumn: durada_dies

		annotation SummarizationSetBy = Automatic

	column Gerencia
		dataType: string
		lineageTag: 38ad37b1-207c-4267-8164-c8075b941328
		summarizeBy: none
		sourceColumn: Gerencia

		annotation SummarizationSetBy = Automatic

	partition fact_tfuita_tinst = m
		mode: import
		queryGroup: Auxiliares
		source = ```
				let
				    Origen = let
				    Union =
				        Table.Combine({
				            Tfuita_Tinst_2025,
				            Tfuita_Tinst_2026
				        }),
				 
				    Gerencia =
				        Table.AddColumn(
				            Union,
				            "Gerencia",
				            each
				                if [grupo_planificacion] = "GD1" then "Barcelona Nord"
				                else if [grupo_planificacion] = "GD2" then "Barcelona Sud"
				                else if [grupo_planificacion] = "GD5" then "Besòs"
				                else if [grupo_planificacion] = "GD3" then "Llobregat Nord"
				                else if [grupo_planificacion] = "G5" then "Llobregat Sud"
				                else null,
				            type text
				        ),
				    #"Filas filtradas" = Table.SelectRows(Gerencia, each ([status_del_sistema] = "MECE" or [status_del_sistema] = "MECE METR ORAS" or [status_del_sistema] = "MECE MIMP" or [status_del_sistema] = "MECE ORAS"))
				in
				    #"Filas filtradas"
				in
				    Origen
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

