table fact_consum_limitadores
	lineageTag: 48660881-6fc2-4643-8fde-f68597850263

	column 'Titular subministrament'
		dataType: string
		lineageTag: 806407df-4f77-4f55-a537-cf850ccead37
		summarizeBy: none
		sourceColumn: Titular subministrament

		annotation SummarizationSetBy = Automatic

	column DOP
		dataType: string
		lineageTag: b9e6c4cd-43d6-44a1-ad27-88702244955b
		summarizeBy: none
		sourceColumn: DOP

		annotation SummarizationSetBy = Automatic

	column 'Data instal·lació'
		dataType: string
		lineageTag: bd1883ad-ead1-4ab1-bdaf-797480d2dfaf
		summarizeBy: none
		sourceColumn: Data instal·lació

		annotation SummarizationSetBy = Automatic

	column 'Pol.subm'
		dataType: string
		lineageTag: dff3f06a-6960-446a-8484-0e823cf4c6a6
		summarizeBy: none
		sourceColumn: Pol.subm

		annotation SummarizationSetBy = Automatic

	column 'Pol. ramal'
		dataType: string
		lineageTag: bc8741db-27eb-4371-95da-bba34aea13e6
		summarizeBy: none
		sourceColumn: Pol. ramal

		annotation SummarizationSetBy = Automatic

	column 'Cabal contractat (m3/h)'
		dataType: double
		lineageTag: 97b46701-e856-406a-9039-b294766f1223
		summarizeBy: sum
		sourceColumn: Cabal contractat (m3/h)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mitjana cabal màxim pre (m³/h)'
		dataType: string
		lineageTag: 72b22ac5-f788-4318-a990-3ac68432308f
		summarizeBy: none
		sourceColumn: Mitjana cabal màxim pre (m³/h)

		annotation SummarizationSetBy = Automatic

	column 'Mitjana cabal màxim post (m³/h)'
		dataType: string
		lineageTag: ae067a62-8a1f-4382-8dbd-435384614c5c
		summarizeBy: none
		sourceColumn: Mitjana cabal màxim post (m³/h)

		annotation SummarizationSetBy = Automatic

	column 'Consum mig diari(m3/d) '
		dataType: string
		lineageTag: 305d43dc-2a7b-4ad7-b236-36f69e71eb48
		summarizeBy: none
		sourceColumn: "Consum mig diari(m3/d) "

		annotation SummarizationSetBy = Automatic

	column 'Mitja consum diari post (m3/d) '
		dataType: double
		lineageTag: 5f322cac-b9c3-473c-ae57-6054f4aaeb54
		summarizeBy: sum
		sourceColumn: "Mitja consum diari post (m3/d) "

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cabal limitació'
		dataType: double
		lineageTag: 308764b7-77ff-4ac5-98c3-65e8227a4e2f
		summarizeBy: sum
		sourceColumn: Cabal limitació

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nº puntas Antes'
		dataType: string
		lineageTag: ba1bc310-b99b-4969-98fd-7debe4692665
		summarizeBy: none
		sourceColumn: Nº puntas Antes

		annotation SummarizationSetBy = Automatic

	column 'Nº puntas Despues limitacion'
		dataType: string
		lineageTag: f38fc3e3-337e-4dd8-8d8b-e47d9f4977ac
		summarizeBy: none
		sourceColumn: Nº puntas Despues limitacion

		annotation SummarizationSetBy = Automatic

	column Observacions
		dataType: string
		lineageTag: 47117d44-1c93-4d0d-ae08-19425e8c6496
		summarizeBy: none
		sourceColumn: Observacions

		annotation SummarizationSetBy = Automatic

	column 'Resultat canvi de contracte (€/any)'
		dataType: string
		lineageTag: f4a28f0a-e11a-44ef-becd-01c22bf481b8
		summarizeBy: none
		sourceColumn: Resultat canvi de contracte (€/any)

		annotation SummarizationSetBy = Automatic

	column COMENTARIS
		dataType: string
		lineageTag: c7db9478-ebae-40a4-b6bf-084b6868b90f
		summarizeBy: none
		sourceColumn: COMENTARIS

		annotation SummarizationSetBy = Automatic

	column 1,8
		dataType: double
		lineageTag: 6fd5a52a-2e0a-45cf-a593-18c67dfa2966
		summarizeBy: sum
		sourceColumn: 1,8

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_consum_limitadores = m
		mode: import
		queryGroup: Hechos
		source = ```
				let
				    // 1. Carga y navegación
				    Origen = GoogleSheets.Contents(Consum_limitadores),
				    Navegacion = Origen{[name = "resumen limitaciones", ItemKind = "Table"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(Navegacion, each ([Column2] <> "")),
				 
				    // 2. Rellenado y estructuración inicial
				    TipoInicial = Table.TransformColumnTypes(#"Filas filtradas", {{"Column21", type number}}),
				    Rellenado = Table.FillDown(TipoInicial, {"Column21"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Rellenado,{{"Column4", type text}}),
				    #"Filas filtradas1" = Table.SelectRows(#"Tipo cambiado", each ([Column3] <> "????")),
				    Encabezados = Table.PromoteHeaders(#"Filas filtradas1", [PromoteAllScalars = true]),
				    #"Errores reemplazados" = Table.ReplaceErrorValues(Encabezados, {{"Cabal limitació", ""}}),
				    #"Errores reemplazados1" = Table.ReplaceErrorValues(#"Errores reemplazados", {{"Mitjana cabal màxim post (m³/h)", ""}}),
				    #"Errores reemplazados2" = Table.ReplaceErrorValues(#"Errores reemplazados1", {{"Mitja consum diari post (m3/d) ", ""}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Errores reemplazados2",{"Dif (m3/d)", "Dif (m3/any)", "Dif (€/any)", "Dif (%/any)"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Columnas quitadas","-","",Replacer.ReplaceValue,{"Mitja consum diari post (m3/d) "}),
				    #"Tipo cambiado4" = Table.TransformColumnTypes(#"Valor reemplazado4",{{"Mitja consum diari post (m3/d) ", type number}, {"Cabal limitació", type number}, {"Titular subministrament", type text}, {"DOP", type text}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado4","10/16","",Replacer.ReplaceValue,{"Cabal contractat (m3/h)"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","10 (16 LIMITADOR)","",Replacer.ReplaceValue,{"Cabal contractat (m3/h)"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","16/25","",Replacer.ReplaceValue,{"Cabal contractat (m3/h)"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","6,3/10","",Replacer.ReplaceValue,{"Cabal contractat (m3/h)"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado3",{{"Cabal contractat (m3/h)", type number}})
				in
				    #"Tipo cambiado1"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

