table fact_aigua_no_registrada_mensual
	lineageTag: f96f2e5b-1cad-4714-b87a-0b7f4562ce64

	column sector_id
		dataType: string
		lineageTag: 81776734-9feb-42fa-8a73-f10a60e150fd
		summarizeBy: none
		sourceColumn: sector_id

		annotation SummarizationSetBy = Automatic

	column gerencia
		dataType: string
		lineageTag: 33397c83-3084-446d-8603-c22d95df5769
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	column sectors
		dataType: string
		lineageTag: 166a9dea-1245-4a08-9059-7effbdf91d30
		summarizeBy: none
		sourceColumn: sectors

		annotation SummarizationSetBy = Automatic

	column valor
		dataType: string
		lineageTag: d59361f4-0971-495c-989f-73e071b71af0
		summarizeBy: none
		sourceColumn: valor

		annotation SummarizationSetBy = Automatic

	column pis_pressio
		dataType: string
		lineageTag: ab15dedd-0d86-4efe-bd29-916a1a6445d8
		summarizeBy: none
		sourceColumn: pis_pressio

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: string
		lineageTag: b94079c6-1ddf-451a-a7f2-dfe9ad8bf69c
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

	partition fact_aigua_no_registrada_mensual = m
		mode: import
		source =
				let
				    // Origen
				    Origen =
				        GoogleSheets.Contents(
				            "https://docs.google.com/spreadsheets/d/1ZffEmnNoWOUZV2BWTDYGZTjcNVbZ07il0J7N43DN_IU/edit?gid=1960240863#gid=1960240863"
				        ),
				
				    Datos = Origen{[name="Aigua No Registrada", ItemKind="Table"]}[Data],
				
				    // Quitar primeras filas y promover encabezados
				    Datos2 = Table.PromoteHeaders(Table.Skip(Datos, 2), [PromoteAllScalars = true]),
				
				    // Quitar columnas vacías
				    Datos3 = Table.RemoveColumns(Datos2, List.Select(Table.ColumnNames(Datos2), each _ = "")),
				
				    // Filtrar filas válidas
				    Datos4 = Table.SelectRows(Datos3, each ([Nº] <> "")),
				
				    // Unpivot dinámico
				    Datos5 =
				        Table.UnpivotOtherColumns(
				            Datos4,
				            {"Nº", "Gerència", "Pis Pressió", "Sectors"},
				            "atributo",
				            "valor"
				        ),
				
				    // Reemplazar errores en la columna valor
				    Datos6 = Table.ReplaceErrorValues(Datos5, {{"valor", 0}}),
				
				    // Normalizar nombres
				    Datos7 =
				        Table.TransformColumnNames(
				            Datos6,
				            each Text.Replace(Text.Lower(_), " ", "_")
				        ),
				
				    // Renombrados finales
				    Resultado =
				        Table.RenameColumns(Datos7,{{"nº", "sector_id"}, {"gerència", "gerencia"}, {"pis_pressió", "pis_pressio"}, {"atributo", "fecha"}})
				in
				    Resultado

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

