table fact_anr_global_acum
	lineageTag: b9338bb5-df5a-4911-a628-9396a160ed6d

	column date
		dataType: dateTime
		isHidden
		formatString: yyyy-mm
		lineageTag: e6cdf6df-3239-4f94-918f-1e3baff9c509
		summarizeBy: none
		sourceColumn: date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column lliurada_hm3
		dataType: double
		lineageTag: 1a826152-210a-4d6f-b26a-e63f50d5c45a
		summarizeBy: none
		sourceColumn: lliurada_hm3

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consumida_hm3
		dataType: double
		lineageTag: 041610aa-2059-40d3-bee1-420f72d0bd00
		summarizeBy: none
		sourceColumn: consumida_hm3

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rth_global
		dataType: double
		lineageTag: c5e7afb9-e525-446b-8419-7e61536b0420
		summarizeBy: none
		sourceColumn: rth_global

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anr_global_hm3
		dataType: double
		lineageTag: 50496d1e-db14-464f-83f9-7c21834eb688
		summarizeBy: none
		sourceColumn: anr_global_hm3

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_anr_global_acum = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vRS1zkWHKwzcm2ZLhnMstWbjgJtQC3DCBLdSY_mCFGtR3x8Z4xdlut8iUNJwB5KVQ/pub?gid=315911922&single=true&output=csv"), [Delimiter = ",", Columns = 48, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				    Data = Table.PromoteHeaders(
				        Table.SelectColumns(
				            Table.Range(Source,20 , 13),
				            {"Column1", "Column2", "Column3", "Column4", "Column5"}
				        ),
				        [PromoteAllScalars = true]
				    ),
				    Result = Table.TransformColumnTypes(
				        Table.RenameColumns(
				            Data,
				            {
				                {"Any", "date"},
				                {"Aigua Lliurada (hm3)", "lliurada_hm3"},
				                {"Aigua Consumida (hm3)", "consumida_hm3"},
				                {"RTH Global", "rth_global"},
				                {"ANR Global (hm3)", "anr_global_hm3"}
				            }
				        ),
				        {
				            {"date", type date},
				            {"lliurada_hm3", type number},
				            {"consumida_hm3", type number},
				            {"rth_global", type number},
				            {"anr_global_hm3", type number}
				        }
				    )
				in
				    Result

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

