table fact_inventari_xarxa_mitjana_12m
	lineageTag: 3ba91347-40e9-443f-a0f7-cf3c1c908be9

	column nombre_escomeses_totals
		dataType: string
		lineageTag: c68e0452-4c37-483f-9aca-8b36bd4ed131
		summarizeBy: none
		sourceColumn: nombre_escomeses_totals

		annotation SummarizationSetBy = Automatic

	column nombre_subministraments_totals
		dataType: string
		lineageTag: cba49637-526d-4a50-8aaa-0e7cc64f592d
		summarizeBy: none
		sourceColumn: nombre_subministraments_totals

		annotation SummarizationSetBy = Automatic

	column l_+_t_km
		dataType: string
		lineageTag: dddf41a6-b0bb-45f5-a5a0-1838ad1ca7f0
		summarizeBy: none
		sourceColumn: l_+_t_km

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: string
		lineageTag: 10310712-e9a8-47bd-bc81-d8114c40ce82
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

	partition fact_inventari_xarxa_mitjana_12m = m
		mode: import
		source =
				let
				    // Origen
				    Origen = GoogleSheets.Contents(
				        "https://docs.google.com/spreadsheets/d/1LK5D7QclVwCBGy5-hONVLgP1GgW35okgrxNLr1kJCoE/edit?gid=664401204#gid=664401204"
				    ),
				    Datos = Origen{[name="Inventari xarxa", ItemKind="Table"]}[Data],
				
				    // Tomar filas y promover encabezados
				    DatosFiltrados = Table.PromoteHeaders(
				        Table.FirstN(Table.Skip(Datos, 393), 13),
				        [PromoteAllScalars = true]
				    ),
				
				    // Selección y renombrado en un solo bloque
				    Seleccion = Table.SelectColumns(
				        DatosFiltrados,
				        {
				            "Mes",
				            "L + T (km)",
				            "Nombre Escomeses Totals",
				            "Nombre Subministraments Totals"
				        }
				    ),
				
				    Renombradas = Table.RenameColumns(
				        Seleccion,
				        {
				            {"Mes", "fecha"},
				            {"L + T (km)", "L + T km"}
				        }
				    ),
				
				    // Normalización final
				    Normalizadas = Table.TransformColumnNames(
				        Renombradas,
				        each Text.Replace(Text.Lower(_), " ", "_")
				    )
				in
				    Normalizadas

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

