table fact_tfuita_tinst
	lineageTag: 2a30e6d2-2eba-4223-8ae7-cfe5dd751d5b

	column aviso
		dataType: int64
		formatString: 0
		lineageTag: e0cad0cd-dadd-4590-9663-e0e8a20843c8
		summarizeBy: sum
		sourceColumn: aviso

		annotation SummarizationSetBy = Automatic

	column clase_de_aviso
		dataType: string
		lineageTag: 519c2418-bd28-4a7f-932f-f8ca8b10fb7c
		summarizeBy: none
		sourceColumn: clase_de_aviso

		annotation SummarizationSetBy = Automatic

	column inicio_deseado
		dataType: dateTime
		formatString: Long Date
		lineageTag: 421e962a-14d6-4173-b53a-3b42f2727ee6
		summarizeBy: none
		sourceColumn: inicio_deseado

		variation Variación
			isDefault
			relationship: fd05e73b-efce-4536-9393-184e9afe0768
			defaultHierarchy: LocalDateTable_9a0a80e2-dd15-47a6-bbd0-09c26f5bb8f2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column inicio_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1de5b8ad-225c-41c1-b866-4c0632823b8e
		summarizeBy: none
		sourceColumn: inicio_de_averia

		variation Variación
			isDefault
			relationship: fcde0620-75b8-4e0f-bb67-8df3f54c0908
			defaultHierarchy: LocalDateTable_b3cc84e6-eab8-4324-9b7f-65f5f229c65c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_de_inicio_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: 1f832c12-c2e4-4a02-9a9d-b65fb9f1c975
		summarizeBy: none
		sourceColumn: hora_de_inicio_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column hora_de_fin_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: 97009579-aa92-4571-967c-40bea6d308eb
		summarizeBy: none
		sourceColumn: hora_de_fin_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column fin_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5500ef68-cb7f-4189-b1d4-55ad9c6936a4
		summarizeBy: none
		sourceColumn: fin_de_averia

		variation Variación
			isDefault
			relationship: 16cc9a11-2624-4723-a342-d6a94a111b13
			defaultHierarchy: LocalDateTable_687b3d9b-655b-4544-ac76-4866600c1773.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column orden
		dataType: int64
		formatString: 0
		lineageTag: 55a93d4f-7c65-4c8f-be6b-4f7c637d64c8
		summarizeBy: sum
		sourceColumn: orden

		annotation SummarizationSetBy = Automatic

	column creado_el
		dataType: dateTime
		formatString: Long Date
		lineageTag: d9cfcf7d-9a00-4ce4-8154-8b26123061c7
		summarizeBy: none
		sourceColumn: creado_el

		variation Variación
			isDefault
			relationship: 0d70b685-97de-4331-8839-732f6fa7b39d
			defaultHierarchy: LocalDateTable_e7cd250e-1860-4590-ab39-76b050dfb594.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fecha_de_aviso
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8f225a8b-f92a-41f2-adb6-b8c4ace40487
		summarizeBy: none
		sourceColumn: fecha_de_aviso

		variation Variación
			isDefault
			relationship: e2e9f2d8-6bdc-4441-bd42-794d9d39bfe1
			defaultHierarchy: LocalDateTable_e1b46833-4b1f-4cbc-87ca-3325a434569a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_del_aviso
		dataType: dateTime
		formatString: Long Time
		lineageTag: 1d99c765-75fc-4cd8-889f-73f1646f2a15
		summarizeBy: none
		sourceColumn: hora_del_aviso

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column creado_por
		dataType: string
		lineageTag: 1388a291-279b-4252-b328-8a408cb1e501
		summarizeBy: none
		sourceColumn: creado_por

		annotation SummarizationSetBy = Automatic

	column grupo_planificacion
		dataType: string
		lineageTag: 12ac0089-5b48-4bfd-aa39-53cea0413308
		summarizeBy: none
		sourceColumn: grupo_planificacion

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		lineageTag: 5bcecc47-23a1-4320-b840-e220b2fe9efe
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	column poblacion
		dataType: string
		lineageTag: 8cca4ec4-1d6f-4f17-9f90-397d7c667403
		summarizeBy: none
		sourceColumn: poblacion

		annotation SummarizationSetBy = Automatic

	column ubicacion_tecnica
		dataType: string
		lineageTag: 000bbe88-47ae-4c28-9da5-7cea13c246f6
		summarizeBy: none
		sourceColumn: ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column status_del_sistema
		dataType: string
		lineageTag: af479849-4e01-4ff0-9549-81c40192a87e
		summarizeBy: none
		sourceColumn: status_del_sistema

		annotation SummarizationSetBy = Automatic

	column denominacion_de_la_ubicacion_tecnica
		dataType: string
		lineageTag: 19cdc0d0-a787-47e9-8c38-77c46e32abca
		summarizeBy: none
		sourceColumn: denominacion_de_la_ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column fecha_de_referencia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4d13572d-a126-436d-b566-8d609bb44592
		summarizeBy: none
		sourceColumn: fecha_de_referencia

		variation Variación
			isDefault
			relationship: 1ce2fed8-3099-44d6-b3aa-f746c7e3b479
			defaultHierarchy: LocalDateTable_9974401e-0612-49da-a1a4-42a6f9a89e43.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column mes_tancament
		dataType: int64
		formatString: 0
		lineageTag: 18ab862f-f557-42da-bf38-4e6da3cdf43e
		summarizeBy: sum
		sourceColumn: mes_tancament

		annotation SummarizationSetBy = Automatic

	column any_tancament
		dataType: int64
		formatString: 0
		lineageTag: afa3579a-b22d-4bee-95a7-d33e92c5398e
		summarizeBy: sum
		sourceColumn: any_tancament

		annotation SummarizationSetBy = Automatic

	column durada_dies
		dataType: int64
		formatString: 0
		lineageTag: 5ecb91f9-adbc-47f7-90b7-4520da076eb8
		summarizeBy: sum
		sourceColumn: durada_dies

		annotation SummarizationSetBy = Automatic

	column Gerencia
		dataType: string
		lineageTag: 23292b4e-ea4e-4300-a9ea-a62270146dba
		summarizeBy: none
		sourceColumn: Gerencia

		annotation SummarizationSetBy = Automatic

	partition fact_tfuita_tinst = m
		mode: import
		queryGroup: Hechos
		source =
				let
				    Union =
				        Table.Combine({
				            Tfuita_Tinst_2025,
				            Tfuita_Tinst_2026
				        }),
				
				    Gerencia =
				        Table.AddColumn(
				            Union,
				            "Gerencia",
				            each
				                if [grupo_planificacion] = "GD1" then "Barcelona Nord"
				                else if [grupo_planificacion] = "GD2" then "Barcelona Sud"
				                else if [grupo_planificacion] = "GD5" then "Besòs"
				                else if [grupo_planificacion] = "GD3" then "Llobregat Nord"
				                else if [grupo_planificacion] = "G5" then "Llobregat Sud"
				                else null,
				            type text
				        ),
				    #"Filas filtradas" = Table.SelectRows(Gerencia, each ([status_del_sistema] = "MECE" or [status_del_sistema] = "MECE METR ORAS" or [status_del_sistema] = "MECE MIMP" or [status_del_sistema] = "MECE ORAS"))
				in
				    #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

