table fact_aigua_consum_historic
	lineageTag: c5b90948-c675-48c2-9f75-8cf2ee3950d6

	column fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 14168cf3-10e7-4172-97fe-406fd3e3b735
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column aigua_lliurada_total
		dataType: double
		lineageTag: cbddf428-a937-4d9c-a9d3-de97f5287356
		summarizeBy: sum
		sourceColumn: aigua_lliurada_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aigua_consumida_total
		dataType: double
		lineageTag: 96a17789-eb8a-4c21-a548-484df4c0aaf4
		summarizeBy: sum
		sourceColumn: aigua_consumida_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rendiment_mes
		dataType: double
		lineageTag: 5d6dabe2-24f6-4f50-8114-927742dcc694
		summarizeBy: sum
		sourceColumn: rendiment_mes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rendiment_12_umc
		dataType: double
		lineageTag: 61cae661-9886-4065-890a-ee7105e01952
		summarizeBy: sum
		sourceColumn: rendiment_12_umc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anr_mes
		dataType: double
		lineageTag: aebee7fd-7c16-4d03-bd39-f459fe7b23a4
		summarizeBy: sum
		sourceColumn: anr_mes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column anr_12_umc
		dataType: double
		lineageTag: 2b380fb5-fb8e-4c7e-8bbc-c76fa2588299
		summarizeBy: sum
		sourceColumn: anr_12_umc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aigua_consumida_baixa
		dataType: double
		lineageTag: f3d86616-6ae4-4afc-b4e4-fa60af7ce642
		summarizeBy: sum
		sourceColumn: aigua_consumida_baixa

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aigua_consumida_alta
		dataType: double
		lineageTag: 065f1316-2c09-4778-af26-e24cd5c5f773
		summarizeBy: sum
		sourceColumn: aigua_consumida_alta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aigua_consumida_acf
		dataType: double
		lineageTag: 7a1a8edf-6778-4f7e-a220-247c4cfc47fc
		summarizeBy: sum
		sourceColumn: aigua_consumida_acf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aigua_consumida_peatges
		dataType: double
		lineageTag: 86f3dfa4-e593-4864-9f6c-c39dc1e478e0
		summarizeBy: sum
		sourceColumn: aigua_consumida_peatges

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aigua_consumida_autoconsum
		dataType: double
		lineageTag: 1cb984f6-a45f-411c-9132-beb56a80d9be
		summarizeBy: sum
		sourceColumn: aigua_consumida_autoconsum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_aigua_consum_historic = m
		mode: import
		queryGroup: Hechos
		source =
				let
				    // Origen
				    Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1GcZpQqbGihEftG7cP56wk9-AIIv07FLtQQT95_s6ZJw/edit?gid=763204073#gid=763204073"),
				    Tabla = Origen{[name="Històric Mesos", ItemKind="Table"]}[Data],
				    #"Filas superiores quitadas" = Table.Skip(Tabla,1),
				    #"Filas filtradas" = Table.SelectRows(#"Filas superiores quitadas", each ([Column4] <> "")),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Filas filtradas",{"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14"}),
				
				    //==============================
				    // CABECERAS (2 primeras filas)
				    //==============================
				    Cabeceras = Table.FirstN(#"Otras columnas quitadas",2),
				
				    //Rellenar horizontalmente la primera fila
				    CabTrans = Table.Transpose(Cabeceras),
				    // Convertir cadenas vacías en null
				    CabTrans2 =
				        Table.TransformColumns(
				            CabTrans,
				            {
				                {
				                    "Column1",
				                    each
				                        if _ = null or Text.Trim(Text.From(_)) = ""
				                        then null
				                        else _,
				                    type nullable text
				                }
				            }
				        ),
				    // Ahora sí funciona correctamente
				    Fill = Table.FillDown(CabTrans2, {"Column1"}),
				    CabFinal = Table.Transpose(Fill),
				
				    //Convertir las dos filas en listas
				    Fila1 = Record.ToList(CabFinal{0}),
				    Fila2 = Record.ToList(CabFinal{1}),
				    // Construir nombres
				    NuevosNombres =
				    List.Transform(
				        List.Positions(Fila1),
				        (i) =>
				            let
				                c1 = Text.Trim(Text.From(Fila1{i})),
				                c2 = Text.Trim(Text.From(Fila2{i}))
				            in
				                if i = 0 then
				                    "Anyo"
				                else if i = 1 then
				                    "Fecha"
				                else if c2 = "" then
				                    c1
				                else
				                    c1 & " - " & c2
				    ),
				    //==============================
				    // DATOS
				    //==============================
				    Datos = Table.Skip(#"Otras columnas quitadas",2),
				
				    //Asignar nombres
				    Resultado = Table.RenameColumns(
				        Datos,
				        List.Zip({Table.ColumnNames(Datos), NuevosNombres}),
				        MissingField.Ignore
				    ),
				
				    #"Solo fechas" =
				    Table.SelectRows(
				        Resultado,
				        each
				            let
				                t = Text.Trim(Text.From([Fecha]))
				            in
				                Text.Length(t) = 10 and
				                Text.Middle(t,2,1) = "/" and
				                Text.Middle(t,5,1) = "/"
				    ),
				    #"Otras columnas quitadas1" = Table.SelectColumns(#"Solo fechas",{"Anyo", "Fecha", "Aigua Lliurada", "Aigua Consumida - En Baixa", "Aigua Consumida - En Alta", "Aigua Consumida - A.C.F.", "Aigua Consumida - Peatges", "Aigua Consumida - Autoconsum", "Aigua Consumida - Total", "Rendiment - Mes", "Rendiment - 12 UMC", "ANR - Mes", "ANR - 12UMC"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Otras columnas quitadas1", each ([#"Rendiment - 12 UMC"] <> "---")),
				
				    #"Columnas quitadas" = Table.RemoveColumns(#"Filas filtradas1",{"Anyo"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{"Aigua Lliurada", "aigua_lliurada_total"}, {"Fecha", "fecha"}, {"Aigua Consumida - Total", "aigua_consumida_total"}, {"Rendiment - Mes", "rendiment_mes"}, {"Rendiment - 12 UMC", "rendiment_12_umc"}, {"ANR - 12UMC", "anr_12_umc"}, {"ANR - Mes", "anr_mes"}, {"Aigua Consumida - En Baixa", "aigua_consumida_baixa"}, {"Aigua Consumida - En Alta", "aigua_consumida_alta"}, {"Aigua Consumida - A.C.F.", "aigua_consumida_acf"}, {"Aigua Consumida - Peatges", "aigua_consumida_peatges"}, {"Aigua Consumida - Autoconsum", "aigua_consumida_autoconsum"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","",0,Replacer.ReplaceValue,{"aigua_consumida_autoconsum"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Valor reemplazado",{{"aigua_lliurada_total", type number}, {"aigua_consumida_baixa", type number}, {"aigua_consumida_alta", type number}, {"aigua_consumida_acf", type number}, {"aigua_consumida_peatges", type number}, {"aigua_consumida_autoconsum", type number}, {"aigua_consumida_total", type number}, {"rendiment_mes", type number}, {"rendiment_12_umc", type number}, {"anr_mes", type number}, {"anr_12_umc", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

