table fact_inventari_xarxa_mitjana_12m
	lineageTag: 3ba91347-40e9-443f-a0f7-cf3c1c908be9

	column Mes
		dataType: string
		lineageTag: 857771a0-39c6-42ce-907f-dd89165172e2
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'L (km) '
		dataType: string
		lineageTag: 368cfbeb-2513-4af8-aded-2f1613733aa9
		summarizeBy: none
		sourceColumn: "L (km) "

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses'
		dataType: string
		lineageTag: ee9762dd-cec0-4c18-b099-2ff6b71b39aa
		summarizeBy: none
		sourceColumn: Nombre escomeses

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin.'
		dataType: string
		lineageTag: 30f9215f-abe4-4929-87c6-ae6ad8b09717
		summarizeBy: none
		sourceColumn: Nombre Submin.

		annotation SummarizationSetBy = Automatic

	column 'L (km) _1'
		dataType: string
		lineageTag: 72ac2fdd-6bf8-41d0-962d-461fe415fef2
		summarizeBy: none
		sourceColumn: L (km) _1

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses_2'
		dataType: string
		lineageTag: bedf410d-c551-49de-8e1b-988d9bc149ba
		summarizeBy: none
		sourceColumn: Nombre escomeses_2

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin._3'
		dataType: string
		lineageTag: 11449c3a-9747-4b5c-8c1d-6bedd78e7b15
		summarizeBy: none
		sourceColumn: Nombre Submin._3

		annotation SummarizationSetBy = Automatic

	column 'L (km) _4'
		dataType: string
		lineageTag: 57b27b13-27ac-486e-8d37-b5fccfac681e
		summarizeBy: none
		sourceColumn: L (km) _4

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses_5'
		dataType: string
		lineageTag: 593a8b21-977c-4190-b085-b244ca29354c
		summarizeBy: none
		sourceColumn: Nombre escomeses_5

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin._6'
		dataType: string
		lineageTag: b1bd2bd1-9796-496e-b1f6-ca1bbb58abd9
		summarizeBy: none
		sourceColumn: Nombre Submin._6

		annotation SummarizationSetBy = Automatic

	column 'L (km) _7'
		dataType: string
		lineageTag: 667afc5b-b253-4ea2-9770-73845d981d03
		summarizeBy: none
		sourceColumn: L (km) _7

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses_8'
		dataType: string
		lineageTag: 399f6188-0c8d-469a-a625-2976c59dcb3c
		summarizeBy: none
		sourceColumn: Nombre escomeses_8

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin._9'
		dataType: string
		lineageTag: 1537d7ce-b323-40fc-8afa-5b64c4d62c4e
		summarizeBy: none
		sourceColumn: Nombre Submin._9

		annotation SummarizationSetBy = Automatic

	column 'L (km) _10'
		dataType: string
		lineageTag: 0fa8789a-bff0-4432-a8e7-d315e5139e10
		summarizeBy: none
		sourceColumn: L (km) _10

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses_11'
		dataType: string
		lineageTag: 1eb87d68-dbda-4747-aa53-2166cefef6a1
		summarizeBy: none
		sourceColumn: Nombre escomeses_11

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin._12'
		dataType: string
		lineageTag: e517b075-cf10-4386-97f9-521f5950411f
		summarizeBy: none
		sourceColumn: Nombre Submin._12

		annotation SummarizationSetBy = Automatic

	column 'L (km) _13'
		dataType: string
		lineageTag: e3969227-cec5-4fda-a944-431b0e92a35e
		summarizeBy: none
		sourceColumn: L (km) _13

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses_14'
		dataType: string
		lineageTag: a553a7e2-d6be-4a0a-81df-a4146150ff8e
		summarizeBy: none
		sourceColumn: Nombre escomeses_14

		annotation SummarizationSetBy = Automatic

	column 'Nombre Submin._15'
		dataType: string
		lineageTag: fb893fca-38e9-4bca-8bcd-2a43672addbe
		summarizeBy: none
		sourceColumn: Nombre Submin._15

		annotation SummarizationSetBy = Automatic

	column 'L (km) _16'
		dataType: string
		lineageTag: 2c9eb63c-f6fb-49c1-a663-6e1eaf434b45
		summarizeBy: none
		sourceColumn: L (km) _16

		annotation SummarizationSetBy = Automatic

	column 'Nombre escomeses Controlades'
		dataType: string
		lineageTag: 2e199779-60ab-4cc6-a635-99a673f98a6d
		summarizeBy: none
		sourceColumn: Nombre escomeses Controlades

		annotation SummarizationSetBy = Automatic

	column 'Nombre Subministraments Controlades'
		dataType: string
		lineageTag: f41f8544-dec9-464a-8813-46a0c3c32d43
		summarizeBy: none
		sourceColumn: Nombre Subministraments Controlades

		annotation SummarizationSetBy = Automatic

	column 'L (km)'
		dataType: string
		lineageTag: 41cbd558-61a5-4867-9317-2daf9e64f09e
		summarizeBy: none
		sourceColumn: L (km)

		annotation SummarizationSetBy = Automatic

	column 'L + T (km)'
		dataType: string
		lineageTag: aa28ca14-9a25-4ba4-9523-3ecd03be7639
		summarizeBy: none
		sourceColumn: L + T (km)

		annotation SummarizationSetBy = Automatic

	column 'Nombre Escomeses Totals'
		dataType: string
		lineageTag: f315f889-446a-4e67-8278-ef666abd1315
		summarizeBy: none
		sourceColumn: Nombre Escomeses Totals

		annotation SummarizationSetBy = Automatic

	column 'Nombre Subministraments Totals'
		dataType: string
		lineageTag: d1b2874c-5b3c-4d38-bbb0-9e5a5398db52
		summarizeBy: none
		sourceColumn: Nombre Subministraments Totals

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: ef0396ad-1533-4f35-820d-f0361b4bfe55
		summarizeBy: none
		sourceColumn: fecha

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_inventari_xarxa_mitjana_12m = m
		mode: import
		source = ```
				let
				  Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vQYF-6nyJqkaezSpkqBN_a0Qmxw1GysBfL8py3eq4WzwX0xzzitdfbvqMzf9D-0YQ/pub?gid=664401204&single=true&output=csv"),[Delimiter=",", Columns=48, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Filas superiores quitadas" = Table.Skip(Origen,394),
				    #"Conservar filas superiores" = Table.FirstN(#"Filas superiores quitadas",13),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Conservar filas superiores", [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"Mes", "L (km) ", "Nombre escomeses", "Nombre Submin.", "L (km) _1", "Nombre escomeses_2", "Nombre Submin._3", "L (km) _4", "Nombre escomeses_5", "Nombre Submin._6", "L (km) _7", "Nombre escomeses_8", "Nombre Submin._9", "L (km) _10", "Nombre escomeses_11", "Nombre Submin._12", "L (km) _13", "Nombre escomeses_14", "Nombre Submin._15", "L (km) _16", "Nombre escomeses Controlades", "Nombre Subministraments Controlades", "L (km)", "L + T (km)", "Nombre Escomeses Totals", "Nombre Subministraments Totals"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Otras columnas quitadas", "fecha", each let
				    txt0  = [Mes],
				    // pasar a minúsculas
				    txt1  = Text.Lower(txt0),
				    // quitar "de ", "d’" y puntos
				    txt2  = Text.Replace(Text.Replace(Text.Replace(txt1,"de ",""),"d’",""),".",""),
				    // separar mes y año por el guion -
				    mesTxt = Text.BeforeDelimiter(txt2,"-"),
				    anioTxt = Text.AfterDelimiter(txt2,"-"),
				    // convertir año tipo "21" -> 2021
				    anio = 2000 + Number.FromText(anioTxt),
				    // mapear mes catalán -> número
				    mes = 
				        if mesTxt = "gen"  then 1 else
				        if mesTxt = "febr" then 2 else
				        if mesTxt = "març" then 3 else
				        if mesTxt = "abr"  then 4 else
				        if mesTxt = "maig" then 5 else
				        if mesTxt = "juny" then 6 else
				        if mesTxt = "jul"  then 7 else
				        if mesTxt = "ag"   then 8 else
				        if mesTxt = "set"  then 9 else
				        if mesTxt = "oct"  then 10 else
				        if mesTxt = "nov"  then 11 else
				        if mesTxt = "des"  then 12 else
				        null
				in
				    #date(anio, mes, 1))
				in
				    #"Personalizada agregada"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

