table 'resumen limitaciones'
	lineageTag: ecfe764e-2b00-42f0-a431-66ec9329fd22

	column titular_subministro
		dataType: string
		lineageTag: 3c765081-e7d0-4c68-8d2c-3a9df7f0dae3
		summarizeBy: none
		sourceColumn: titular_subministro

		annotation SummarizationSetBy = Automatic

	column gerencia
		dataType: string
		lineageTag: ad42ed95-134f-4a90-9fe6-f2225a62a820
		summarizeBy: none
		sourceColumn: gerencia

		annotation SummarizationSetBy = Automatic

	column data_instal
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3fb516c1-9d72-4e31-b738-39eb6475482c
		summarizeBy: none
		sourceColumn: data_instal

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column polissa_subm
		dataType: string
		lineageTag: 835540c7-008c-45fe-a082-e192eef09f80
		summarizeBy: none
		sourceColumn: polissa_subm

		annotation SummarizationSetBy = Automatic

	column polissa_ramal
		dataType: string
		lineageTag: 504dc752-62af-4ccc-b1b1-520c8d8d648c
		summarizeBy: none
		sourceColumn: polissa_ramal

		annotation SummarizationSetBy = Automatic

	column cabal_contract_m3/h
		dataType: double
		lineageTag: 35060910-e107-43aa-b2e7-e197c1788d65
		summarizeBy: sum
		sourceColumn: cabal_contract_m3/h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mitjana_cabal_maxi_pre_(m³/h)
		dataType: double
		lineageTag: 81e8cbae-ff7c-42c9-8b94-07fa5a4795d5
		summarizeBy: sum
		sourceColumn: mitjana_cabal_maxi_pre_(m³/h)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mitjana_cabal_maxi_post_(m³/h)
		dataType: double
		lineageTag: 79ab9e51-8dfb-4de9-badd-b3b7f2f8d785
		summarizeBy: sum
		sourceColumn: mitjana_cabal_maxi_post_(m³/h)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consum_mig_diari(m3/d)
		dataType: double
		lineageTag: 74784595-3acb-483b-b89c-252e8dbf4316
		summarizeBy: sum
		sourceColumn: consum_mig_diari(m3/d)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mitja_consum_diari_post_(m3/d)
		dataType: double
		lineageTag: 95cfb612-c659-495c-9b47-c68cb08decb4
		summarizeBy: sum
		sourceColumn: mitja_consum_diari_post_(m3/d)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column coeficiente_euro
		dataType: double
		lineageTag: 4c22600c-52a0-4cb5-a9f0-e389364673f7
		summarizeBy: sum
		sourceColumn: coeficiente_euro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'resumen limitaciones' = m
		mode: import
		source =
				let
				    Origen = GoogleSheets.Contents(Consum_limitadores),
				    TablaOrigen = Origen{[name="resumen limitaciones",ItemKind="Table"]}[Data],
				    ErroresComoNull = Table.ReplaceErrorValues(TablaOrigen, List.Transform(Table.ColumnNames(TablaOrigen), each {_, null})),
				    TipoInicial = Table.TransformColumnTypes(ErroresComoNull, {{"Column21", type number}}),
				    Rellenado = Table.FillDown(TipoInicial, {"Column21"}),
				    Encabezados = Table.PromoteHeaders(Rellenado, [PromoteAllScalars = true]),
				    SinFilasVacias = Table.SelectRows(Encabezados, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    FiltrarDOP = Table.SelectRows(SinFilasVacias, each ([DOP] <> "")),
				    LimitarFilas = Table.Range(FiltrarDOP, 0, 156),
				    QuitarColumnas = Table.RemoveColumns(LimitarFilas, {"COMENTARIS", "Observacions", "Nº puntas Despues limitacion", "Nº puntas Antes", "Dif (m3/d)", "Dif (m3/any)", "Dif (€/any)", "Dif (%/any)", "Cabal limitació", "Resultat canvi de contracte (€/any)"}),
				    RenombrarColumnas = Table.RenameColumns(QuitarColumnas, {{"1,8", "coeficiente_euro"}, {"DOP", "gerencia"}, {"Data instal·lació", "data_instal"}, {"Pol.subm", "polissa_subm"}, {"Pol. ramal", "polissa_ramal"}, {"Cabal contractat (m3/h)", "cabal_contract_m3/h"}, {"Mitjana cabal màxim pre (m³/h)", "mitjana_cabal_maxi_pre_(m³/h)"}, {"Mitjana cabal màxim post (m³/h)", "mitjana_cabal_maxi_post_(m³/h)"}, {"Consum mig diari(m3/d) ", "consum_mig_diari(m3/d)"}, {"Mitja consum diari post (m3/d) ", "mitja_consum_diari_post_(m3/d)"}, {"Titular subministrament", "titular_subministro"}}),
				    ReemplazarGerencia = Table.ReplaceValue(RenombrarColumnas, each [gerencia], each if [gerencia] = "BCN N" then "Barcelona Nord" else if [gerencia] = "BCN S" or [gerencia] = "BCNS" then "Barcelona Sud" else if [gerencia] = "LLOB N" then "Llobregat Nord" else if [gerencia] = "LLOB S" then "Llobregat Sud" else if [gerencia] = "BES" then "Besòs" else [gerencia], Replacer.ReplaceValue, {"gerencia"}),
				    CorregirFechas = Table.ReplaceValue(ReemplazarGerencia, "????", #date(2100, 1, 1), Replacer.ReplaceValue, {"data_instal"}),
				    LimpiarPre = Table.TransformColumns(CorregirFechas, {{"mitjana_cabal_maxi_pre_(m³/h)", each try if _ = "-" or _ = "" or _ = null then 0 else _ otherwise 0, type number}}),
				    LimpiarPost = Table.TransformColumns(LimpiarPre, {{"mitjana_cabal_maxi_post_(m³/h)", each try if _ = "-" or _ = "" or _ = null then 0 else _ otherwise 0, type number}}),
				    LimpiarConsumPost = Table.TransformColumns(LimpiarPost, {{"mitja_consum_diari_post_(m3/d)", each try if _ = "-" or _ = "" or _ = null then 0 else _ otherwise 0, type number}}),
				    LimpiarConsumMig = Table.TransformColumns(LimpiarConsumPost, {{"consum_mig_diari(m3/d)", each try if _ = "-" or _ = "" or _ = null then 0 else _ otherwise 0, type number}}),
				    FilasFiltradas = Table.SelectRows(LimpiarConsumMig, each ([#"cabal_contract_m3/h"] <> "10 (16 LIMITADOR)" and [#"cabal_contract_m3/h"] <> "10/16" and [#"cabal_contract_m3/h"] <> "16/25" and [#"cabal_contract_m3/h"] <> "6,3/10")),
				    TiposFinales = Table.TransformColumnTypes(FilasFiltradas, {{"polissa_subm", type text}, {"polissa_ramal", type text}, {"data_instal", type date}, {"mitjana_cabal_maxi_pre_(m³/h)", type number}, {"mitjana_cabal_maxi_post_(m³/h)", type number}, {"consum_mig_diari(m3/d)", type number}, {"mitja_consum_diari_post_(m3/d)", type number}, {"titular_subministro", type text}, {"gerencia", type text}, {"cabal_contract_m3/h", type number}}),
				    ValorReemplazado = Table.ReplaceValue(TiposFinales, "-", "No Disponible", Replacer.ReplaceText, {"polissa_ramal"}),
				    ValorReemplazado2 = Table.ReplaceValue(ValorReemplazado, null, 0, Replacer.ReplaceValue, {"cabal_contract_m3/h"}),
				    ValorReemplazado1 = Table.ReplaceValue(ValorReemplazado2, "", "No Disponible", Replacer.ReplaceValue, {"polissa_ramal"}),
				    ValorReemplazado3 = Table.ReplaceValue(ValorReemplazado1, null, 0, Replacer.ReplaceValue, {"mitjana_cabal_maxi_post_(m³/h)"}),
				    TipoCambiado = Table.TransformColumnTypes(ValorReemplazado3, {{"mitja_consum_diari_post_(m3/d)", type number}}),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(TipoCambiado,{{"titular_subministro", Text.Proper, type text}})
				in
				    #"Poner En Mayúsculas Cada Palabra"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

