table Tfuita_Tinst_2025
	lineageTag: 9029d3a7-e09b-44bb-926d-5cca33cdefda

	column aviso
		dataType: int64
		formatString: 0
		lineageTag: d8678d68-d7e1-4b58-8cf5-5ca22a2a0dcd
		summarizeBy: sum
		sourceColumn: aviso

		annotation SummarizationSetBy = Automatic

	column clase_de_aviso
		dataType: string
		lineageTag: c2a4cb5f-e444-4817-bd76-a2a5e05113b3
		summarizeBy: none
		sourceColumn: clase_de_aviso

		annotation SummarizationSetBy = Automatic

	column inicio_deseado
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9211a0f4-3967-442e-ae06-1c747aa119d9
		summarizeBy: none
		sourceColumn: inicio_deseado

		variation Variación
			isDefault
			relationship: ee18cb31-aa21-4612-9f24-f3dc81b7b5d4
			defaultHierarchy: LocalDateTable_306fe0ea-8161-40cd-8dfd-fe758fdb1dfd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column inicio_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6b49e9b7-b2a0-48a0-902c-4a5840c21fbe
		summarizeBy: none
		sourceColumn: inicio_de_averia

		variation Variación
			isDefault
			relationship: 0db49582-9246-47ac-a3b0-fdb513eb5c9e
			defaultHierarchy: LocalDateTable_964b00e9-8933-4825-b37f-ae586e0c1738.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_de_inicio_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: 4369b448-a93c-4724-85f9-4f6b8ff812d6
		summarizeBy: none
		sourceColumn: hora_de_inicio_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column hora_de_fin_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: 8d72191e-51a5-4a7c-b1d7-89579ec0cb56
		summarizeBy: none
		sourceColumn: hora_de_fin_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column fin_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: a1d9888d-cd76-4b10-a5b3-bc1d2cdd2234
		summarizeBy: none
		sourceColumn: fin_de_averia

		variation Variación
			isDefault
			relationship: 2a1a4b91-8a9d-4135-aa85-f880502ad17f
			defaultHierarchy: LocalDateTable_4c52b8cb-dc8a-408a-aa88-09edb8451cbb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column orden
		dataType: int64
		formatString: 0
		lineageTag: d4d5e8ff-c71d-4e5c-8ad2-dd8d6c8f0cec
		summarizeBy: sum
		sourceColumn: orden

		annotation SummarizationSetBy = Automatic

	column creado_el
		dataType: dateTime
		formatString: Long Date
		lineageTag: 12457b5e-8371-4bae-af73-9a171cfa561c
		summarizeBy: none
		sourceColumn: creado_el

		variation Variación
			isDefault
			relationship: 9ae6565c-7bc8-4347-9c1b-a1002f566776
			defaultHierarchy: LocalDateTable_e6399120-4430-4204-bb55-7c29f929af07.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fecha_de_aviso
		dataType: dateTime
		formatString: Long Date
		lineageTag: e8ae5f82-ea27-4c89-83d5-8145b197c5af
		summarizeBy: none
		sourceColumn: fecha_de_aviso

		variation Variación
			isDefault
			relationship: 4a24110d-1250-43b2-a493-6b2248e0d553
			defaultHierarchy: LocalDateTable_4e7fc600-a728-4249-a3a0-e718e6b99149.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_del_aviso
		dataType: dateTime
		formatString: Long Time
		lineageTag: 9aea405f-6511-4a44-a7f1-a6704664f67e
		summarizeBy: none
		sourceColumn: hora_del_aviso

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column creado_por
		dataType: string
		lineageTag: ad6306fa-15ed-46c1-bd2d-3d86bbe38c9d
		summarizeBy: none
		sourceColumn: creado_por

		annotation SummarizationSetBy = Automatic

	column grupo_planificacion
		dataType: string
		lineageTag: 14101194-88c7-4816-a9a7-f85559bc3330
		summarizeBy: none
		sourceColumn: grupo_planificacion

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		lineageTag: 5527047d-1480-401f-9c7f-c650095de8ca
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	column poblacion
		dataType: string
		lineageTag: e0a3e405-100b-43df-8274-19fd7ba16c91
		summarizeBy: none
		sourceColumn: poblacion

		annotation SummarizationSetBy = Automatic

	column ubicacion_tecnica
		dataType: string
		lineageTag: 586340e0-e06e-417f-a81c-02b09d7246a0
		summarizeBy: none
		sourceColumn: ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column status_del_sistema
		dataType: string
		lineageTag: aab291a0-9603-465e-8d66-73b9d93cd067
		summarizeBy: none
		sourceColumn: status_del_sistema

		annotation SummarizationSetBy = Automatic

	column denominacion_de_la_ubicacion_tecnica
		dataType: string
		lineageTag: 1dafa633-01a1-40d7-9534-15a48e0adda9
		summarizeBy: none
		sourceColumn: denominacion_de_la_ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column fecha_de_referencia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 07342377-1a03-40ae-861d-a2f369fbf2ce
		summarizeBy: none
		sourceColumn: fecha_de_referencia

		variation Variación
			isDefault
			relationship: 50aab68b-25ab-49f6-8bab-64149e40eb65
			defaultHierarchy: LocalDateTable_74583d68-bf96-40f4-baea-640304c1a2b7.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column mes_tancament
		dataType: int64
		formatString: 0
		lineageTag: 06c5bc69-c6ab-4681-b454-d49ee4ccc6a6
		summarizeBy: sum
		sourceColumn: mes_tancament

		annotation SummarizationSetBy = Automatic

	column any_tancament
		dataType: int64
		formatString: 0
		lineageTag: 7c23d390-e209-4dea-9a2c-1b705fd5bbc5
		summarizeBy: sum
		sourceColumn: any_tancament

		annotation SummarizationSetBy = Automatic

	column durada_dies
		dataType: int64
		formatString: 0
		lineageTag: f2a00550-b2ae-40c8-b4a4-84948886ffc2
		summarizeBy: sum
		sourceColumn: durada_dies

		annotation SummarizationSetBy = Automatic

	partition Tfuita_Tinst_2025 = m
		mode: import
		queryGroup: Tfuita_Tinst
		source =
				let
				    Origen = GoogleSheets.Contents(#"12_S7 desembre 2025_Tfuita_Tinst"),
				    #"Dades IW59_Table" = Origen{[name="Dades IW59",ItemKind="Table"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(#"Dades IW59_Table",{"Column23"}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(
				        #"Columnas quitadas",
				        [PromoteAllScalars=true]
				    ),
				
				    // Renombrar todas las columnas
				    #"Columnas renombradas" = Table.TransformColumnNames(
				        #"Encabezados promovidos",
				        each
				            let
				                nombre = Text.Lower(_),
				
				                // Eliminar tildes
				                sinTildes = Text.Replace(
				                    Text.Replace(
				                        Text.Replace(
				                            Text.Replace(
				                                Text.Replace(nombre, "á", "a"),
				                                "é", "e"
				                            ),
				                            "í", "i"
				                        ),
				                        "ó", "o"
				                    ),
				                    "ú", "u"
				                ),
				
				                // Reemplazar caracteres por _
				                reemplazado = Text.Replace(
				                    Text.Replace(
				                        Text.Replace(
				                            Text.Replace(
				                                sinTildes,
				                                " ", "_"
				                            ),
				                            "(", "_"
				                        ),
				                        ")", "_"
				                    ),
				                    "-", "_"
				                ),
				
				                // Eliminar _ duplicados
				                limpio = Text.Combine(
				                    List.Select(
				                        Text.Split(reemplazado, "_"),
				                        each _ <> ""
				                    ),
				                    "_"
				                )
				            in
				                limpio
				    ),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas renombradas",{{"aviso", Int64.Type}, {"clase_de_aviso", type text}, {"inicio_deseado", type date}, {"inicio_de_averia", type date}, {"hora_de_inicio_de_averia", type time}, {"hora_de_fin_de_averia", type time}, {"fin_de_averia", type date}, {"orden", Int64.Type}, {"creado_el", type date}, {"fecha_de_aviso", type date}, {"hora_del_aviso", type time}, {"creado_por", type text}, {"grupo_planificacion", type text}, {"descripcion", type text}, {"poblacion", type text}, {"ubicacion_tecnica", type text}, {"status_del_sistema", type text}, {"denominacion_de_la_ubicacion_tecnica", type text}, {"fecha_de_referencia", type date}, {"mes_tancament", Int64.Type}, {"any_tancament", Int64.Type}, {"durada_dies", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

