table Tfuita_Tinst_2026
	lineageTag: dccf6e1d-3422-4889-ab96-083f93d85795

	column aviso
		dataType: int64
		formatString: 0
		lineageTag: bf98fc71-e1ea-4c6a-95e9-4556e2c6445a
		summarizeBy: none
		sourceColumn: aviso

		annotation SummarizationSetBy = Automatic

	column clase_de_aviso
		dataType: string
		lineageTag: d0f273eb-1ad6-4c65-8d06-a0913908c3af
		summarizeBy: none
		sourceColumn: clase_de_aviso

		annotation SummarizationSetBy = Automatic

	column inicio_deseado
		dataType: dateTime
		formatString: Long Date
		lineageTag: fbb384eb-c242-45ad-915f-3da38ee679e9
		summarizeBy: none
		sourceColumn: inicio_deseado

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column inicio_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: e10b3116-3889-4d32-83a5-b1bf003acf91
		summarizeBy: none
		sourceColumn: inicio_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_de_inicio_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: 4846b5e8-be14-4c00-a707-c6ce324fad79
		summarizeBy: none
		sourceColumn: hora_de_inicio_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column hora_de_fin_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: ee16afac-5947-4490-9116-36813bf745af
		summarizeBy: none
		sourceColumn: hora_de_fin_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column fin_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 58899dee-3399-4f5a-a358-f32d15c118a2
		summarizeBy: none
		sourceColumn: fin_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column orden
		dataType: int64
		formatString: 0
		lineageTag: bdc34f4b-36b5-4704-bcf6-733b1fe8fecf
		summarizeBy: sum
		sourceColumn: orden

		annotation SummarizationSetBy = Automatic

	column creado_el
		dataType: dateTime
		formatString: Long Date
		lineageTag: f8646c37-167d-484f-adf3-4dcd565fdac2
		summarizeBy: none
		sourceColumn: creado_el

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fecha_de_aviso
		dataType: dateTime
		formatString: Long Date
		lineageTag: 77295c8b-6929-4328-84df-89f0cdb32f8c
		summarizeBy: none
		sourceColumn: fecha_de_aviso

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_del_aviso
		dataType: dateTime
		formatString: Long Time
		lineageTag: ff4de546-a6fe-4b17-b4b0-1b8c9f449eb7
		summarizeBy: none
		sourceColumn: hora_del_aviso

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column creado_por
		dataType: string
		lineageTag: 2b2ba224-02ee-4af4-b4ce-d3d42306d3ce
		summarizeBy: none
		sourceColumn: creado_por

		annotation SummarizationSetBy = Automatic

	column grupo_planificacion
		dataType: string
		lineageTag: 5e6b3f38-6100-495d-aeef-e7cdef970b17
		summarizeBy: none
		sourceColumn: grupo_planificacion

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		lineageTag: 2e7ef944-4d2e-4261-9457-2af44e5b569d
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	column poblacion
		dataType: string
		lineageTag: 6a1016f3-ed87-4f55-93f7-e3fdc6620e5c
		summarizeBy: none
		sourceColumn: poblacion

		annotation SummarizationSetBy = Automatic

	column ubicacion_tecnica
		dataType: string
		lineageTag: e7d53f89-431c-4a7b-9941-babcfd54831c
		summarizeBy: none
		sourceColumn: ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column status_del_sistema
		dataType: string
		lineageTag: 84d7e79a-09a1-4c4d-b875-3d0ea1c34727
		summarizeBy: none
		sourceColumn: status_del_sistema

		annotation SummarizationSetBy = Automatic

	column denominacion_de_la_ubicacion_tecnica
		dataType: string
		lineageTag: f5bf01d0-ba1c-43b0-97f4-c73b8782b956
		summarizeBy: none
		sourceColumn: denominacion_de_la_ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column fecha_de_referencia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 35dad660-f8c6-4c45-b23d-1f6b3abf73b0
		summarizeBy: none
		sourceColumn: fecha_de_referencia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column mes_tancament
		dataType: int64
		formatString: 0
		lineageTag: b557daeb-470b-4a0c-8a76-0ba58d03f54d
		summarizeBy: sum
		sourceColumn: mes_tancament

		annotation SummarizationSetBy = Automatic

	column any_tancament
		dataType: int64
		formatString: 0
		lineageTag: ef831047-2dd5-48be-a19b-5b70ba6c8b06
		summarizeBy: sum
		sourceColumn: any_tancament

		annotation SummarizationSetBy = Automatic

	column durada_dies
		dataType: int64
		formatString: 0
		lineageTag: 8223b382-913d-4b59-8b38-5ea617d9fa53
		summarizeBy: sum
		sourceColumn: durada_dies

		annotation SummarizationSetBy = Automatic

	partition Tfuita_Tinst_2026 = m
		mode: import
		queryGroup: Auxiliares
		source = ```
				let
				    Origen = let
				    Origen = GoogleSheets.Contents(#"12_S7 desembre 2026_Tfuita_Tinst"),
				    #"Dades IW59_Table" = Origen{[name="Dades IW59",ItemKind="Table"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(#"Dades IW59_Table",{"Column23"}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(
				        #"Columnas quitadas",
				        [PromoteAllScalars=true]
				    ),
				 
				    // Renombrar todas las columnas
				    #"Columnas renombradas" = Table.TransformColumnNames(
				        #"Encabezados promovidos",
				        each
				            let
				                nombre = Text.Lower(_),
				 
				                // Eliminar tildes
				                sinTildes = Text.Replace(
				                    Text.Replace(
				                        Text.Replace(
				                            Text.Replace(
				                                Text.Replace(nombre, "á", "a"),
				                                "é", "e"
				                            ),
				                            "í", "i"
				                        ),
				                        "ó", "o"
				                    ),
				                    "ú", "u"
				                ),
				 
				                // Reemplazar caracteres por _
				                reemplazado = Text.Replace(
				                    Text.Replace(
				                        Text.Replace(
				                            Text.Replace(
				                                sinTildes,
				                                " ", "_"
				                            ),
				                            "(", "_"
				                        ),
				                        ")", "_"
				                    ),
				                    "-", "_"
				                ),
				 
				                // Eliminar _ duplicados
				                limpio = Text.Combine(
				                    List.Select(
				                        Text.Split(reemplazado, "_"),
				                        each _ <> ""
				                    ),
				                    "_"
				                )
				            in
				                limpio
				    ),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas renombradas",{{"aviso", Int64.Type}, {"clase_de_aviso", type text}, {"inicio_deseado", type date}, {"inicio_de_averia", type date}, {"hora_de_inicio_de_averia", type time}, {"hora_de_fin_de_averia", type time}, {"fin_de_averia", type date}, {"orden", Int64.Type}, {"creado_el", type date}, {"fecha_de_aviso", type date}, {"hora_del_aviso", type time}, {"creado_por", type text}, {"grupo_planificacion", type text}, {"descripcion", type text}, {"poblacion", type text}, {"ubicacion_tecnica", type text}, {"status_del_sistema", type text}, {"denominacion_de_la_ubicacion_tecnica", type text}, {"fecha_de_referencia", type date}, {"mes_tancament", Int64.Type}, {"any_tancament", Int64.Type}, {"durada_dies", Int64.Type}})
				in
				    #"Tipo cambiado"
				in
				    Origen
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

