table Tfuita_Tinst_2025
	lineageTag: 4dc2178d-3919-4c4f-9bbc-3200358e19df

	column aviso
		dataType: int64
		formatString: 0
		lineageTag: 39ccab07-f119-437b-98db-ddf52c2b5e25
		summarizeBy: sum
		sourceColumn: aviso

		annotation SummarizationSetBy = Automatic

	column clase_de_aviso
		dataType: string
		lineageTag: 7074c830-71e9-4461-b160-e30863b4e5e1
		summarizeBy: none
		sourceColumn: clase_de_aviso

		annotation SummarizationSetBy = Automatic

	column inicio_deseado
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0bdc4190-c996-4c04-8ffc-9f34da7bb3c6
		summarizeBy: none
		sourceColumn: inicio_deseado

		variation Variación
			isDefault
			relationship: 3e46602b-27ed-4905-ae40-03fa58a898d9
			defaultHierarchy: LocalDateTable_1df7d4f2-7d02-4e9c-a831-8e4db4e5f7f2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column inicio_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: d9e82e49-116f-418d-a6da-b75796c66cbd
		summarizeBy: none
		sourceColumn: inicio_de_averia

		variation Variación
			isDefault
			relationship: 6c09faa4-9919-41b5-8e0e-12e95ba31a10
			defaultHierarchy: LocalDateTable_cb62f932-ab42-42a2-94ff-b9ee24d19a20.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_de_inicio_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: 2f14ebab-3e1b-4749-a671-bc2600291244
		summarizeBy: none
		sourceColumn: hora_de_inicio_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column hora_de_fin_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: ff621f51-8db8-485d-bad3-f7f0e349bb3a
		summarizeBy: none
		sourceColumn: hora_de_fin_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column fin_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4903b1cf-485b-479d-9022-29a7cfa63e41
		summarizeBy: none
		sourceColumn: fin_de_averia

		variation Variación
			isDefault
			relationship: d00d2ef9-90b5-48b0-8612-ae8ebf40269e
			defaultHierarchy: LocalDateTable_057549f1-75a2-42bd-9b8d-2669ecba5fae.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column orden
		dataType: int64
		formatString: 0
		lineageTag: 1edacc20-dc52-41f7-9959-cb257f8a8966
		summarizeBy: sum
		sourceColumn: orden

		annotation SummarizationSetBy = Automatic

	column creado_el
		dataType: dateTime
		formatString: Long Date
		lineageTag: c806ec85-f96c-47d2-b060-4755b8d1d5e4
		summarizeBy: none
		sourceColumn: creado_el

		variation Variación
			isDefault
			relationship: ee4943f9-7f3c-47ed-81fe-cdf795ef4185
			defaultHierarchy: LocalDateTable_47bf05d9-af3a-4784-ba0a-5d7600944546.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fecha_de_aviso
		dataType: dateTime
		formatString: Long Date
		lineageTag: 867a53bf-e897-4625-b22e-4aca90743711
		summarizeBy: none
		sourceColumn: fecha_de_aviso

		variation Variación
			isDefault
			relationship: 22df0c21-6f06-4ea8-bbb7-ba491a3f3969
			defaultHierarchy: LocalDateTable_c92de276-191f-4797-acd4-af78c87511bb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_del_aviso
		dataType: dateTime
		formatString: Long Time
		lineageTag: 8ed7d03d-74b5-4d52-8c32-97a5f07d0c62
		summarizeBy: none
		sourceColumn: hora_del_aviso

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column creado_por
		dataType: string
		lineageTag: b5ac7b81-d11d-40ec-8776-dd26c56a8f9f
		summarizeBy: none
		sourceColumn: creado_por

		annotation SummarizationSetBy = Automatic

	column grupo_planificacion
		dataType: string
		lineageTag: d3db1bfe-d3cc-4b70-8e44-a4d7e6b3d154
		summarizeBy: none
		sourceColumn: grupo_planificacion

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		lineageTag: f2ed0730-9db7-4fbe-9512-c008571a8ebd
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	column poblacion
		dataType: string
		lineageTag: 80ee6b0a-d629-4275-bf7f-0f696093ab18
		summarizeBy: none
		sourceColumn: poblacion

		annotation SummarizationSetBy = Automatic

	column ubicacion_tecnica
		dataType: string
		lineageTag: 5211f8ee-0478-4120-ab08-01fde63026f4
		summarizeBy: none
		sourceColumn: ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column status_del_sistema
		dataType: string
		lineageTag: b494e573-21d7-4205-8a8e-86c9103ddb9f
		summarizeBy: none
		sourceColumn: status_del_sistema

		annotation SummarizationSetBy = Automatic

	column denominacion_de_la_ubicacion_tecnica
		dataType: string
		lineageTag: 5ed60907-d0ac-4a33-a3b1-52173cdd93c1
		summarizeBy: none
		sourceColumn: denominacion_de_la_ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column fecha_de_referencia
		dataType: dateTime
		formatString: Long Date
		lineageTag: b911fffe-9caa-45de-8be0-6bcae4a85c66
		summarizeBy: none
		sourceColumn: fecha_de_referencia

		variation Variación
			isDefault
			relationship: 9da1a799-8206-4d26-82f1-97e8fe824c09
			defaultHierarchy: LocalDateTable_41723570-4b3d-44bd-9c1f-8c588d8898ce.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column mes_tancament
		dataType: int64
		formatString: 0
		lineageTag: e0c5eeaf-34aa-4eb0-9056-e33a09856d0f
		summarizeBy: sum
		sourceColumn: mes_tancament

		annotation SummarizationSetBy = Automatic

	column any_tancament
		dataType: int64
		formatString: 0
		lineageTag: 3bccd217-11ea-4574-9c41-4ac997bacb94
		summarizeBy: sum
		sourceColumn: any_tancament

		annotation SummarizationSetBy = Automatic

	column durada_dies
		dataType: int64
		formatString: 0
		lineageTag: e9e0f2e6-cc98-4938-9594-18c5399c9186
		summarizeBy: sum
		sourceColumn: durada_dies

		annotation SummarizationSetBy = Automatic

	partition Tfuita_Tinst_2025 = m
		mode: import
		queryGroup: Auxiliares
		source = ```
				let
				    Origen = let
				    Origen = GoogleSheets.Contents(#"12_S7 desembre 2025_Tfuita_Tinst"),
				    #"Dades IW59_Table" = Origen{[name="Dades IW59",ItemKind="Table"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(#"Dades IW59_Table",{"Column23"}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(
				        #"Columnas quitadas",
				        [PromoteAllScalars=true]
				    ),
				 
				    // Renombrar todas las columnas
				    #"Columnas renombradas" = Table.TransformColumnNames(
				        #"Encabezados promovidos",
				        each
				            let
				                nombre = Text.Lower(_),
				 
				                // Eliminar tildes
				                sinTildes = Text.Replace(
				                    Text.Replace(
				                        Text.Replace(
				                            Text.Replace(
				                                Text.Replace(nombre, "á", "a"),
				                                "é", "e"
				                            ),
				                            "í", "i"
				                        ),
				                        "ó", "o"
				                    ),
				                    "ú", "u"
				                ),
				 
				                // Reemplazar caracteres por _
				                reemplazado = Text.Replace(
				                    Text.Replace(
				                        Text.Replace(
				                            Text.Replace(
				                                sinTildes,
				                                " ", "_"
				                            ),
				                            "(", "_"
				                        ),
				                        ")", "_"
				                    ),
				                    "-", "_"
				                ),
				 
				                // Eliminar _ duplicados
				                limpio = Text.Combine(
				                    List.Select(
				                        Text.Split(reemplazado, "_"),
				                        each _ <> ""
				                    ),
				                    "_"
				                )
				            in
				                limpio
				    ),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas renombradas",{{"aviso", Int64.Type}, {"clase_de_aviso", type text}, {"inicio_deseado", type date}, {"inicio_de_averia", type date}, {"hora_de_inicio_de_averia", type time}, {"hora_de_fin_de_averia", type time}, {"fin_de_averia", type date}, {"orden", Int64.Type}, {"creado_el", type date}, {"fecha_de_aviso", type date}, {"hora_del_aviso", type time}, {"creado_por", type text}, {"grupo_planificacion", type text}, {"descripcion", type text}, {"poblacion", type text}, {"ubicacion_tecnica", type text}, {"status_del_sistema", type text}, {"denominacion_de_la_ubicacion_tecnica", type text}, {"fecha_de_referencia", type date}, {"mes_tancament", Int64.Type}, {"any_tancament", Int64.Type}, {"durada_dies", Int64.Type}})
				in
				    #"Tipo cambiado"
				in
				    Origen
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

