table Tfuita_Tinst_2026
	lineageTag: 56b9679a-5908-4edb-a821-2e3a5afffa7c

	column aviso
		dataType: int64
		formatString: 0
		lineageTag: 4fef85dc-05a8-4527-a4a4-fe9b674b7bce
		summarizeBy: sum
		sourceColumn: aviso

		annotation SummarizationSetBy = Automatic

	column clase_de_aviso
		dataType: string
		lineageTag: b497ab07-5ea4-40e2-941f-0e8acf260967
		summarizeBy: none
		sourceColumn: clase_de_aviso

		annotation SummarizationSetBy = Automatic

	column inicio_deseado
		dataType: dateTime
		formatString: Long Date
		lineageTag: b4988f99-1afc-4106-9b98-0ce8f6413107
		summarizeBy: none
		sourceColumn: inicio_deseado

		variation Variación
			isDefault
			relationship: c1ba90d1-0eb8-488c-9c61-af64cdddbd0f
			defaultHierarchy: LocalDateTable_1080b848-c06f-4c6e-bfe9-01f4037340ef.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column inicio_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2c441e61-b3b6-4341-a6f8-7874ae49932b
		summarizeBy: none
		sourceColumn: inicio_de_averia

		variation Variación
			isDefault
			relationship: f7b34b4f-fef6-4367-ba1b-e9842353adb5
			defaultHierarchy: LocalDateTable_a095a497-4f4c-4e4d-87b6-0889c6da01c3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_de_inicio_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: e5aeb4ce-721a-4580-bac8-bf6df6ebffd1
		summarizeBy: none
		sourceColumn: hora_de_inicio_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column hora_de_fin_de_averia
		dataType: dateTime
		formatString: Long Time
		lineageTag: 4d283568-e2ee-4e06-b7f0-72c940221a4b
		summarizeBy: none
		sourceColumn: hora_de_fin_de_averia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column fin_de_averia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 461fb95d-a4cb-4ef4-ba83-193443b7ef4e
		summarizeBy: none
		sourceColumn: fin_de_averia

		variation Variación
			isDefault
			relationship: 6b68ad51-f4e3-4a37-9a7b-ae1b39f97eeb
			defaultHierarchy: LocalDateTable_8e22c806-a2ec-4626-bf0f-cf45eae01f28.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column orden
		dataType: int64
		formatString: 0
		lineageTag: b87fcba0-7ba6-46ae-9611-d8304b814b12
		summarizeBy: sum
		sourceColumn: orden

		annotation SummarizationSetBy = Automatic

	column creado_el
		dataType: dateTime
		formatString: Long Date
		lineageTag: fcdd4ecc-7134-4cb0-9e0b-6172a48c1043
		summarizeBy: none
		sourceColumn: creado_el

		variation Variación
			isDefault
			relationship: bc3b1982-f614-473b-8f45-b3b6a59fe07d
			defaultHierarchy: LocalDateTable_d331e20c-a22f-4911-b8cd-9944e9dcf21b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fecha_de_aviso
		dataType: dateTime
		formatString: Long Date
		lineageTag: ca01e8af-caf4-4acc-94ed-ff9f18b89f86
		summarizeBy: none
		sourceColumn: fecha_de_aviso

		variation Variación
			isDefault
			relationship: 1fc7c129-7b72-4b18-9455-7b6e29719c41
			defaultHierarchy: LocalDateTable_06517322-f69a-472a-aac6-42b3b6b70e77.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_del_aviso
		dataType: dateTime
		formatString: Long Time
		lineageTag: 3c944e30-8bdd-4c5d-9235-7e8a1d17a7ba
		summarizeBy: none
		sourceColumn: hora_del_aviso

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column creado_por
		dataType: string
		lineageTag: b95cb6d2-00c6-48c0-92b3-54c5787f0f39
		summarizeBy: none
		sourceColumn: creado_por

		annotation SummarizationSetBy = Automatic

	column grupo_planificacion
		dataType: string
		lineageTag: 9aee359b-f6b3-46ac-a052-ac72a831fd96
		summarizeBy: none
		sourceColumn: grupo_planificacion

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		lineageTag: 57cc907e-642f-4ae8-8830-3b0342eac032
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	column poblacion
		dataType: string
		lineageTag: 6ffb43df-2dab-418b-986b-bdf68db92d4b
		summarizeBy: none
		sourceColumn: poblacion

		annotation SummarizationSetBy = Automatic

	column ubicacion_tecnica
		dataType: string
		lineageTag: 77bb3d45-8ee5-4701-bc1e-caedbeeebe5f
		summarizeBy: none
		sourceColumn: ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column status_del_sistema
		dataType: string
		lineageTag: 5c35ea37-b17a-4275-a7f7-6b7b90f7a88a
		summarizeBy: none
		sourceColumn: status_del_sistema

		annotation SummarizationSetBy = Automatic

	column denominacion_de_la_ubicacion_tecnica
		dataType: string
		lineageTag: a0e1f2ff-aa1e-4481-8c36-f708bb2bb3d5
		summarizeBy: none
		sourceColumn: denominacion_de_la_ubicacion_tecnica

		annotation SummarizationSetBy = Automatic

	column fecha_de_referencia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0dc35f54-6666-4282-99ea-4426cb2e07e9
		summarizeBy: none
		sourceColumn: fecha_de_referencia

		variation Variación
			isDefault
			relationship: a93f1e6d-4539-4991-bb66-5aea0f2af7de
			defaultHierarchy: LocalDateTable_c20b1b5b-2211-447c-b021-e5b88a8e83da.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column mes_tancament
		dataType: int64
		formatString: 0
		lineageTag: 58dd2a32-c0c1-414b-8c44-251627014048
		summarizeBy: sum
		sourceColumn: mes_tancament

		annotation SummarizationSetBy = Automatic

	column any_tancament
		dataType: int64
		formatString: 0
		lineageTag: 099a3f67-bcef-4511-828b-913272d409d1
		summarizeBy: sum
		sourceColumn: any_tancament

		annotation SummarizationSetBy = Automatic

	column durada_dies
		dataType: int64
		formatString: 0
		lineageTag: 1589bf21-cd1e-4989-a853-b2e603de6986
		summarizeBy: sum
		sourceColumn: durada_dies

		annotation SummarizationSetBy = Automatic

	partition Tfuita_Tinst_2026 = m
		mode: import
		queryGroup: Tfuita_Tinst
		source =
				let
				    Origen = GoogleSheets.Contents(#"12_S7 desembre 2026_Tfuita_Tinst"),
				    #"Dades IW59_Table" = Origen{[name="Dades IW59",ItemKind="Table"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(#"Dades IW59_Table",{"Column23"}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(
				        #"Columnas quitadas",
				        [PromoteAllScalars=true]
				    ),
				
				    // Renombrar todas las columnas
				    #"Columnas renombradas" = Table.TransformColumnNames(
				        #"Encabezados promovidos",
				        each
				            let
				                nombre = Text.Lower(_),
				
				                // Eliminar tildes
				                sinTildes = Text.Replace(
				                    Text.Replace(
				                        Text.Replace(
				                            Text.Replace(
				                                Text.Replace(nombre, "á", "a"),
				                                "é", "e"
				                            ),
				                            "í", "i"
				                        ),
				                        "ó", "o"
				                    ),
				                    "ú", "u"
				                ),
				
				                // Reemplazar caracteres por _
				                reemplazado = Text.Replace(
				                    Text.Replace(
				                        Text.Replace(
				                            Text.Replace(
				                                sinTildes,
				                                " ", "_"
				                            ),
				                            "(", "_"
				                        ),
				                        ")", "_"
				                    ),
				                    "-", "_"
				                ),
				
				                // Eliminar _ duplicados
				                limpio = Text.Combine(
				                    List.Select(
				                        Text.Split(reemplazado, "_"),
				                        each _ <> ""
				                    ),
				                    "_"
				                )
				            in
				                limpio
				    ),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas renombradas",{{"aviso", Int64.Type}, {"clase_de_aviso", type text}, {"inicio_deseado", type date}, {"inicio_de_averia", type date}, {"hora_de_inicio_de_averia", type time}, {"hora_de_fin_de_averia", type time}, {"fin_de_averia", type date}, {"orden", Int64.Type}, {"creado_el", type date}, {"fecha_de_aviso", type date}, {"hora_del_aviso", type time}, {"creado_por", type text}, {"grupo_planificacion", type text}, {"descripcion", type text}, {"poblacion", type text}, {"ubicacion_tecnica", type text}, {"status_del_sistema", type text}, {"denominacion_de_la_ubicacion_tecnica", type text}, {"fecha_de_referencia", type date}, {"mes_tancament", Int64.Type}, {"any_tancament", Int64.Type}, {"durada_dies", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

