let
    // Cargar CSV
    Source = Csv.Document(
        Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vR302uR0UWHuftN7Gg_n5lmBV362VvX3CUFriWq-DnLdv1VDD4rdxEujWleVopHsA/pub?output=csv"),
        [Delimiter=",", Columns=27, Encoding=65001, QuoteStyle=QuoteStyle.None]
    ),

    // Mantener solo las columnas necesarias
    KeepCols = Table.SelectColumns(Source, List.Transform({1..14}, each "Column" & Text.From(_))),

    // Convertir a texto solo las columnas utilizadas
    ToText = Table.TransformColumnTypes(
        KeepCols,
        List.Transform(Table.ColumnNames(KeepCols), each {_, type text}),
        "es"
    ),

    // Rellenar arteria
    FillArteria =
        Table.FillDown(
            Table.ReplaceValue(ToText, "", null, Replacer.ReplaceValue, {"Column1"}),
            {"Column1"}
        ),

    // Saltar filas y promover encabezados
    Headers =
        Table.PromoteHeaders(
            Table.Skip(FillArteria, 3),
            [PromoteAllScalars=true]
        ),

    // Renombrar
    Rename =
        Table.RenameColumns(
            Headers,
            {
                {"", "tipo"},
                {"Artèria Transport", "arteria"}
            }
        ),

    // Filtrar únicamente registros válidos
    Filtered =
        Table.SelectRows(Rename, each [tipo] <> "rendiment (%)"),

    // Despivotar
    Unpivoted =
        Table.UnpivotOtherColumns(
            Filtered,
            {"arteria", "tipo"},
            "date",
            "valor"
        ),

    // Convertir valor numérico
    NumericValue =
        Table.TransformColumns(
            Unpivoted,
            {{"valor", each Int64.From(Text.Replace(_, ",", "")), Int64.Type}}
        ),

    // Pivotar
    Pivoted =
        Table.Pivot(
            NumericValue,
            List.Distinct(NumericValue[tipo]),
            "tipo",
            "valor"
        ),

    // Renombrar medidas
    Measures =
        Table.RenameColumns(
            Pivoted,
            {
                {"sortit (m3)", "sortit_m3"},
                {"entrat (m3)", "entrat_m3"}
            }
        ),

    // Columnas calculadas
    AddColumns =
        Table.AddColumn(
            Table.AddColumn(
                Table.AddColumn(
                    Measures,
                    "gerencia",
                    each "Llobregat Sud",
                    type text
                ),
                "rendiment",
                each try [sortit_m3] / [entrat_m3] otherwise null,
                type number
            ),
            "anr_m3",
            each [entrat_m3] - [sortit_m3],
            Int64.Type
        ),

    // Tipos finales
    FinalTypes =
        Table.TransformColumnTypes(
            AddColumns,
            {{"date", type date}}
        ),

    Result =
        Table.Sort(
            Table.ReorderColumns(
                FinalTypes,
                {
                    "date",
                    "gerencia",
                    "arteria",
                    "sortit_m3",
                    "entrat_m3",
                    "rendiment",
                    "anr_m3"
                }
            ),
            {{"date", Order.Ascending}}
        ),
    #"Filas filtradas" = Table.SelectRows(Result, each ([arteria] <> "Total")),
    #"Filas ordenadas" = Table.Sort(#"Filas filtradas",{{"arteria", Order.Ascending}, {"date", Order.Ascending}})
in
    #"Filas ordenadas" 