let
  Origen = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vQYF-6nyJqkaezSpkqBN_a0Qmxw1GysBfL8py3eq4WzwX0xzzitdfbvqMzf9D-0YQ/pub?gid=664401204&single=true&output=csv"),[Delimiter=",", Columns=48, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Filas superiores quitadas" = Table.Skip(Origen,374),
    #"Conservar filas superiores" = Table.FirstN(#"Filas superiores quitadas",13),
    #"Encabezados promovidos" = Table.PromoteHeaders(#"Conservar filas superiores", [PromoteAllScalars=true]),
    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"Mes", "L (km) ", "Nombre escomeses", "Nombre Submin.", "L (km) _1", "Nombre escomeses_2", "Nombre Submin._3", "L (km) _4", "Nombre escomeses_5", "Nombre Submin._6", "L (km) _7", "Nombre escomeses_8", "Nombre Submin._9", "L (km) _10", "Nombre escomeses_11", "Nombre Submin._12", "L (km) _13", "Nombre escomeses_14", "Nombre Submin._15", "L (km) _16", "Nombre escomeses Controlades", "Nombre Subministraments Controlades", "L (km)", "L + T (km)", "Nombre Escomeses Totals", "Nombre Subministraments Totals"}),
    #"Personalizada agregada" = Table.AddColumn(#"Otras columnas quitadas", "fecha", each let
    txt0  = [Mes],
    // pasar a minúsculas
    txt1  = Text.Lower(txt0),
    // quitar "de ", "d’" y puntos
    txt2  = Text.Replace(Text.Replace(Text.Replace(txt1,"de ",""),"d’",""),".",""),
    // separar mes y año por el guion -
    mesTxt = Text.BeforeDelimiter(txt2,"-"),
    anioTxt = Text.AfterDelimiter(txt2,"-"),
    // convertir año tipo "21" -> 2021
    anio = 2000 + Number.FromText(anioTxt),
    // mapear mes catalán -> número
    mes = 
        if mesTxt = "gen"  then 1 else
        if mesTxt = "febr" then 2 else
        if mesTxt = "març" then 3 else
        if mesTxt = "abr"  then 4 else
        if mesTxt = "maig" then 5 else
        if mesTxt = "juny" then 6 else
        if mesTxt = "jul"  then 7 else
        if mesTxt = "ag"   then 8 else
        if mesTxt = "set"  then 9 else
        if mesTxt = "oct"  then 10 else
        if mesTxt = "nov"  then 11 else
        if mesTxt = "des"  then 12 else
        null
in
    #date(anio, mes, 1))
in
    #"Personalizada agregada"