let
    Source = Csv.Document(
        Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vRS1zkWHKwzcm2ZLhnMstWbjgJtQC3DCBLdSY_mCFGtR3x8Z4xdlut8iUNJwB5KVQ/pub?gid=315911922&single=true&output=csv"),
        [Delimiter = ",", Columns = 48, Encoding = 65001, QuoteStyle = QuoteStyle.None]
    ),
    Data =
        Table.PromoteHeaders(
            Table.SelectColumns(
                Table.Range(Source, 4, 13),
                {"Column1", "Column2", "Column3", "Column4", "Column5"}
            ),
            [PromoteAllScalars = true]
        ),
    Renamed =
        Table.RenameColumns(Data,{{"Any", "fecha"}, {"Aigua Lliurada (hm3)", "lliurada_hm3"}, {"Aigua Consumida (hm3)", "consumida_hm3"}, {"RTH Global", "rth_global"}, {"ANR Global (hm3)", "anr_global_hm3"}}),
    ReplaceDots =
        Table.TransformColumns(
            Renamed,
            List.Transform(
                List.RemoveItems(Table.ColumnNames(Renamed), {"date"}),
                each {_, (x) => Text.Replace(x, ".", ","), type text}
            )
        ),
    Result =
        Table.TransformColumnTypes(
            ReplaceDots,
            {
                {"fecha", type date},
                {"lliurada_hm3", type number},
                {"consumida_hm3", type number},
                {"rth_global", type number},
                {"anr_global_hm3", type number}
            }
        )
in
    Result